/*
FlashBlade REST API

OpenAPI specification for FlashBlade REST API, developed by Everpure, Inc. (https://www.everpuredata.com/).

API version: 2.22
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the ReferenceWithoutType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReferenceWithoutType{}

// ReferenceWithoutType struct for ReferenceWithoutType
type ReferenceWithoutType struct {
	// A globally unique, system-generated ID. The ID cannot be modified.
	Id *string `json:"id,omitempty"`
	// The resource name, such as volume name, pod name, snapshot name, and so on.
	Name *string `json:"name,omitempty"`
}

// NewReferenceWithoutType instantiates a new ReferenceWithoutType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReferenceWithoutType() *ReferenceWithoutType {
	this := ReferenceWithoutType{}
	return &this
}

// NewReferenceWithoutTypeWithDefaults instantiates a new ReferenceWithoutType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReferenceWithoutTypeWithDefaults() *ReferenceWithoutType {
	this := ReferenceWithoutType{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ReferenceWithoutType) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferenceWithoutType) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ReferenceWithoutType) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ReferenceWithoutType) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ReferenceWithoutType) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferenceWithoutType) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ReferenceWithoutType) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ReferenceWithoutType) SetName(v string) {
	o.Name = &v
}

func (o ReferenceWithoutType) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReferenceWithoutType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableReferenceWithoutType struct {
	value *ReferenceWithoutType
	isSet bool
}

func (v NullableReferenceWithoutType) Get() *ReferenceWithoutType {
	return v.value
}

func (v *NullableReferenceWithoutType) Set(val *ReferenceWithoutType) {
	v.value = val
	v.isSet = true
}

func (v NullableReferenceWithoutType) IsSet() bool {
	return v.isSet
}

func (v *NullableReferenceWithoutType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReferenceWithoutType(val *ReferenceWithoutType) *NullableReferenceWithoutType {
	return &NullableReferenceWithoutType{value: val, isSet: true}
}

func (v NullableReferenceWithoutType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReferenceWithoutType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
