/*
FlashArray REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.38
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the DirectoryServiceRole type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DirectoryServiceRole{}

// DirectoryServiceRole struct for DirectoryServiceRole
type DirectoryServiceRole struct {
	// A user-specified name. The name must be locally unique and cannot be changed.
	Name *string `json:"name,omitempty"`
	// Group name that contains users with the abilities granted by the associated policies.
	Group *string `json:"group,omitempty"`
	// Specifies where the configured group is located in the directory tree.
	GroupBase *string `json:"group_base,omitempty"`
	// List of management access policies associated with the group.
	ManagementAccessPolicies []FixedReferenceWithType `json:"management_access_policies,omitempty"`
	// This field has been deprecated. Predecessor to management access policies.
	Role *ReferenceNoId `json:"role,omitempty"`
}

// NewDirectoryServiceRole instantiates a new DirectoryServiceRole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDirectoryServiceRole() *DirectoryServiceRole {
	this := DirectoryServiceRole{}
	return &this
}

// NewDirectoryServiceRoleWithDefaults instantiates a new DirectoryServiceRole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDirectoryServiceRoleWithDefaults() *DirectoryServiceRole {
	this := DirectoryServiceRole{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DirectoryServiceRole) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryServiceRole) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DirectoryServiceRole) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DirectoryServiceRole) SetName(v string) {
	o.Name = &v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *DirectoryServiceRole) GetGroup() string {
	if o == nil || IsNil(o.Group) {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryServiceRole) GetGroupOk() (*string, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *DirectoryServiceRole) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *DirectoryServiceRole) SetGroup(v string) {
	o.Group = &v
}

// GetGroupBase returns the GroupBase field value if set, zero value otherwise.
func (o *DirectoryServiceRole) GetGroupBase() string {
	if o == nil || IsNil(o.GroupBase) {
		var ret string
		return ret
	}
	return *o.GroupBase
}

// GetGroupBaseOk returns a tuple with the GroupBase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryServiceRole) GetGroupBaseOk() (*string, bool) {
	if o == nil || IsNil(o.GroupBase) {
		return nil, false
	}
	return o.GroupBase, true
}

// HasGroupBase returns a boolean if a field has been set.
func (o *DirectoryServiceRole) HasGroupBase() bool {
	if o != nil && !IsNil(o.GroupBase) {
		return true
	}

	return false
}

// SetGroupBase gets a reference to the given string and assigns it to the GroupBase field.
func (o *DirectoryServiceRole) SetGroupBase(v string) {
	o.GroupBase = &v
}

// GetManagementAccessPolicies returns the ManagementAccessPolicies field value if set, zero value otherwise.
func (o *DirectoryServiceRole) GetManagementAccessPolicies() []FixedReferenceWithType {
	if o == nil || IsNil(o.ManagementAccessPolicies) {
		var ret []FixedReferenceWithType
		return ret
	}
	return o.ManagementAccessPolicies
}

// GetManagementAccessPoliciesOk returns a tuple with the ManagementAccessPolicies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryServiceRole) GetManagementAccessPoliciesOk() ([]FixedReferenceWithType, bool) {
	if o == nil || IsNil(o.ManagementAccessPolicies) {
		return nil, false
	}
	return o.ManagementAccessPolicies, true
}

// HasManagementAccessPolicies returns a boolean if a field has been set.
func (o *DirectoryServiceRole) HasManagementAccessPolicies() bool {
	if o != nil && !IsNil(o.ManagementAccessPolicies) {
		return true
	}

	return false
}

// SetManagementAccessPolicies gets a reference to the given []FixedReferenceWithType and assigns it to the ManagementAccessPolicies field.
func (o *DirectoryServiceRole) SetManagementAccessPolicies(v []FixedReferenceWithType) {
	o.ManagementAccessPolicies = v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *DirectoryServiceRole) GetRole() ReferenceNoId {
	if o == nil || IsNil(o.Role) {
		var ret ReferenceNoId
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectoryServiceRole) GetRoleOk() (*ReferenceNoId, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *DirectoryServiceRole) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given ReferenceNoId and assigns it to the Role field.
func (o *DirectoryServiceRole) SetRole(v ReferenceNoId) {
	o.Role = &v
}

func (o DirectoryServiceRole) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DirectoryServiceRole) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	if !IsNil(o.GroupBase) {
		toSerialize["group_base"] = o.GroupBase
	}
	if !IsNil(o.ManagementAccessPolicies) {
		toSerialize["management_access_policies"] = o.ManagementAccessPolicies
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

type NullableDirectoryServiceRole struct {
	value *DirectoryServiceRole
	isSet bool
}

func (v NullableDirectoryServiceRole) Get() *DirectoryServiceRole {
	return v.value
}

func (v *NullableDirectoryServiceRole) Set(val *DirectoryServiceRole) {
	v.value = val
	v.isSet = true
}

func (v NullableDirectoryServiceRole) IsSet() bool {
	return v.isSet
}

func (v *NullableDirectoryServiceRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDirectoryServiceRole(val *DirectoryServiceRole) *NullableDirectoryServiceRole {
	return &NullableDirectoryServiceRole{value: val, isSet: true}
}

func (v NullableDirectoryServiceRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDirectoryServiceRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
