/*
FlashBlade REST API

OpenAPI specification for FlashBlade REST API, developed by Everpure, Inc. (https://www.everpuredata.com/).

API version: 2.21
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the NodeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodeResponse{}

// NodeResponse struct for NodeResponse
type NodeResponse struct {
	// A list of node objects.
	Items []Node `json:"items,omitempty"`
}

// NewNodeResponse instantiates a new NodeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodeResponse() *NodeResponse {
	this := NodeResponse{}
	return &this
}

// NewNodeResponseWithDefaults instantiates a new NodeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodeResponseWithDefaults() *NodeResponse {
	this := NodeResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *NodeResponse) GetItems() []Node {
	if o == nil || IsNil(o.Items) {
		var ret []Node
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodeResponse) GetItemsOk() ([]Node, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *NodeResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Node and assigns it to the Items field.
func (o *NodeResponse) SetItems(v []Node) {
	o.Items = v
}

func (o NodeResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableNodeResponse struct {
	value *NodeResponse
	isSet bool
}

func (v NullableNodeResponse) Get() *NodeResponse {
	return v.value
}

func (v *NullableNodeResponse) Set(val *NodeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNodeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNodeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodeResponse(val *NodeResponse) *NullableNodeResponse {
	return &NullableNodeResponse{value: val, isSet: true}
}

func (v NullableNodeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
