/*
FlashArray REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.32
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the DirectorySnapshot type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DirectorySnapshot{}

// DirectorySnapshot struct for DirectorySnapshot
type DirectorySnapshot struct {
	// A globally unique, system-generated ID. The ID cannot be modified and cannot refer to another resource.
	Id *string `json:"id,omitempty"`
	// A user-specified name. The name must be locally unique and can be changed.
	Name *string `json:"name,omitempty"`
	// The customizable portion of the client-visible snapshot name. A full snapshot name is constructed in the form of `DIR.CLIENT_NAME.SUFFIX` where `DIR` is the full managed directory name, `CLIENT_NAME` is the client name, and `SUFFIX` is the suffix. The client-visible snapshot name is `CLIENT_NAME.SUFFIX`.
	ClientName *string `json:"client_name,omitempty"`
	// The snapshot creation time, measured in milliseconds since the UNIX epoch.
	Created *int64 `json:"created,omitempty"`
	// Returns a value of `true` if the snapshot has been destroyed and is pending eradication. The `time_remaining` value displays the amount of time left until the destroyed directory snapshot is permanently eradicated. Before the `time_remaining` period has elapsed, the destroyed directory snapshot can be recovered by setting `destroyed=false`. Once the `time_remaining` period has elapsed, the directory snapshot is permanently eradicated and can no longer be recovered.
	Destroyed *bool `json:"destroyed,omitempty"`
	// The snapshot policy that manages this snapshot, if applicable.
	Policy *FixedReference `json:"policy,omitempty"`
	// The directory from which this snapshot was taken.
	Source *FixedReference `json:"source,omitempty"`
	// Displays size and space consumption information.
	Space *Space `json:"space,omitempty"`
	// The suffix that is appended to the `source_name` value and the `client_name` value to generate the full directory snapshot name in the form of `DIR.CLIENT_NAME.SUFFIX` where `DIR` is the managed directory name, `CLIENT_NAME` is the client name, and `SUFFIX` is the suffix. If the suffix is a string, this field returns `null`. See the `name` value for the full snapshot name including the suffix.
	Suffix *int64 `json:"suffix,omitempty"`
	// The amount of time left until the directory snapshot is permanently eradicated, measured in milliseconds. Before the `time_remaining` period has elapsed, the snapshot can be recovered by setting `destroyed=false` if it is destroyed, by setting `policy=\"\"` if it is managed by a snapshot policy, or by setting `keep_for=\"\"` if it is a manual snapshot.
	TimeRemaining *int64 `json:"time_remaining,omitempty"`
}

// NewDirectorySnapshot instantiates a new DirectorySnapshot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDirectorySnapshot() *DirectorySnapshot {
	this := DirectorySnapshot{}
	return &this
}

// NewDirectorySnapshotWithDefaults instantiates a new DirectorySnapshot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDirectorySnapshotWithDefaults() *DirectorySnapshot {
	this := DirectorySnapshot{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DirectorySnapshot) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectorySnapshot) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DirectorySnapshot) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DirectorySnapshot) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DirectorySnapshot) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectorySnapshot) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DirectorySnapshot) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DirectorySnapshot) SetName(v string) {
	o.Name = &v
}

// GetClientName returns the ClientName field value if set, zero value otherwise.
func (o *DirectorySnapshot) GetClientName() string {
	if o == nil || IsNil(o.ClientName) {
		var ret string
		return ret
	}
	return *o.ClientName
}

// GetClientNameOk returns a tuple with the ClientName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectorySnapshot) GetClientNameOk() (*string, bool) {
	if o == nil || IsNil(o.ClientName) {
		return nil, false
	}
	return o.ClientName, true
}

// HasClientName returns a boolean if a field has been set.
func (o *DirectorySnapshot) HasClientName() bool {
	if o != nil && !IsNil(o.ClientName) {
		return true
	}

	return false
}

// SetClientName gets a reference to the given string and assigns it to the ClientName field.
func (o *DirectorySnapshot) SetClientName(v string) {
	o.ClientName = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *DirectorySnapshot) GetCreated() int64 {
	if o == nil || IsNil(o.Created) {
		var ret int64
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectorySnapshot) GetCreatedOk() (*int64, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *DirectorySnapshot) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given int64 and assigns it to the Created field.
func (o *DirectorySnapshot) SetCreated(v int64) {
	o.Created = &v
}

// GetDestroyed returns the Destroyed field value if set, zero value otherwise.
func (o *DirectorySnapshot) GetDestroyed() bool {
	if o == nil || IsNil(o.Destroyed) {
		var ret bool
		return ret
	}
	return *o.Destroyed
}

// GetDestroyedOk returns a tuple with the Destroyed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectorySnapshot) GetDestroyedOk() (*bool, bool) {
	if o == nil || IsNil(o.Destroyed) {
		return nil, false
	}
	return o.Destroyed, true
}

// HasDestroyed returns a boolean if a field has been set.
func (o *DirectorySnapshot) HasDestroyed() bool {
	if o != nil && !IsNil(o.Destroyed) {
		return true
	}

	return false
}

// SetDestroyed gets a reference to the given bool and assigns it to the Destroyed field.
func (o *DirectorySnapshot) SetDestroyed(v bool) {
	o.Destroyed = &v
}

// GetPolicy returns the Policy field value if set, zero value otherwise.
func (o *DirectorySnapshot) GetPolicy() FixedReference {
	if o == nil || IsNil(o.Policy) {
		var ret FixedReference
		return ret
	}
	return *o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectorySnapshot) GetPolicyOk() (*FixedReference, bool) {
	if o == nil || IsNil(o.Policy) {
		return nil, false
	}
	return o.Policy, true
}

// HasPolicy returns a boolean if a field has been set.
func (o *DirectorySnapshot) HasPolicy() bool {
	if o != nil && !IsNil(o.Policy) {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given FixedReference and assigns it to the Policy field.
func (o *DirectorySnapshot) SetPolicy(v FixedReference) {
	o.Policy = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *DirectorySnapshot) GetSource() FixedReference {
	if o == nil || IsNil(o.Source) {
		var ret FixedReference
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectorySnapshot) GetSourceOk() (*FixedReference, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *DirectorySnapshot) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given FixedReference and assigns it to the Source field.
func (o *DirectorySnapshot) SetSource(v FixedReference) {
	o.Source = &v
}

// GetSpace returns the Space field value if set, zero value otherwise.
func (o *DirectorySnapshot) GetSpace() Space {
	if o == nil || IsNil(o.Space) {
		var ret Space
		return ret
	}
	return *o.Space
}

// GetSpaceOk returns a tuple with the Space field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectorySnapshot) GetSpaceOk() (*Space, bool) {
	if o == nil || IsNil(o.Space) {
		return nil, false
	}
	return o.Space, true
}

// HasSpace returns a boolean if a field has been set.
func (o *DirectorySnapshot) HasSpace() bool {
	if o != nil && !IsNil(o.Space) {
		return true
	}

	return false
}

// SetSpace gets a reference to the given Space and assigns it to the Space field.
func (o *DirectorySnapshot) SetSpace(v Space) {
	o.Space = &v
}

// GetSuffix returns the Suffix field value if set, zero value otherwise.
func (o *DirectorySnapshot) GetSuffix() int64 {
	if o == nil || IsNil(o.Suffix) {
		var ret int64
		return ret
	}
	return *o.Suffix
}

// GetSuffixOk returns a tuple with the Suffix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectorySnapshot) GetSuffixOk() (*int64, bool) {
	if o == nil || IsNil(o.Suffix) {
		return nil, false
	}
	return o.Suffix, true
}

// HasSuffix returns a boolean if a field has been set.
func (o *DirectorySnapshot) HasSuffix() bool {
	if o != nil && !IsNil(o.Suffix) {
		return true
	}

	return false
}

// SetSuffix gets a reference to the given int64 and assigns it to the Suffix field.
func (o *DirectorySnapshot) SetSuffix(v int64) {
	o.Suffix = &v
}

// GetTimeRemaining returns the TimeRemaining field value if set, zero value otherwise.
func (o *DirectorySnapshot) GetTimeRemaining() int64 {
	if o == nil || IsNil(o.TimeRemaining) {
		var ret int64
		return ret
	}
	return *o.TimeRemaining
}

// GetTimeRemainingOk returns a tuple with the TimeRemaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectorySnapshot) GetTimeRemainingOk() (*int64, bool) {
	if o == nil || IsNil(o.TimeRemaining) {
		return nil, false
	}
	return o.TimeRemaining, true
}

// HasTimeRemaining returns a boolean if a field has been set.
func (o *DirectorySnapshot) HasTimeRemaining() bool {
	if o != nil && !IsNil(o.TimeRemaining) {
		return true
	}

	return false
}

// SetTimeRemaining gets a reference to the given int64 and assigns it to the TimeRemaining field.
func (o *DirectorySnapshot) SetTimeRemaining(v int64) {
	o.TimeRemaining = &v
}

func (o DirectorySnapshot) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DirectorySnapshot) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ClientName) {
		toSerialize["client_name"] = o.ClientName
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Destroyed) {
		toSerialize["destroyed"] = o.Destroyed
	}
	if !IsNil(o.Policy) {
		toSerialize["policy"] = o.Policy
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.Space) {
		toSerialize["space"] = o.Space
	}
	if !IsNil(o.Suffix) {
		toSerialize["suffix"] = o.Suffix
	}
	if !IsNil(o.TimeRemaining) {
		toSerialize["time_remaining"] = o.TimeRemaining
	}
	return toSerialize, nil
}

type NullableDirectorySnapshot struct {
	value *DirectorySnapshot
	isSet bool
}

func (v NullableDirectorySnapshot) Get() *DirectorySnapshot {
	return v.value
}

func (v *NullableDirectorySnapshot) Set(val *DirectorySnapshot) {
	v.value = val
	v.isSet = true
}

func (v NullableDirectorySnapshot) IsSet() bool {
	return v.isSet
}

func (v *NullableDirectorySnapshot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDirectorySnapshot(val *DirectorySnapshot) *NullableDirectorySnapshot {
	return &NullableDirectorySnapshot{value: val, isSet: true}
}

func (v NullableDirectorySnapshot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDirectorySnapshot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
