/*
FlashArray REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.27
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the HostGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostGetResponse{}

// HostGetResponse struct for HostGetResponse
type HostGetResponse struct {
	// Continuation token that can be provided in the `continuation_token` query param to get the next page of data. If you use the continuation token to page through data you are guaranteed to get all items exactly once regardless of how items are modified. If an item is added or deleted during the pagination then it may or may not be returned. The continuation token is generated if the limit is less than the remaining number of items, and the default sort is used (no sort is specified).
	ContinuationToken *string `json:"continuation_token,omitempty"`
	// Returns a value of `true` if subsequent items can be retrieved.
	MoreItemsRemaining *bool `json:"more_items_remaining,omitempty"`
	// The total number of records after applying all filter query parameters. The `total_item_count` will be calculated if and only if the corresponding query parameter `total_item_count` is set to `true`. If this query parameter is not set or set to `false`, a value of `null` will be returned.
	TotalItemCount *int32 `json:"total_item_count,omitempty"`
	// Returns a list of all items after filtering. If applicable, the values are displayed for each name.
	Items []Host `json:"items,omitempty"`
}

// NewHostGetResponse instantiates a new HostGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostGetResponse() *HostGetResponse {
	this := HostGetResponse{}
	return &this
}

// NewHostGetResponseWithDefaults instantiates a new HostGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostGetResponseWithDefaults() *HostGetResponse {
	this := HostGetResponse{}
	return &this
}

// GetContinuationToken returns the ContinuationToken field value if set, zero value otherwise.
func (o *HostGetResponse) GetContinuationToken() string {
	if o == nil || IsNil(o.ContinuationToken) {
		var ret string
		return ret
	}
	return *o.ContinuationToken
}

// GetContinuationTokenOk returns a tuple with the ContinuationToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HostGetResponse) GetContinuationTokenOk() (*string, bool) {
	if o == nil || IsNil(o.ContinuationToken) {
		return nil, false
	}
	return o.ContinuationToken, true
}

// HasContinuationToken returns a boolean if a field has been set.
func (o *HostGetResponse) HasContinuationToken() bool {
	if o != nil && !IsNil(o.ContinuationToken) {
		return true
	}

	return false
}

// SetContinuationToken gets a reference to the given string and assigns it to the ContinuationToken field.
func (o *HostGetResponse) SetContinuationToken(v string) {
	o.ContinuationToken = &v
}

// GetMoreItemsRemaining returns the MoreItemsRemaining field value if set, zero value otherwise.
func (o *HostGetResponse) GetMoreItemsRemaining() bool {
	if o == nil || IsNil(o.MoreItemsRemaining) {
		var ret bool
		return ret
	}
	return *o.MoreItemsRemaining
}

// GetMoreItemsRemainingOk returns a tuple with the MoreItemsRemaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HostGetResponse) GetMoreItemsRemainingOk() (*bool, bool) {
	if o == nil || IsNil(o.MoreItemsRemaining) {
		return nil, false
	}
	return o.MoreItemsRemaining, true
}

// HasMoreItemsRemaining returns a boolean if a field has been set.
func (o *HostGetResponse) HasMoreItemsRemaining() bool {
	if o != nil && !IsNil(o.MoreItemsRemaining) {
		return true
	}

	return false
}

// SetMoreItemsRemaining gets a reference to the given bool and assigns it to the MoreItemsRemaining field.
func (o *HostGetResponse) SetMoreItemsRemaining(v bool) {
	o.MoreItemsRemaining = &v
}

// GetTotalItemCount returns the TotalItemCount field value if set, zero value otherwise.
func (o *HostGetResponse) GetTotalItemCount() int32 {
	if o == nil || IsNil(o.TotalItemCount) {
		var ret int32
		return ret
	}
	return *o.TotalItemCount
}

// GetTotalItemCountOk returns a tuple with the TotalItemCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HostGetResponse) GetTotalItemCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalItemCount) {
		return nil, false
	}
	return o.TotalItemCount, true
}

// HasTotalItemCount returns a boolean if a field has been set.
func (o *HostGetResponse) HasTotalItemCount() bool {
	if o != nil && !IsNil(o.TotalItemCount) {
		return true
	}

	return false
}

// SetTotalItemCount gets a reference to the given int32 and assigns it to the TotalItemCount field.
func (o *HostGetResponse) SetTotalItemCount(v int32) {
	o.TotalItemCount = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *HostGetResponse) GetItems() []Host {
	if o == nil || IsNil(o.Items) {
		var ret []Host
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HostGetResponse) GetItemsOk() ([]Host, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *HostGetResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Host and assigns it to the Items field.
func (o *HostGetResponse) SetItems(v []Host) {
	o.Items = v
}

func (o HostGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContinuationToken) {
		toSerialize["continuation_token"] = o.ContinuationToken
	}
	if !IsNil(o.MoreItemsRemaining) {
		toSerialize["more_items_remaining"] = o.MoreItemsRemaining
	}
	if !IsNil(o.TotalItemCount) {
		toSerialize["total_item_count"] = o.TotalItemCount
	}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableHostGetResponse struct {
	value *HostGetResponse
	isSet bool
}

func (v NullableHostGetResponse) Get() *HostGetResponse {
	return v.value
}

func (v *NullableHostGetResponse) Set(val *HostGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHostGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHostGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostGetResponse(val *HostGetResponse) *NullableHostGetResponse {
	return &NullableHostGetResponse{value: val, isSet: true}
}

func (v NullableHostGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
