/*
FlashBlade REST API

OpenAPI specification for FlashBlade REST API, developed by Everpure, Inc. (https://www.everpuredata.com/).

API version: 2.24
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the ManagementAuthenticationPolicyConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagementAuthenticationPolicyConfig{}

// ManagementAuthenticationPolicyConfig struct for ManagementAuthenticationPolicyConfig
type ManagementAuthenticationPolicyConfig struct {
	// The authentication methods that are allowed for this interface. It cannot contain duplicates.
	AllowedMethods []string `json:"allowed_methods,omitempty"`
	// The authentication methods that are required for this interface. It cannot contain duplicates. `default` is not allowed as a required method.
	RequiredMethods []string `json:"required_methods,omitempty"`
}

// NewManagementAuthenticationPolicyConfig instantiates a new ManagementAuthenticationPolicyConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagementAuthenticationPolicyConfig() *ManagementAuthenticationPolicyConfig {
	this := ManagementAuthenticationPolicyConfig{}
	return &this
}

// NewManagementAuthenticationPolicyConfigWithDefaults instantiates a new ManagementAuthenticationPolicyConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagementAuthenticationPolicyConfigWithDefaults() *ManagementAuthenticationPolicyConfig {
	this := ManagementAuthenticationPolicyConfig{}
	return &this
}

// GetAllowedMethods returns the AllowedMethods field value if set, zero value otherwise.
func (o *ManagementAuthenticationPolicyConfig) GetAllowedMethods() []string {
	if o == nil || IsNil(o.AllowedMethods) {
		var ret []string
		return ret
	}
	return o.AllowedMethods
}

// GetAllowedMethodsOk returns a tuple with the AllowedMethods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementAuthenticationPolicyConfig) GetAllowedMethodsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedMethods) {
		return nil, false
	}
	return o.AllowedMethods, true
}

// HasAllowedMethods returns a boolean if a field has been set.
func (o *ManagementAuthenticationPolicyConfig) HasAllowedMethods() bool {
	if o != nil && !IsNil(o.AllowedMethods) {
		return true
	}

	return false
}

// SetAllowedMethods gets a reference to the given []string and assigns it to the AllowedMethods field.
func (o *ManagementAuthenticationPolicyConfig) SetAllowedMethods(v []string) {
	o.AllowedMethods = v
}

// GetRequiredMethods returns the RequiredMethods field value if set, zero value otherwise.
func (o *ManagementAuthenticationPolicyConfig) GetRequiredMethods() []string {
	if o == nil || IsNil(o.RequiredMethods) {
		var ret []string
		return ret
	}
	return o.RequiredMethods
}

// GetRequiredMethodsOk returns a tuple with the RequiredMethods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementAuthenticationPolicyConfig) GetRequiredMethodsOk() ([]string, bool) {
	if o == nil || IsNil(o.RequiredMethods) {
		return nil, false
	}
	return o.RequiredMethods, true
}

// HasRequiredMethods returns a boolean if a field has been set.
func (o *ManagementAuthenticationPolicyConfig) HasRequiredMethods() bool {
	if o != nil && !IsNil(o.RequiredMethods) {
		return true
	}

	return false
}

// SetRequiredMethods gets a reference to the given []string and assigns it to the RequiredMethods field.
func (o *ManagementAuthenticationPolicyConfig) SetRequiredMethods(v []string) {
	o.RequiredMethods = v
}

func (o ManagementAuthenticationPolicyConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagementAuthenticationPolicyConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AllowedMethods) {
		toSerialize["allowed_methods"] = o.AllowedMethods
	}
	if !IsNil(o.RequiredMethods) {
		toSerialize["required_methods"] = o.RequiredMethods
	}
	return toSerialize, nil
}

type NullableManagementAuthenticationPolicyConfig struct {
	value *ManagementAuthenticationPolicyConfig
	isSet bool
}

func (v NullableManagementAuthenticationPolicyConfig) Get() *ManagementAuthenticationPolicyConfig {
	return v.value
}

func (v *NullableManagementAuthenticationPolicyConfig) Set(val *ManagementAuthenticationPolicyConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableManagementAuthenticationPolicyConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableManagementAuthenticationPolicyConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagementAuthenticationPolicyConfig(val *ManagementAuthenticationPolicyConfig) *NullableManagementAuthenticationPolicyConfig {
	return &NullableManagementAuthenticationPolicyConfig{value: val, isSet: true}
}

func (v NullableManagementAuthenticationPolicyConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagementAuthenticationPolicyConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
