/*
FlashBlade REST API

OpenAPI specification for FlashBlade REST API, developed by Everpure, Inc. (https://www.everpuredata.com/).

API version: 2.24
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the RealmDefaults type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RealmDefaults{}

// RealmDefaults struct for RealmDefaults
type RealmDefaults struct {
	// The context in which the operation was performed.  Valid values include a reference to any array which is a member of the same fleet or to the fleet itself.  Other parameters provided with the request, such as names of volumes or snapshots, are resolved relative to the provided `context`.
	Context *FixedReference `json:"context,omitempty"`
	// Default configurations for object store.
	ObjectStore []ObjectStoreDefault `json:"object_store,omitempty"`
	// Realm for the defaults.
	Realm *FixedReference `json:"realm,omitempty"`
}

// NewRealmDefaults instantiates a new RealmDefaults object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRealmDefaults() *RealmDefaults {
	this := RealmDefaults{}
	return &this
}

// NewRealmDefaultsWithDefaults instantiates a new RealmDefaults object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRealmDefaultsWithDefaults() *RealmDefaults {
	this := RealmDefaults{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *RealmDefaults) GetContext() FixedReference {
	if o == nil || IsNil(o.Context) {
		var ret FixedReference
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RealmDefaults) GetContextOk() (*FixedReference, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *RealmDefaults) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given FixedReference and assigns it to the Context field.
func (o *RealmDefaults) SetContext(v FixedReference) {
	o.Context = &v
}

// GetObjectStore returns the ObjectStore field value if set, zero value otherwise.
func (o *RealmDefaults) GetObjectStore() []ObjectStoreDefault {
	if o == nil || IsNil(o.ObjectStore) {
		var ret []ObjectStoreDefault
		return ret
	}
	return o.ObjectStore
}

// GetObjectStoreOk returns a tuple with the ObjectStore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RealmDefaults) GetObjectStoreOk() ([]ObjectStoreDefault, bool) {
	if o == nil || IsNil(o.ObjectStore) {
		return nil, false
	}
	return o.ObjectStore, true
}

// HasObjectStore returns a boolean if a field has been set.
func (o *RealmDefaults) HasObjectStore() bool {
	if o != nil && !IsNil(o.ObjectStore) {
		return true
	}

	return false
}

// SetObjectStore gets a reference to the given []ObjectStoreDefault and assigns it to the ObjectStore field.
func (o *RealmDefaults) SetObjectStore(v []ObjectStoreDefault) {
	o.ObjectStore = v
}

// GetRealm returns the Realm field value if set, zero value otherwise.
func (o *RealmDefaults) GetRealm() FixedReference {
	if o == nil || IsNil(o.Realm) {
		var ret FixedReference
		return ret
	}
	return *o.Realm
}

// GetRealmOk returns a tuple with the Realm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RealmDefaults) GetRealmOk() (*FixedReference, bool) {
	if o == nil || IsNil(o.Realm) {
		return nil, false
	}
	return o.Realm, true
}

// HasRealm returns a boolean if a field has been set.
func (o *RealmDefaults) HasRealm() bool {
	if o != nil && !IsNil(o.Realm) {
		return true
	}

	return false
}

// SetRealm gets a reference to the given FixedReference and assigns it to the Realm field.
func (o *RealmDefaults) SetRealm(v FixedReference) {
	o.Realm = &v
}

func (o RealmDefaults) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RealmDefaults) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.ObjectStore) {
		toSerialize["object_store"] = o.ObjectStore
	}
	if !IsNil(o.Realm) {
		toSerialize["realm"] = o.Realm
	}
	return toSerialize, nil
}

type NullableRealmDefaults struct {
	value *RealmDefaults
	isSet bool
}

func (v NullableRealmDefaults) Get() *RealmDefaults {
	return v.value
}

func (v *NullableRealmDefaults) Set(val *RealmDefaults) {
	v.value = val
	v.isSet = true
}

func (v NullableRealmDefaults) IsSet() bool {
	return v.isSet
}

func (v *NullableRealmDefaults) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRealmDefaults(val *RealmDefaults) *NullableRealmDefaults {
	return &NullableRealmDefaults{value: val, isSet: true}
}

func (v NullableRealmDefaults) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRealmDefaults) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
