/*
FlashArray REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.36
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the RealmPost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RealmPost{}

// RealmPost struct for RealmPost
type RealmPost struct {
	// Sets QoS limits.
	Qos *ContainerQos `json:"qos,omitempty"`
	// The logical quota limit of the realm, measured in bytes. Must be a multiple of 512.
	QuotaLimit *int64 `json:"quota_limit,omitempty"`
}

// NewRealmPost instantiates a new RealmPost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRealmPost() *RealmPost {
	this := RealmPost{}
	return &this
}

// NewRealmPostWithDefaults instantiates a new RealmPost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRealmPostWithDefaults() *RealmPost {
	this := RealmPost{}
	return &this
}

// GetQos returns the Qos field value if set, zero value otherwise.
func (o *RealmPost) GetQos() ContainerQos {
	if o == nil || IsNil(o.Qos) {
		var ret ContainerQos
		return ret
	}
	return *o.Qos
}

// GetQosOk returns a tuple with the Qos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RealmPost) GetQosOk() (*ContainerQos, bool) {
	if o == nil || IsNil(o.Qos) {
		return nil, false
	}
	return o.Qos, true
}

// HasQos returns a boolean if a field has been set.
func (o *RealmPost) HasQos() bool {
	if o != nil && !IsNil(o.Qos) {
		return true
	}

	return false
}

// SetQos gets a reference to the given ContainerQos and assigns it to the Qos field.
func (o *RealmPost) SetQos(v ContainerQos) {
	o.Qos = &v
}

// GetQuotaLimit returns the QuotaLimit field value if set, zero value otherwise.
func (o *RealmPost) GetQuotaLimit() int64 {
	if o == nil || IsNil(o.QuotaLimit) {
		var ret int64
		return ret
	}
	return *o.QuotaLimit
}

// GetQuotaLimitOk returns a tuple with the QuotaLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RealmPost) GetQuotaLimitOk() (*int64, bool) {
	if o == nil || IsNil(o.QuotaLimit) {
		return nil, false
	}
	return o.QuotaLimit, true
}

// HasQuotaLimit returns a boolean if a field has been set.
func (o *RealmPost) HasQuotaLimit() bool {
	if o != nil && !IsNil(o.QuotaLimit) {
		return true
	}

	return false
}

// SetQuotaLimit gets a reference to the given int64 and assigns it to the QuotaLimit field.
func (o *RealmPost) SetQuotaLimit(v int64) {
	o.QuotaLimit = &v
}

func (o RealmPost) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RealmPost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Qos) {
		toSerialize["qos"] = o.Qos
	}
	if !IsNil(o.QuotaLimit) {
		toSerialize["quota_limit"] = o.QuotaLimit
	}
	return toSerialize, nil
}

type NullableRealmPost struct {
	value *RealmPost
	isSet bool
}

func (v NullableRealmPost) Get() *RealmPost {
	return v.value
}

func (v *NullableRealmPost) Set(val *RealmPost) {
	v.value = val
	v.isSet = true
}

func (v NullableRealmPost) IsSet() bool {
	return v.isSet
}

func (v *NullableRealmPost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRealmPost(val *RealmPost) *NullableRealmPost {
	return &NullableRealmPost{value: val, isSet: true}
}

func (v NullableRealmPost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRealmPost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
