/*
FlashBlade REST API

OpenAPI specification for FlashBlade REST API, developed by Everpure, Inc. (https://www.everpuredata.com/).

API version: 2.23
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the ObjectStoreTrustPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObjectStoreTrustPolicy{}

// ObjectStoreTrustPolicy struct for ObjectStoreTrustPolicy
type ObjectStoreTrustPolicy struct {
	// A globally unique, system-generated ID. The ID cannot be modified and cannot refer to another resource.
	Id *string `json:"id,omitempty"`
	// A user-specified name. The name must be locally unique and can be changed.
	Name *string `json:"name,omitempty"`
	// If `true`, the policy is enabled. If not specified, defaults to `true`.
	Enabled *bool `json:"enabled,omitempty"`
	// Whether the policy is defined on the local array.
	IsLocal *bool `json:"is_local,omitempty"`
	// Reference to the array where the policy is defined.
	Location *FixedReference `json:"location,omitempty"`
	// Type of the policy. Valid values include `alert`, `audit`, `bucket-access`, `cross-origin-resource-sharing`, `network-access`, `nfs`, `object-access`, `s3-export`, smb-client`, `smb-share`, `ssh-certificate-authority`, and `telemetry-metrics`.
	PolicyType *string `json:"policy_type,omitempty"`
	// The realms containing this policy.
	Realms []FixedReference `json:"realms,omitempty"`
	// The context in which the operation was performed.  Valid values include a reference to any array which is a member of the same fleet or to the fleet itself.  Other parameters provided with the request, such as names of volumes or snapshots, are resolved relative to the provided `context`.
	Context *FixedReference `json:"context,omitempty"`
	// Object Store Role to which the Trust Policy applies.
	Role *FixedReference `json:"role,omitempty"`
	// List of rules establishing the trust policy
	Rules []TrustPolicyRule `json:"rules,omitempty"`
}

// NewObjectStoreTrustPolicy instantiates a new ObjectStoreTrustPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectStoreTrustPolicy() *ObjectStoreTrustPolicy {
	this := ObjectStoreTrustPolicy{}
	return &this
}

// NewObjectStoreTrustPolicyWithDefaults instantiates a new ObjectStoreTrustPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectStoreTrustPolicyWithDefaults() *ObjectStoreTrustPolicy {
	this := ObjectStoreTrustPolicy{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ObjectStoreTrustPolicy) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectStoreTrustPolicy) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ObjectStoreTrustPolicy) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ObjectStoreTrustPolicy) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ObjectStoreTrustPolicy) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectStoreTrustPolicy) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ObjectStoreTrustPolicy) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ObjectStoreTrustPolicy) SetName(v string) {
	o.Name = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *ObjectStoreTrustPolicy) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectStoreTrustPolicy) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *ObjectStoreTrustPolicy) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *ObjectStoreTrustPolicy) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetIsLocal returns the IsLocal field value if set, zero value otherwise.
func (o *ObjectStoreTrustPolicy) GetIsLocal() bool {
	if o == nil || IsNil(o.IsLocal) {
		var ret bool
		return ret
	}
	return *o.IsLocal
}

// GetIsLocalOk returns a tuple with the IsLocal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectStoreTrustPolicy) GetIsLocalOk() (*bool, bool) {
	if o == nil || IsNil(o.IsLocal) {
		return nil, false
	}
	return o.IsLocal, true
}

// HasIsLocal returns a boolean if a field has been set.
func (o *ObjectStoreTrustPolicy) HasIsLocal() bool {
	if o != nil && !IsNil(o.IsLocal) {
		return true
	}

	return false
}

// SetIsLocal gets a reference to the given bool and assigns it to the IsLocal field.
func (o *ObjectStoreTrustPolicy) SetIsLocal(v bool) {
	o.IsLocal = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *ObjectStoreTrustPolicy) GetLocation() FixedReference {
	if o == nil || IsNil(o.Location) {
		var ret FixedReference
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectStoreTrustPolicy) GetLocationOk() (*FixedReference, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *ObjectStoreTrustPolicy) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given FixedReference and assigns it to the Location field.
func (o *ObjectStoreTrustPolicy) SetLocation(v FixedReference) {
	o.Location = &v
}

// GetPolicyType returns the PolicyType field value if set, zero value otherwise.
func (o *ObjectStoreTrustPolicy) GetPolicyType() string {
	if o == nil || IsNil(o.PolicyType) {
		var ret string
		return ret
	}
	return *o.PolicyType
}

// GetPolicyTypeOk returns a tuple with the PolicyType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectStoreTrustPolicy) GetPolicyTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PolicyType) {
		return nil, false
	}
	return o.PolicyType, true
}

// HasPolicyType returns a boolean if a field has been set.
func (o *ObjectStoreTrustPolicy) HasPolicyType() bool {
	if o != nil && !IsNil(o.PolicyType) {
		return true
	}

	return false
}

// SetPolicyType gets a reference to the given string and assigns it to the PolicyType field.
func (o *ObjectStoreTrustPolicy) SetPolicyType(v string) {
	o.PolicyType = &v
}

// GetRealms returns the Realms field value if set, zero value otherwise.
func (o *ObjectStoreTrustPolicy) GetRealms() []FixedReference {
	if o == nil || IsNil(o.Realms) {
		var ret []FixedReference
		return ret
	}
	return o.Realms
}

// GetRealmsOk returns a tuple with the Realms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectStoreTrustPolicy) GetRealmsOk() ([]FixedReference, bool) {
	if o == nil || IsNil(o.Realms) {
		return nil, false
	}
	return o.Realms, true
}

// HasRealms returns a boolean if a field has been set.
func (o *ObjectStoreTrustPolicy) HasRealms() bool {
	if o != nil && !IsNil(o.Realms) {
		return true
	}

	return false
}

// SetRealms gets a reference to the given []FixedReference and assigns it to the Realms field.
func (o *ObjectStoreTrustPolicy) SetRealms(v []FixedReference) {
	o.Realms = v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *ObjectStoreTrustPolicy) GetContext() FixedReference {
	if o == nil || IsNil(o.Context) {
		var ret FixedReference
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectStoreTrustPolicy) GetContextOk() (*FixedReference, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *ObjectStoreTrustPolicy) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given FixedReference and assigns it to the Context field.
func (o *ObjectStoreTrustPolicy) SetContext(v FixedReference) {
	o.Context = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *ObjectStoreTrustPolicy) GetRole() FixedReference {
	if o == nil || IsNil(o.Role) {
		var ret FixedReference
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectStoreTrustPolicy) GetRoleOk() (*FixedReference, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *ObjectStoreTrustPolicy) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given FixedReference and assigns it to the Role field.
func (o *ObjectStoreTrustPolicy) SetRole(v FixedReference) {
	o.Role = &v
}

// GetRules returns the Rules field value if set, zero value otherwise.
func (o *ObjectStoreTrustPolicy) GetRules() []TrustPolicyRule {
	if o == nil || IsNil(o.Rules) {
		var ret []TrustPolicyRule
		return ret
	}
	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectStoreTrustPolicy) GetRulesOk() ([]TrustPolicyRule, bool) {
	if o == nil || IsNil(o.Rules) {
		return nil, false
	}
	return o.Rules, true
}

// HasRules returns a boolean if a field has been set.
func (o *ObjectStoreTrustPolicy) HasRules() bool {
	if o != nil && !IsNil(o.Rules) {
		return true
	}

	return false
}

// SetRules gets a reference to the given []TrustPolicyRule and assigns it to the Rules field.
func (o *ObjectStoreTrustPolicy) SetRules(v []TrustPolicyRule) {
	o.Rules = v
}

func (o ObjectStoreTrustPolicy) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObjectStoreTrustPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.IsLocal) {
		toSerialize["is_local"] = o.IsLocal
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.PolicyType) {
		toSerialize["policy_type"] = o.PolicyType
	}
	if !IsNil(o.Realms) {
		toSerialize["realms"] = o.Realms
	}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.Rules) {
		toSerialize["rules"] = o.Rules
	}
	return toSerialize, nil
}

type NullableObjectStoreTrustPolicy struct {
	value *ObjectStoreTrustPolicy
	isSet bool
}

func (v NullableObjectStoreTrustPolicy) Get() *ObjectStoreTrustPolicy {
	return v.value
}

func (v *NullableObjectStoreTrustPolicy) Set(val *ObjectStoreTrustPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectStoreTrustPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectStoreTrustPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectStoreTrustPolicy(val *ObjectStoreTrustPolicy) *NullableObjectStoreTrustPolicy {
	return &NullableObjectStoreTrustPolicy{value: val, isSet: true}
}

func (v NullableObjectStoreTrustPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectStoreTrustPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
