/*
FlashArray REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.57
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the CloudProviderTagResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudProviderTagResponse{}

// CloudProviderTagResponse struct for CloudProviderTagResponse
type CloudProviderTagResponse struct {
	Items []CloudProviderTag `json:"items,omitempty"`
}

// NewCloudProviderTagResponse instantiates a new CloudProviderTagResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudProviderTagResponse() *CloudProviderTagResponse {
	this := CloudProviderTagResponse{}
	return &this
}

// NewCloudProviderTagResponseWithDefaults instantiates a new CloudProviderTagResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudProviderTagResponseWithDefaults() *CloudProviderTagResponse {
	this := CloudProviderTagResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *CloudProviderTagResponse) GetItems() []CloudProviderTag {
	if o == nil || IsNil(o.Items) {
		var ret []CloudProviderTag
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudProviderTagResponse) GetItemsOk() ([]CloudProviderTag, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *CloudProviderTagResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []CloudProviderTag and assigns it to the Items field.
func (o *CloudProviderTagResponse) SetItems(v []CloudProviderTag) {
	o.Items = v
}

func (o CloudProviderTagResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudProviderTagResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableCloudProviderTagResponse struct {
	value *CloudProviderTagResponse
	isSet bool
}

func (v NullableCloudProviderTagResponse) Get() *CloudProviderTagResponse {
	return v.value
}

func (v *NullableCloudProviderTagResponse) Set(val *CloudProviderTagResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudProviderTagResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudProviderTagResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudProviderTagResponse(val *CloudProviderTagResponse) *NullableCloudProviderTagResponse {
	return &NullableCloudProviderTagResponse{value: val, isSet: true}
}

func (v NullableCloudProviderTagResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudProviderTagResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
