/*
FlashArray REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.57
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the PolicyQosPost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyQosPost{}

// PolicyQosPost struct for PolicyQosPost
type PolicyQosPost struct {
	// If set to `true`, enables the policy. If set to `false`, disables the policy.
	Enabled *bool `json:"enabled,omitempty"`
	// The maximum allowed `bytes/s` totaled across all the clients. Throttling occurs when the total bandwidth exceeds this limit. The minimum limit is `1 MB/s` and the maximum limit is `512 GB/s`. The limit can be unset by setting the value to `0` or `\"\"`. If not specified at creation time, this value defaults to `null` to indicate no limit.
	MaxTotalBytesPerSec *int64 `json:"max_total_bytes_per_sec,omitempty"`
	// The maximum allowed `operations/s` totaled across all the clients. Throttling occurs when the total `IOPS` exceeds this limit. The minimum limit is `100 IOPS/s` and the maximum limit is `100M IOPS/s`. The limit can be unset by setting the value to `0` or `\"\"`. If not specified at creation time, this value defaults to `null` to indicate no limit.
	MaxTotalOpsPerSec *int64 `json:"max_total_ops_per_sec,omitempty"`
}

// NewPolicyQosPost instantiates a new PolicyQosPost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyQosPost() *PolicyQosPost {
	this := PolicyQosPost{}
	return &this
}

// NewPolicyQosPostWithDefaults instantiates a new PolicyQosPost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyQosPostWithDefaults() *PolicyQosPost {
	this := PolicyQosPost{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *PolicyQosPost) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyQosPost) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *PolicyQosPost) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *PolicyQosPost) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetMaxTotalBytesPerSec returns the MaxTotalBytesPerSec field value if set, zero value otherwise.
func (o *PolicyQosPost) GetMaxTotalBytesPerSec() int64 {
	if o == nil || IsNil(o.MaxTotalBytesPerSec) {
		var ret int64
		return ret
	}
	return *o.MaxTotalBytesPerSec
}

// GetMaxTotalBytesPerSecOk returns a tuple with the MaxTotalBytesPerSec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyQosPost) GetMaxTotalBytesPerSecOk() (*int64, bool) {
	if o == nil || IsNil(o.MaxTotalBytesPerSec) {
		return nil, false
	}
	return o.MaxTotalBytesPerSec, true
}

// HasMaxTotalBytesPerSec returns a boolean if a field has been set.
func (o *PolicyQosPost) HasMaxTotalBytesPerSec() bool {
	if o != nil && !IsNil(o.MaxTotalBytesPerSec) {
		return true
	}

	return false
}

// SetMaxTotalBytesPerSec gets a reference to the given int64 and assigns it to the MaxTotalBytesPerSec field.
func (o *PolicyQosPost) SetMaxTotalBytesPerSec(v int64) {
	o.MaxTotalBytesPerSec = &v
}

// GetMaxTotalOpsPerSec returns the MaxTotalOpsPerSec field value if set, zero value otherwise.
func (o *PolicyQosPost) GetMaxTotalOpsPerSec() int64 {
	if o == nil || IsNil(o.MaxTotalOpsPerSec) {
		var ret int64
		return ret
	}
	return *o.MaxTotalOpsPerSec
}

// GetMaxTotalOpsPerSecOk returns a tuple with the MaxTotalOpsPerSec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyQosPost) GetMaxTotalOpsPerSecOk() (*int64, bool) {
	if o == nil || IsNil(o.MaxTotalOpsPerSec) {
		return nil, false
	}
	return o.MaxTotalOpsPerSec, true
}

// HasMaxTotalOpsPerSec returns a boolean if a field has been set.
func (o *PolicyQosPost) HasMaxTotalOpsPerSec() bool {
	if o != nil && !IsNil(o.MaxTotalOpsPerSec) {
		return true
	}

	return false
}

// SetMaxTotalOpsPerSec gets a reference to the given int64 and assigns it to the MaxTotalOpsPerSec field.
func (o *PolicyQosPost) SetMaxTotalOpsPerSec(v int64) {
	o.MaxTotalOpsPerSec = &v
}

func (o PolicyQosPost) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyQosPost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.MaxTotalBytesPerSec) {
		toSerialize["max_total_bytes_per_sec"] = o.MaxTotalBytesPerSec
	}
	if !IsNil(o.MaxTotalOpsPerSec) {
		toSerialize["max_total_ops_per_sec"] = o.MaxTotalOpsPerSec
	}
	return toSerialize, nil
}

type NullablePolicyQosPost struct {
	value *PolicyQosPost
	isSet bool
}

func (v NullablePolicyQosPost) Get() *PolicyQosPost {
	return v.value
}

func (v *NullablePolicyQosPost) Set(val *PolicyQosPost) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyQosPost) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyQosPost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyQosPost(val *PolicyQosPost) *NullablePolicyQosPost {
	return &NullablePolicyQosPost{value: val, isSet: true}
}

func (v NullablePolicyQosPost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyQosPost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
