/*
FlashArray REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.45
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the PolicyPost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyPost{}

// PolicyPost struct for PolicyPost
type PolicyPost struct {
	// If set to `true`, enables the policy. If set to `false`, disables the policy.
	Enabled *bool `json:"enabled,omitempty"`
}

// NewPolicyPost instantiates a new PolicyPost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyPost() *PolicyPost {
	this := PolicyPost{}
	return &this
}

// NewPolicyPostWithDefaults instantiates a new PolicyPost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyPostWithDefaults() *PolicyPost {
	this := PolicyPost{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *PolicyPost) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyPost) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *PolicyPost) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *PolicyPost) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o PolicyPost) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyPost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return toSerialize, nil
}

type NullablePolicyPost struct {
	value *PolicyPost
	isSet bool
}

func (v NullablePolicyPost) Get() *PolicyPost {
	return v.value
}

func (v *NullablePolicyPost) Set(val *PolicyPost) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyPost) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyPost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyPost(val *PolicyPost) *NullablePolicyPost {
	return &NullablePolicyPost{value: val, isSet: true}
}

func (v NullablePolicyPost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyPost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
