/*
FlashArray REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.45
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the NetworkInterfacePortDetailsTxPower type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkInterfacePortDetailsTxPower{}

// NetworkInterfacePortDetailsTxPower struct for NetworkInterfacePortDetailsTxPower
type NetworkInterfacePortDetailsTxPower struct {
	// The channel number if the transceiver is a multilane transceiver. If not specified, defaults to `null`.
	Channel *int32 `json:"channel,omitempty"`
	// Tx output power in mW.
	Measurement *float64 `json:"measurement,omitempty"`
	// Indicates whether the measurement is outside the high alarm, low alarm, high warning, or low warning thresholds for Tx output power. Valid values are `alarm low`, `alarm high`, `warn low`, `warn high`, and `ok`.
	Status *string `json:"status,omitempty"`
}

// NewNetworkInterfacePortDetailsTxPower instantiates a new NetworkInterfacePortDetailsTxPower object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkInterfacePortDetailsTxPower() *NetworkInterfacePortDetailsTxPower {
	this := NetworkInterfacePortDetailsTxPower{}
	return &this
}

// NewNetworkInterfacePortDetailsTxPowerWithDefaults instantiates a new NetworkInterfacePortDetailsTxPower object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkInterfacePortDetailsTxPowerWithDefaults() *NetworkInterfacePortDetailsTxPower {
	this := NetworkInterfacePortDetailsTxPower{}
	return &this
}

// GetChannel returns the Channel field value if set, zero value otherwise.
func (o *NetworkInterfacePortDetailsTxPower) GetChannel() int32 {
	if o == nil || IsNil(o.Channel) {
		var ret int32
		return ret
	}
	return *o.Channel
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkInterfacePortDetailsTxPower) GetChannelOk() (*int32, bool) {
	if o == nil || IsNil(o.Channel) {
		return nil, false
	}
	return o.Channel, true
}

// HasChannel returns a boolean if a field has been set.
func (o *NetworkInterfacePortDetailsTxPower) HasChannel() bool {
	if o != nil && !IsNil(o.Channel) {
		return true
	}

	return false
}

// SetChannel gets a reference to the given int32 and assigns it to the Channel field.
func (o *NetworkInterfacePortDetailsTxPower) SetChannel(v int32) {
	o.Channel = &v
}

// GetMeasurement returns the Measurement field value if set, zero value otherwise.
func (o *NetworkInterfacePortDetailsTxPower) GetMeasurement() float64 {
	if o == nil || IsNil(o.Measurement) {
		var ret float64
		return ret
	}
	return *o.Measurement
}

// GetMeasurementOk returns a tuple with the Measurement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkInterfacePortDetailsTxPower) GetMeasurementOk() (*float64, bool) {
	if o == nil || IsNil(o.Measurement) {
		return nil, false
	}
	return o.Measurement, true
}

// HasMeasurement returns a boolean if a field has been set.
func (o *NetworkInterfacePortDetailsTxPower) HasMeasurement() bool {
	if o != nil && !IsNil(o.Measurement) {
		return true
	}

	return false
}

// SetMeasurement gets a reference to the given float64 and assigns it to the Measurement field.
func (o *NetworkInterfacePortDetailsTxPower) SetMeasurement(v float64) {
	o.Measurement = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *NetworkInterfacePortDetailsTxPower) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkInterfacePortDetailsTxPower) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *NetworkInterfacePortDetailsTxPower) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *NetworkInterfacePortDetailsTxPower) SetStatus(v string) {
	o.Status = &v
}

func (o NetworkInterfacePortDetailsTxPower) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkInterfacePortDetailsTxPower) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Channel) {
		toSerialize["channel"] = o.Channel
	}
	if !IsNil(o.Measurement) {
		toSerialize["measurement"] = o.Measurement
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableNetworkInterfacePortDetailsTxPower struct {
	value *NetworkInterfacePortDetailsTxPower
	isSet bool
}

func (v NullableNetworkInterfacePortDetailsTxPower) Get() *NetworkInterfacePortDetailsTxPower {
	return v.value
}

func (v *NullableNetworkInterfacePortDetailsTxPower) Set(val *NetworkInterfacePortDetailsTxPower) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkInterfacePortDetailsTxPower) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkInterfacePortDetailsTxPower) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkInterfacePortDetailsTxPower(val *NetworkInterfacePortDetailsTxPower) *NullableNetworkInterfacePortDetailsTxPower {
	return &NullableNetworkInterfacePortDetailsTxPower{value: val, isSet: true}
}

func (v NullableNetworkInterfacePortDetailsTxPower) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkInterfacePortDetailsTxPower) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
