/*
FlashArray REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.45
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the PolicyAuditFileGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyAuditFileGetResponse{}

// PolicyAuditFileGetResponse struct for PolicyAuditFileGetResponse
type PolicyAuditFileGetResponse struct {
	// Continuation token that can be provided in the `continuation_token` query param to get the next page of data. If you use the continuation token to page through data you are guaranteed to get all items exactly once regardless of how items are modified. If an item is added or deleted during the pagination then it may or may not be returned. The continuation token is generated if the limit is less than the remaining number of items, and the default sort is used (no sort is specified).
	ContinuationToken *string `json:"continuation_token,omitempty"`
	// Returns a value of `true` if subsequent items can be retrieved.
	MoreItemsRemaining *bool `json:"more_items_remaining,omitempty"`
	// The total number of records after applying all filter query parameters. The `total_item_count` will be calculated if and only if the corresponding query parameter `total_item_count` is set to `true`. If this query parameter is not set or set to `false`, a value of `null` will be returned.
	TotalItemCount *int32 `json:"total_item_count,omitempty"`
	// Displays a list of all items after filtering. If applicable, the values are displayed for each name.
	Items []PolicyAuditFile `json:"items,omitempty"`
	// The list of errors encountered when attempting to perform an operation.
	Errors []ErrorcontextresponseErrors `json:"errors,omitempty"`
}

// NewPolicyAuditFileGetResponse instantiates a new PolicyAuditFileGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyAuditFileGetResponse() *PolicyAuditFileGetResponse {
	this := PolicyAuditFileGetResponse{}
	return &this
}

// NewPolicyAuditFileGetResponseWithDefaults instantiates a new PolicyAuditFileGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyAuditFileGetResponseWithDefaults() *PolicyAuditFileGetResponse {
	this := PolicyAuditFileGetResponse{}
	return &this
}

// GetContinuationToken returns the ContinuationToken field value if set, zero value otherwise.
func (o *PolicyAuditFileGetResponse) GetContinuationToken() string {
	if o == nil || IsNil(o.ContinuationToken) {
		var ret string
		return ret
	}
	return *o.ContinuationToken
}

// GetContinuationTokenOk returns a tuple with the ContinuationToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyAuditFileGetResponse) GetContinuationTokenOk() (*string, bool) {
	if o == nil || IsNil(o.ContinuationToken) {
		return nil, false
	}
	return o.ContinuationToken, true
}

// HasContinuationToken returns a boolean if a field has been set.
func (o *PolicyAuditFileGetResponse) HasContinuationToken() bool {
	if o != nil && !IsNil(o.ContinuationToken) {
		return true
	}

	return false
}

// SetContinuationToken gets a reference to the given string and assigns it to the ContinuationToken field.
func (o *PolicyAuditFileGetResponse) SetContinuationToken(v string) {
	o.ContinuationToken = &v
}

// GetMoreItemsRemaining returns the MoreItemsRemaining field value if set, zero value otherwise.
func (o *PolicyAuditFileGetResponse) GetMoreItemsRemaining() bool {
	if o == nil || IsNil(o.MoreItemsRemaining) {
		var ret bool
		return ret
	}
	return *o.MoreItemsRemaining
}

// GetMoreItemsRemainingOk returns a tuple with the MoreItemsRemaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyAuditFileGetResponse) GetMoreItemsRemainingOk() (*bool, bool) {
	if o == nil || IsNil(o.MoreItemsRemaining) {
		return nil, false
	}
	return o.MoreItemsRemaining, true
}

// HasMoreItemsRemaining returns a boolean if a field has been set.
func (o *PolicyAuditFileGetResponse) HasMoreItemsRemaining() bool {
	if o != nil && !IsNil(o.MoreItemsRemaining) {
		return true
	}

	return false
}

// SetMoreItemsRemaining gets a reference to the given bool and assigns it to the MoreItemsRemaining field.
func (o *PolicyAuditFileGetResponse) SetMoreItemsRemaining(v bool) {
	o.MoreItemsRemaining = &v
}

// GetTotalItemCount returns the TotalItemCount field value if set, zero value otherwise.
func (o *PolicyAuditFileGetResponse) GetTotalItemCount() int32 {
	if o == nil || IsNil(o.TotalItemCount) {
		var ret int32
		return ret
	}
	return *o.TotalItemCount
}

// GetTotalItemCountOk returns a tuple with the TotalItemCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyAuditFileGetResponse) GetTotalItemCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalItemCount) {
		return nil, false
	}
	return o.TotalItemCount, true
}

// HasTotalItemCount returns a boolean if a field has been set.
func (o *PolicyAuditFileGetResponse) HasTotalItemCount() bool {
	if o != nil && !IsNil(o.TotalItemCount) {
		return true
	}

	return false
}

// SetTotalItemCount gets a reference to the given int32 and assigns it to the TotalItemCount field.
func (o *PolicyAuditFileGetResponse) SetTotalItemCount(v int32) {
	o.TotalItemCount = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *PolicyAuditFileGetResponse) GetItems() []PolicyAuditFile {
	if o == nil || IsNil(o.Items) {
		var ret []PolicyAuditFile
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyAuditFileGetResponse) GetItemsOk() ([]PolicyAuditFile, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *PolicyAuditFileGetResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []PolicyAuditFile and assigns it to the Items field.
func (o *PolicyAuditFileGetResponse) SetItems(v []PolicyAuditFile) {
	o.Items = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *PolicyAuditFileGetResponse) GetErrors() []ErrorcontextresponseErrors {
	if o == nil || IsNil(o.Errors) {
		var ret []ErrorcontextresponseErrors
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyAuditFileGetResponse) GetErrorsOk() ([]ErrorcontextresponseErrors, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *PolicyAuditFileGetResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []ErrorcontextresponseErrors and assigns it to the Errors field.
func (o *PolicyAuditFileGetResponse) SetErrors(v []ErrorcontextresponseErrors) {
	o.Errors = v
}

func (o PolicyAuditFileGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyAuditFileGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContinuationToken) {
		toSerialize["continuation_token"] = o.ContinuationToken
	}
	if !IsNil(o.MoreItemsRemaining) {
		toSerialize["more_items_remaining"] = o.MoreItemsRemaining
	}
	if !IsNil(o.TotalItemCount) {
		toSerialize["total_item_count"] = o.TotalItemCount
	}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullablePolicyAuditFileGetResponse struct {
	value *PolicyAuditFileGetResponse
	isSet bool
}

func (v NullablePolicyAuditFileGetResponse) Get() *PolicyAuditFileGetResponse {
	return v.value
}

func (v *NullablePolicyAuditFileGetResponse) Set(val *PolicyAuditFileGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyAuditFileGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyAuditFileGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyAuditFileGetResponse(val *PolicyAuditFileGetResponse) *NullablePolicyAuditFileGetResponse {
	return &NullablePolicyAuditFileGetResponse{value: val, isSet: true}
}

func (v NullablePolicyAuditFileGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyAuditFileGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
