/*
FlashArray REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.48
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the PolicyrulemanagementaccessRules type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyrulemanagementaccessRules{}

// PolicyrulemanagementaccessRules struct for PolicyrulemanagementaccessRules
type PolicyrulemanagementaccessRules struct {
	// Role defines a set of permissions applicable in a scope. `viewer` grants users the ability to read a resource. `support` grants the ability to perform general support-related actions, as well as read resources. `storage` grants access to all storage operations on a resource. `admin` grants access to all operations.
	Role *ReferenceNoId `json:"role,omitempty"`
	// Reference to the resource (e.g. arrays, realms) which specifies the scope that the role applies. The `id` or `name` parameter is required, but they cannot be set together. Also, `resource_type` must be set.
	Scope *ReferenceWithType `json:"scope,omitempty"`
}

// NewPolicyrulemanagementaccessRules instantiates a new PolicyrulemanagementaccessRules object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyrulemanagementaccessRules() *PolicyrulemanagementaccessRules {
	this := PolicyrulemanagementaccessRules{}
	return &this
}

// NewPolicyrulemanagementaccessRulesWithDefaults instantiates a new PolicyrulemanagementaccessRules object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyrulemanagementaccessRulesWithDefaults() *PolicyrulemanagementaccessRules {
	this := PolicyrulemanagementaccessRules{}
	return &this
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *PolicyrulemanagementaccessRules) GetRole() ReferenceNoId {
	if o == nil || IsNil(o.Role) {
		var ret ReferenceNoId
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyrulemanagementaccessRules) GetRoleOk() (*ReferenceNoId, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *PolicyrulemanagementaccessRules) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given ReferenceNoId and assigns it to the Role field.
func (o *PolicyrulemanagementaccessRules) SetRole(v ReferenceNoId) {
	o.Role = &v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *PolicyrulemanagementaccessRules) GetScope() ReferenceWithType {
	if o == nil || IsNil(o.Scope) {
		var ret ReferenceWithType
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyrulemanagementaccessRules) GetScopeOk() (*ReferenceWithType, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *PolicyrulemanagementaccessRules) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given ReferenceWithType and assigns it to the Scope field.
func (o *PolicyrulemanagementaccessRules) SetScope(v ReferenceWithType) {
	o.Scope = &v
}

func (o PolicyrulemanagementaccessRules) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyrulemanagementaccessRules) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	return toSerialize, nil
}

type NullablePolicyrulemanagementaccessRules struct {
	value *PolicyrulemanagementaccessRules
	isSet bool
}

func (v NullablePolicyrulemanagementaccessRules) Get() *PolicyrulemanagementaccessRules {
	return v.value
}

func (v *NullablePolicyrulemanagementaccessRules) Set(val *PolicyrulemanagementaccessRules) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyrulemanagementaccessRules) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyrulemanagementaccessRules) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyrulemanagementaccessRules(val *PolicyrulemanagementaccessRules) *NullablePolicyrulemanagementaccessRules {
	return &NullablePolicyrulemanagementaccessRules{value: val, isSet: true}
}

func (v NullablePolicyrulemanagementaccessRules) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyrulemanagementaccessRules) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
