/*
FlashArray REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.56
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the PodRemoteArrayStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PodRemoteArrayStatus{}

// PodRemoteArrayStatus struct for PodRemoteArrayStatus
type PodRemoteArrayStatus struct {
	// A globally unique, system-generated ID. The ID cannot be modified.
	Id *string `json:"id,omitempty"`
	// The resource name, such as volume name, pod name, snapshot name, and so on.
	Name *string `json:"name,omitempty"`
	// Type of the object (full name of the endpoint). Valid values are `hosts`, `host-groups`, `network-interfaces`, `pods`, `ports`, `pod-replica-links`, `subnets`, `volumes`, `volume-snapshots`, `volume-groups`, `directories`, `policies/nfs`, `policies/smb`, `policies/snapshot`, etc.
	ResourceType *string `json:"resource_type,omitempty"`
	// Specifies the reference to the member associated with the pod's array status.
	Member *ReferenceWithType `json:"member,omitempty"`
}

// NewPodRemoteArrayStatus instantiates a new PodRemoteArrayStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPodRemoteArrayStatus() *PodRemoteArrayStatus {
	this := PodRemoteArrayStatus{}
	return &this
}

// NewPodRemoteArrayStatusWithDefaults instantiates a new PodRemoteArrayStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPodRemoteArrayStatusWithDefaults() *PodRemoteArrayStatus {
	this := PodRemoteArrayStatus{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PodRemoteArrayStatus) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PodRemoteArrayStatus) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PodRemoteArrayStatus) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PodRemoteArrayStatus) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PodRemoteArrayStatus) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PodRemoteArrayStatus) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PodRemoteArrayStatus) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PodRemoteArrayStatus) SetName(v string) {
	o.Name = &v
}

// GetResourceType returns the ResourceType field value if set, zero value otherwise.
func (o *PodRemoteArrayStatus) GetResourceType() string {
	if o == nil || IsNil(o.ResourceType) {
		var ret string
		return ret
	}
	return *o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PodRemoteArrayStatus) GetResourceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceType) {
		return nil, false
	}
	return o.ResourceType, true
}

// HasResourceType returns a boolean if a field has been set.
func (o *PodRemoteArrayStatus) HasResourceType() bool {
	if o != nil && !IsNil(o.ResourceType) {
		return true
	}

	return false
}

// SetResourceType gets a reference to the given string and assigns it to the ResourceType field.
func (o *PodRemoteArrayStatus) SetResourceType(v string) {
	o.ResourceType = &v
}

// GetMember returns the Member field value if set, zero value otherwise.
func (o *PodRemoteArrayStatus) GetMember() ReferenceWithType {
	if o == nil || IsNil(o.Member) {
		var ret ReferenceWithType
		return ret
	}
	return *o.Member
}

// GetMemberOk returns a tuple with the Member field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PodRemoteArrayStatus) GetMemberOk() (*ReferenceWithType, bool) {
	if o == nil || IsNil(o.Member) {
		return nil, false
	}
	return o.Member, true
}

// HasMember returns a boolean if a field has been set.
func (o *PodRemoteArrayStatus) HasMember() bool {
	if o != nil && !IsNil(o.Member) {
		return true
	}

	return false
}

// SetMember gets a reference to the given ReferenceWithType and assigns it to the Member field.
func (o *PodRemoteArrayStatus) SetMember(v ReferenceWithType) {
	o.Member = &v
}

func (o PodRemoteArrayStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PodRemoteArrayStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ResourceType) {
		toSerialize["resource_type"] = o.ResourceType
	}
	if !IsNil(o.Member) {
		toSerialize["member"] = o.Member
	}
	return toSerialize, nil
}

type NullablePodRemoteArrayStatus struct {
	value *PodRemoteArrayStatus
	isSet bool
}

func (v NullablePodRemoteArrayStatus) Get() *PodRemoteArrayStatus {
	return v.value
}

func (v *NullablePodRemoteArrayStatus) Set(val *PodRemoteArrayStatus) {
	v.value = val
	v.isSet = true
}

func (v NullablePodRemoteArrayStatus) IsSet() bool {
	return v.isSet
}

func (v *NullablePodRemoteArrayStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePodRemoteArrayStatus(val *PodRemoteArrayStatus) *NullablePodRemoteArrayStatus {
	return &NullablePodRemoteArrayStatus{value: val, isSet: true}
}

func (v NullablePodRemoteArrayStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePodRemoteArrayStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
