/*
FlashBlade REST API

OpenAPI specification for FlashBlade REST API, developed by Everpure, Inc. (https://www.everpuredata.com/).

API version: 2.17
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the GroupQuotaResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupQuotaResponse{}

// GroupQuotaResponse struct for GroupQuotaResponse
type GroupQuotaResponse struct {
	// A list of quota objects.
	Items []GroupQuota `json:"items,omitempty"`
}

// NewGroupQuotaResponse instantiates a new GroupQuotaResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupQuotaResponse() *GroupQuotaResponse {
	this := GroupQuotaResponse{}
	return &this
}

// NewGroupQuotaResponseWithDefaults instantiates a new GroupQuotaResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupQuotaResponseWithDefaults() *GroupQuotaResponse {
	this := GroupQuotaResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *GroupQuotaResponse) GetItems() []GroupQuota {
	if o == nil || IsNil(o.Items) {
		var ret []GroupQuota
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupQuotaResponse) GetItemsOk() ([]GroupQuota, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *GroupQuotaResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []GroupQuota and assigns it to the Items field.
func (o *GroupQuotaResponse) SetItems(v []GroupQuota) {
	o.Items = v
}

func (o GroupQuotaResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupQuotaResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableGroupQuotaResponse struct {
	value *GroupQuotaResponse
	isSet bool
}

func (v NullableGroupQuotaResponse) Get() *GroupQuotaResponse {
	return v.value
}

func (v *NullableGroupQuotaResponse) Set(val *GroupQuotaResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupQuotaResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupQuotaResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupQuotaResponse(val *GroupQuotaResponse) *NullableGroupQuotaResponse {
	return &NullableGroupQuotaResponse{value: val, isSet: true}
}

func (v NullableGroupQuotaResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupQuotaResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
