/*
FlashBlade REST API

OpenAPI specification for FlashBlade REST API, developed by Everpure, Inc. (https://www.everpuredata.com/).

API version: 2.17
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the LifecycleRuleConfigExtension type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LifecycleRuleConfigExtension{}

// LifecycleRuleConfigExtension struct for LifecycleRuleConfigExtension
type LifecycleRuleConfigExtension struct {
	// Duration of time after which incomplete multipart uploads will be aborted. Measured in milliseconds. Must be a multiple of 86400000 to represent a whole number of days.
	AbortIncompleteMultipartUploadsAfter *int64 `json:"abort_incomplete_multipart_uploads_after,omitempty"`
	// Time after which current versions will be marked expired. Measured in milliseconds. Must be a multiple of 86400000 to represent a whole number of days.
	KeepCurrentVersionFor *int64 `json:"keep_current_version_for,omitempty"`
	// Time after which current versions will be marked expired. Measured in milliseconds, time since epoch. Must be a valid date, accurate to day.
	KeepCurrentVersionUntil *int64 `json:"keep_current_version_until,omitempty"`
}

// NewLifecycleRuleConfigExtension instantiates a new LifecycleRuleConfigExtension object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLifecycleRuleConfigExtension() *LifecycleRuleConfigExtension {
	this := LifecycleRuleConfigExtension{}
	return &this
}

// NewLifecycleRuleConfigExtensionWithDefaults instantiates a new LifecycleRuleConfigExtension object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLifecycleRuleConfigExtensionWithDefaults() *LifecycleRuleConfigExtension {
	this := LifecycleRuleConfigExtension{}
	return &this
}

// GetAbortIncompleteMultipartUploadsAfter returns the AbortIncompleteMultipartUploadsAfter field value if set, zero value otherwise.
func (o *LifecycleRuleConfigExtension) GetAbortIncompleteMultipartUploadsAfter() int64 {
	if o == nil || IsNil(o.AbortIncompleteMultipartUploadsAfter) {
		var ret int64
		return ret
	}
	return *o.AbortIncompleteMultipartUploadsAfter
}

// GetAbortIncompleteMultipartUploadsAfterOk returns a tuple with the AbortIncompleteMultipartUploadsAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LifecycleRuleConfigExtension) GetAbortIncompleteMultipartUploadsAfterOk() (*int64, bool) {
	if o == nil || IsNil(o.AbortIncompleteMultipartUploadsAfter) {
		return nil, false
	}
	return o.AbortIncompleteMultipartUploadsAfter, true
}

// HasAbortIncompleteMultipartUploadsAfter returns a boolean if a field has been set.
func (o *LifecycleRuleConfigExtension) HasAbortIncompleteMultipartUploadsAfter() bool {
	if o != nil && !IsNil(o.AbortIncompleteMultipartUploadsAfter) {
		return true
	}

	return false
}

// SetAbortIncompleteMultipartUploadsAfter gets a reference to the given int64 and assigns it to the AbortIncompleteMultipartUploadsAfter field.
func (o *LifecycleRuleConfigExtension) SetAbortIncompleteMultipartUploadsAfter(v int64) {
	o.AbortIncompleteMultipartUploadsAfter = &v
}

// GetKeepCurrentVersionFor returns the KeepCurrentVersionFor field value if set, zero value otherwise.
func (o *LifecycleRuleConfigExtension) GetKeepCurrentVersionFor() int64 {
	if o == nil || IsNil(o.KeepCurrentVersionFor) {
		var ret int64
		return ret
	}
	return *o.KeepCurrentVersionFor
}

// GetKeepCurrentVersionForOk returns a tuple with the KeepCurrentVersionFor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LifecycleRuleConfigExtension) GetKeepCurrentVersionForOk() (*int64, bool) {
	if o == nil || IsNil(o.KeepCurrentVersionFor) {
		return nil, false
	}
	return o.KeepCurrentVersionFor, true
}

// HasKeepCurrentVersionFor returns a boolean if a field has been set.
func (o *LifecycleRuleConfigExtension) HasKeepCurrentVersionFor() bool {
	if o != nil && !IsNil(o.KeepCurrentVersionFor) {
		return true
	}

	return false
}

// SetKeepCurrentVersionFor gets a reference to the given int64 and assigns it to the KeepCurrentVersionFor field.
func (o *LifecycleRuleConfigExtension) SetKeepCurrentVersionFor(v int64) {
	o.KeepCurrentVersionFor = &v
}

// GetKeepCurrentVersionUntil returns the KeepCurrentVersionUntil field value if set, zero value otherwise.
func (o *LifecycleRuleConfigExtension) GetKeepCurrentVersionUntil() int64 {
	if o == nil || IsNil(o.KeepCurrentVersionUntil) {
		var ret int64
		return ret
	}
	return *o.KeepCurrentVersionUntil
}

// GetKeepCurrentVersionUntilOk returns a tuple with the KeepCurrentVersionUntil field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LifecycleRuleConfigExtension) GetKeepCurrentVersionUntilOk() (*int64, bool) {
	if o == nil || IsNil(o.KeepCurrentVersionUntil) {
		return nil, false
	}
	return o.KeepCurrentVersionUntil, true
}

// HasKeepCurrentVersionUntil returns a boolean if a field has been set.
func (o *LifecycleRuleConfigExtension) HasKeepCurrentVersionUntil() bool {
	if o != nil && !IsNil(o.KeepCurrentVersionUntil) {
		return true
	}

	return false
}

// SetKeepCurrentVersionUntil gets a reference to the given int64 and assigns it to the KeepCurrentVersionUntil field.
func (o *LifecycleRuleConfigExtension) SetKeepCurrentVersionUntil(v int64) {
	o.KeepCurrentVersionUntil = &v
}

func (o LifecycleRuleConfigExtension) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LifecycleRuleConfigExtension) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AbortIncompleteMultipartUploadsAfter) {
		toSerialize["abort_incomplete_multipart_uploads_after"] = o.AbortIncompleteMultipartUploadsAfter
	}
	if !IsNil(o.KeepCurrentVersionFor) {
		toSerialize["keep_current_version_for"] = o.KeepCurrentVersionFor
	}
	if !IsNil(o.KeepCurrentVersionUntil) {
		toSerialize["keep_current_version_until"] = o.KeepCurrentVersionUntil
	}
	return toSerialize, nil
}

type NullableLifecycleRuleConfigExtension struct {
	value *LifecycleRuleConfigExtension
	isSet bool
}

func (v NullableLifecycleRuleConfigExtension) Get() *LifecycleRuleConfigExtension {
	return v.value
}

func (v *NullableLifecycleRuleConfigExtension) Set(val *LifecycleRuleConfigExtension) {
	v.value = val
	v.isSet = true
}

func (v NullableLifecycleRuleConfigExtension) IsSet() bool {
	return v.isSet
}

func (v *NullableLifecycleRuleConfigExtension) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLifecycleRuleConfigExtension(val *LifecycleRuleConfigExtension) *NullableLifecycleRuleConfigExtension {
	return &NullableLifecycleRuleConfigExtension{value: val, isSet: true}
}

func (v NullableLifecycleRuleConfigExtension) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLifecycleRuleConfigExtension) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
