/*
FlashBlade REST API

OpenAPI specification for FlashBlade REST API, developed by Everpure, Inc. (https://www.everpuredata.com/).

API version: 2.27
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the PresetWorkloadExportConfigurationNfsPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PresetWorkloadExportConfigurationNfsPolicy{}

// PresetWorkloadExportConfigurationNfsPolicy struct for PresetWorkloadExportConfigurationNfsPolicy
type PresetWorkloadExportConfigurationNfsPolicy struct {
	Rules []PresetWorkloadExportConfigurationNfsRule `json:"rules,omitempty"`
	// If \"true\", queries the joined AD/OpenLDAP server to find the user corresponding to the incoming UID. If \"false\", users are defined by UID/GID pair. Supports parameterization.
	UserMappingEnabled *string `json:"user_mapping_enabled,omitempty"`
}

// NewPresetWorkloadExportConfigurationNfsPolicy instantiates a new PresetWorkloadExportConfigurationNfsPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPresetWorkloadExportConfigurationNfsPolicy() *PresetWorkloadExportConfigurationNfsPolicy {
	this := PresetWorkloadExportConfigurationNfsPolicy{}
	return &this
}

// NewPresetWorkloadExportConfigurationNfsPolicyWithDefaults instantiates a new PresetWorkloadExportConfigurationNfsPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPresetWorkloadExportConfigurationNfsPolicyWithDefaults() *PresetWorkloadExportConfigurationNfsPolicy {
	this := PresetWorkloadExportConfigurationNfsPolicy{}
	return &this
}

// GetRules returns the Rules field value if set, zero value otherwise.
func (o *PresetWorkloadExportConfigurationNfsPolicy) GetRules() []PresetWorkloadExportConfigurationNfsRule {
	if o == nil || IsNil(o.Rules) {
		var ret []PresetWorkloadExportConfigurationNfsRule
		return ret
	}
	return o.Rules
}

// GetRulesOk returns a tuple with the Rules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PresetWorkloadExportConfigurationNfsPolicy) GetRulesOk() ([]PresetWorkloadExportConfigurationNfsRule, bool) {
	if o == nil || IsNil(o.Rules) {
		return nil, false
	}
	return o.Rules, true
}

// HasRules returns a boolean if a field has been set.
func (o *PresetWorkloadExportConfigurationNfsPolicy) HasRules() bool {
	if o != nil && !IsNil(o.Rules) {
		return true
	}

	return false
}

// SetRules gets a reference to the given []PresetWorkloadExportConfigurationNfsRule and assigns it to the Rules field.
func (o *PresetWorkloadExportConfigurationNfsPolicy) SetRules(v []PresetWorkloadExportConfigurationNfsRule) {
	o.Rules = v
}

// GetUserMappingEnabled returns the UserMappingEnabled field value if set, zero value otherwise.
func (o *PresetWorkloadExportConfigurationNfsPolicy) GetUserMappingEnabled() string {
	if o == nil || IsNil(o.UserMappingEnabled) {
		var ret string
		return ret
	}
	return *o.UserMappingEnabled
}

// GetUserMappingEnabledOk returns a tuple with the UserMappingEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PresetWorkloadExportConfigurationNfsPolicy) GetUserMappingEnabledOk() (*string, bool) {
	if o == nil || IsNil(o.UserMappingEnabled) {
		return nil, false
	}
	return o.UserMappingEnabled, true
}

// HasUserMappingEnabled returns a boolean if a field has been set.
func (o *PresetWorkloadExportConfigurationNfsPolicy) HasUserMappingEnabled() bool {
	if o != nil && !IsNil(o.UserMappingEnabled) {
		return true
	}

	return false
}

// SetUserMappingEnabled gets a reference to the given string and assigns it to the UserMappingEnabled field.
func (o *PresetWorkloadExportConfigurationNfsPolicy) SetUserMappingEnabled(v string) {
	o.UserMappingEnabled = &v
}

func (o PresetWorkloadExportConfigurationNfsPolicy) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PresetWorkloadExportConfigurationNfsPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Rules) {
		toSerialize["rules"] = o.Rules
	}
	if !IsNil(o.UserMappingEnabled) {
		toSerialize["user_mapping_enabled"] = o.UserMappingEnabled
	}
	return toSerialize, nil
}

type NullablePresetWorkloadExportConfigurationNfsPolicy struct {
	value *PresetWorkloadExportConfigurationNfsPolicy
	isSet bool
}

func (v NullablePresetWorkloadExportConfigurationNfsPolicy) Get() *PresetWorkloadExportConfigurationNfsPolicy {
	return v.value
}

func (v *NullablePresetWorkloadExportConfigurationNfsPolicy) Set(val *PresetWorkloadExportConfigurationNfsPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullablePresetWorkloadExportConfigurationNfsPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullablePresetWorkloadExportConfigurationNfsPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePresetWorkloadExportConfigurationNfsPolicy(val *PresetWorkloadExportConfigurationNfsPolicy) *NullablePresetWorkloadExportConfigurationNfsPolicy {
	return &NullablePresetWorkloadExportConfigurationNfsPolicy{value: val, isSet: true}
}

func (v NullablePresetWorkloadExportConfigurationNfsPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePresetWorkloadExportConfigurationNfsPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
