/*
FlashBlade REST API

OpenAPI specification for FlashBlade REST API, developed by Pure Storage, Inc. (https://www.purestorage.com/).

API version: 2.27
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the ManagementAccessPolicyRolesGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagementAccessPolicyRolesGetResponse{}

// ManagementAccessPolicyRolesGetResponse struct for ManagementAccessPolicyRolesGetResponse
type ManagementAccessPolicyRolesGetResponse struct {
	// Continuation token that can be provided in the `continuation_token` query param to get the next page of data. If you use the `continuation_token` to page through data you are guaranteed to get all items exactly once regardless of how items are modified. If an item is added or deleted during the pagination then it may or may not be returned. The `continuation_token` is generated if the `limit` is less than the remaining number of items, and the default sort is used (no sort is specified).
	ContinuationToken *string `json:"continuation_token,omitempty"`
	// Total number of items after applying `filter` params.
	TotalItemCount *int32 `json:"total_item_count,omitempty"`
	// Displays a list of all items after filtering. If applicable, the values are displayed for each name.
	Items []ManagementAccessPolicyRole `json:"items,omitempty"`
	// The list of errors encountered when attempting to perform an operation.
	Errors []ErrorContextResponseErrors `json:"errors,omitempty"`
}

// NewManagementAccessPolicyRolesGetResponse instantiates a new ManagementAccessPolicyRolesGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagementAccessPolicyRolesGetResponse() *ManagementAccessPolicyRolesGetResponse {
	this := ManagementAccessPolicyRolesGetResponse{}
	return &this
}

// NewManagementAccessPolicyRolesGetResponseWithDefaults instantiates a new ManagementAccessPolicyRolesGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagementAccessPolicyRolesGetResponseWithDefaults() *ManagementAccessPolicyRolesGetResponse {
	this := ManagementAccessPolicyRolesGetResponse{}
	return &this
}

// GetContinuationToken returns the ContinuationToken field value if set, zero value otherwise.
func (o *ManagementAccessPolicyRolesGetResponse) GetContinuationToken() string {
	if o == nil || IsNil(o.ContinuationToken) {
		var ret string
		return ret
	}
	return *o.ContinuationToken
}

// GetContinuationTokenOk returns a tuple with the ContinuationToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementAccessPolicyRolesGetResponse) GetContinuationTokenOk() (*string, bool) {
	if o == nil || IsNil(o.ContinuationToken) {
		return nil, false
	}
	return o.ContinuationToken, true
}

// HasContinuationToken returns a boolean if a field has been set.
func (o *ManagementAccessPolicyRolesGetResponse) HasContinuationToken() bool {
	if o != nil && !IsNil(o.ContinuationToken) {
		return true
	}

	return false
}

// SetContinuationToken gets a reference to the given string and assigns it to the ContinuationToken field.
func (o *ManagementAccessPolicyRolesGetResponse) SetContinuationToken(v string) {
	o.ContinuationToken = &v
}

// GetTotalItemCount returns the TotalItemCount field value if set, zero value otherwise.
func (o *ManagementAccessPolicyRolesGetResponse) GetTotalItemCount() int32 {
	if o == nil || IsNil(o.TotalItemCount) {
		var ret int32
		return ret
	}
	return *o.TotalItemCount
}

// GetTotalItemCountOk returns a tuple with the TotalItemCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementAccessPolicyRolesGetResponse) GetTotalItemCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalItemCount) {
		return nil, false
	}
	return o.TotalItemCount, true
}

// HasTotalItemCount returns a boolean if a field has been set.
func (o *ManagementAccessPolicyRolesGetResponse) HasTotalItemCount() bool {
	if o != nil && !IsNil(o.TotalItemCount) {
		return true
	}

	return false
}

// SetTotalItemCount gets a reference to the given int32 and assigns it to the TotalItemCount field.
func (o *ManagementAccessPolicyRolesGetResponse) SetTotalItemCount(v int32) {
	o.TotalItemCount = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ManagementAccessPolicyRolesGetResponse) GetItems() []ManagementAccessPolicyRole {
	if o == nil || IsNil(o.Items) {
		var ret []ManagementAccessPolicyRole
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementAccessPolicyRolesGetResponse) GetItemsOk() ([]ManagementAccessPolicyRole, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ManagementAccessPolicyRolesGetResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []ManagementAccessPolicyRole and assigns it to the Items field.
func (o *ManagementAccessPolicyRolesGetResponse) SetItems(v []ManagementAccessPolicyRole) {
	o.Items = v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *ManagementAccessPolicyRolesGetResponse) GetErrors() []ErrorContextResponseErrors {
	if o == nil || IsNil(o.Errors) {
		var ret []ErrorContextResponseErrors
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagementAccessPolicyRolesGetResponse) GetErrorsOk() ([]ErrorContextResponseErrors, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ManagementAccessPolicyRolesGetResponse) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []ErrorContextResponseErrors and assigns it to the Errors field.
func (o *ManagementAccessPolicyRolesGetResponse) SetErrors(v []ErrorContextResponseErrors) {
	o.Errors = v
}

func (o ManagementAccessPolicyRolesGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagementAccessPolicyRolesGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContinuationToken) {
		toSerialize["continuation_token"] = o.ContinuationToken
	}
	if !IsNil(o.TotalItemCount) {
		toSerialize["total_item_count"] = o.TotalItemCount
	}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableManagementAccessPolicyRolesGetResponse struct {
	value *ManagementAccessPolicyRolesGetResponse
	isSet bool
}

func (v NullableManagementAccessPolicyRolesGetResponse) Get() *ManagementAccessPolicyRolesGetResponse {
	return v.value
}

func (v *NullableManagementAccessPolicyRolesGetResponse) Set(val *ManagementAccessPolicyRolesGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableManagementAccessPolicyRolesGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableManagementAccessPolicyRolesGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagementAccessPolicyRolesGetResponse(val *ManagementAccessPolicyRolesGetResponse) *NullableManagementAccessPolicyRolesGetResponse {
	return &NullableManagementAccessPolicyRolesGetResponse{value: val, isSet: true}
}

func (v NullableManagementAccessPolicyRolesGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagementAccessPolicyRolesGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
