/*
FlashBlade REST API

OpenAPI specification for FlashBlade REST API, developed by Everpure, Inc. (https://www.everpuredata.com/).

API version: 2.28
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the FileSystemStorageClassSpace type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileSystemStorageClassSpace{}

// FileSystemStorageClassSpace struct for FileSystemStorageClassSpace
type FileSystemStorageClassSpace struct {
	// A non-modifiable, globally unique ID chosen by the system.
	Id *string `json:"id,omitempty"`
	// Name of the object (e.g., a file system or snapshot).
	Name  *string `json:"name,omitempty"`
	Space *Space  `json:"space,omitempty"`
	// The storage class type of the space information, either `S500X-S` (speed) or `S500X-A` (archival).
	StorageClass *string `json:"storage_class,omitempty"`
	// Sample time in milliseconds since UNIX epoch.
	Time *int64 `json:"time,omitempty"`
}

// NewFileSystemStorageClassSpace instantiates a new FileSystemStorageClassSpace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileSystemStorageClassSpace() *FileSystemStorageClassSpace {
	this := FileSystemStorageClassSpace{}
	return &this
}

// NewFileSystemStorageClassSpaceWithDefaults instantiates a new FileSystemStorageClassSpace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileSystemStorageClassSpaceWithDefaults() *FileSystemStorageClassSpace {
	this := FileSystemStorageClassSpace{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FileSystemStorageClassSpace) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSystemStorageClassSpace) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FileSystemStorageClassSpace) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *FileSystemStorageClassSpace) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FileSystemStorageClassSpace) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSystemStorageClassSpace) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FileSystemStorageClassSpace) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FileSystemStorageClassSpace) SetName(v string) {
	o.Name = &v
}

// GetSpace returns the Space field value if set, zero value otherwise.
func (o *FileSystemStorageClassSpace) GetSpace() Space {
	if o == nil || IsNil(o.Space) {
		var ret Space
		return ret
	}
	return *o.Space
}

// GetSpaceOk returns a tuple with the Space field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSystemStorageClassSpace) GetSpaceOk() (*Space, bool) {
	if o == nil || IsNil(o.Space) {
		return nil, false
	}
	return o.Space, true
}

// HasSpace returns a boolean if a field has been set.
func (o *FileSystemStorageClassSpace) HasSpace() bool {
	if o != nil && !IsNil(o.Space) {
		return true
	}

	return false
}

// SetSpace gets a reference to the given Space and assigns it to the Space field.
func (o *FileSystemStorageClassSpace) SetSpace(v Space) {
	o.Space = &v
}

// GetStorageClass returns the StorageClass field value if set, zero value otherwise.
func (o *FileSystemStorageClassSpace) GetStorageClass() string {
	if o == nil || IsNil(o.StorageClass) {
		var ret string
		return ret
	}
	return *o.StorageClass
}

// GetStorageClassOk returns a tuple with the StorageClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSystemStorageClassSpace) GetStorageClassOk() (*string, bool) {
	if o == nil || IsNil(o.StorageClass) {
		return nil, false
	}
	return o.StorageClass, true
}

// HasStorageClass returns a boolean if a field has been set.
func (o *FileSystemStorageClassSpace) HasStorageClass() bool {
	if o != nil && !IsNil(o.StorageClass) {
		return true
	}

	return false
}

// SetStorageClass gets a reference to the given string and assigns it to the StorageClass field.
func (o *FileSystemStorageClassSpace) SetStorageClass(v string) {
	o.StorageClass = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *FileSystemStorageClassSpace) GetTime() int64 {
	if o == nil || IsNil(o.Time) {
		var ret int64
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileSystemStorageClassSpace) GetTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *FileSystemStorageClassSpace) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given int64 and assigns it to the Time field.
func (o *FileSystemStorageClassSpace) SetTime(v int64) {
	o.Time = &v
}

func (o FileSystemStorageClassSpace) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileSystemStorageClassSpace) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Space) {
		toSerialize["space"] = o.Space
	}
	if !IsNil(o.StorageClass) {
		toSerialize["storage_class"] = o.StorageClass
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	return toSerialize, nil
}

type NullableFileSystemStorageClassSpace struct {
	value *FileSystemStorageClassSpace
	isSet bool
}

func (v NullableFileSystemStorageClassSpace) Get() *FileSystemStorageClassSpace {
	return v.value
}

func (v *NullableFileSystemStorageClassSpace) Set(val *FileSystemStorageClassSpace) {
	v.value = val
	v.isSet = true
}

func (v NullableFileSystemStorageClassSpace) IsSet() bool {
	return v.isSet
}

func (v *NullableFileSystemStorageClassSpace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileSystemStorageClassSpace(val *FileSystemStorageClassSpace) *NullableFileSystemStorageClassSpace {
	return &NullableFileSystemStorageClassSpace{value: val, isSet: true}
}

func (v NullableFileSystemStorageClassSpace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileSystemStorageClassSpace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
