/*
FlashArray REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.55
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the RealmMemberResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RealmMemberResponse{}

// RealmMemberResponse struct for RealmMemberResponse
type RealmMemberResponse struct {
	// The list of all `items` displayed after `filtering`. The `values` are displayed for each `name` where meaningful. If the `total_only` parameter is set to `true`, the `items` list will be empty.
	Items []RealmMember `json:"items,omitempty"`
}

// NewRealmMemberResponse instantiates a new RealmMemberResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRealmMemberResponse() *RealmMemberResponse {
	this := RealmMemberResponse{}
	return &this
}

// NewRealmMemberResponseWithDefaults instantiates a new RealmMemberResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRealmMemberResponseWithDefaults() *RealmMemberResponse {
	this := RealmMemberResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *RealmMemberResponse) GetItems() []RealmMember {
	if o == nil || IsNil(o.Items) {
		var ret []RealmMember
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RealmMemberResponse) GetItemsOk() ([]RealmMember, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *RealmMemberResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []RealmMember and assigns it to the Items field.
func (o *RealmMemberResponse) SetItems(v []RealmMember) {
	o.Items = v
}

func (o RealmMemberResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RealmMemberResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableRealmMemberResponse struct {
	value *RealmMemberResponse
	isSet bool
}

func (v NullableRealmMemberResponse) Get() *RealmMemberResponse {
	return v.value
}

func (v *NullableRealmMemberResponse) Set(val *RealmMemberResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRealmMemberResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRealmMemberResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRealmMemberResponse(val *RealmMemberResponse) *NullableRealmMemberResponse {
	return &NullableRealmMemberResponse{value: val, isSet: true}
}

func (v NullableRealmMemberResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRealmMemberResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
