/*
FlashArray REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.55
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the PolicyrulenfsclientpatchRules type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyrulenfsclientpatchRules{}

// PolicyrulenfsclientpatchRules struct for PolicyrulenfsclientpatchRules
type PolicyrulenfsclientpatchRules struct {
	// Specifies access control for the export. Values include `root-squash`, `all-squash`, and `no-root-squash`. The `root-squash` value prevents client users and groups with root privilege from mapping their root privilege to a file system. All users with UID `0` will have their UID mapped to `anonuid`. All users with GID `0` will have their GID mapped to `anongid`. The `all-squash` value maps all UIDs (including root) to `anonuid` and all GIDs (including root) to `anongid`. The `no-root-squash` value allows users and groups to access the file system with their UIDs and GIDs.
	Access *string `json:"access,omitempty"`
	// Any user whose GID is affected by an `access` of `root_squash` or `all_squash` will have their GID mapped to `anongid`. If not specified, defaults to `65534`. Set to `\"\"` to clear. This value is ignored when user mapping is enabled.
	Anongid *string `json:"anongid,omitempty"`
	// Any user whose UID is affected by an `access` of `root_squash` or `all_squash` will have their UID mapped to `anonuid`. The default `anonuid` is null, which means 65534. Use \"\" to clear.
	Anonuid *string `json:"anonuid,omitempty"`
	// Specifies which clients are given access. Valid values include `IP`, `IP mask`, or `hostname`. The default is `*` if not specified.
	Client *string `json:"client,omitempty"`
	// The NFS protocol version allowed for the export. Values include `nfsv3` and `nfsv4`.
	NfsVersion []string `json:"nfs_version,omitempty"`
	// Specifies which read-write client access permissions are allowed for the export. Values include `rw` and `ro`.
	Permission *string `json:"permission,omitempty"`
	// The security flavors to use for accessing files on this mount point. Values include `auth_sys`, `krb5`, `krb5i`, and `krb5p`. If the server does not support the requested flavor, the mount operation fails. This operation updates all rules of the specified policy. If `auth_sys`, the client is trusted to specify the identity of the user. If `krb5`, cryptographic proof of the identity of the user is provided in each RPC request. This provides strong verification of the identity of users accessing data on the server. Note that additional configuration besides adding this mount option is required to enable Kerberos security. If `krb5i`, integrity checking is added to krb5. This ensures the data has not been tampered with. If `krb5p`, integrity checking and encryption is added to krb5. This is the most secure setting, but it also involves the most performance overhead.
	Security []string `json:"security,omitempty"`
}

// NewPolicyrulenfsclientpatchRules instantiates a new PolicyrulenfsclientpatchRules object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyrulenfsclientpatchRules() *PolicyrulenfsclientpatchRules {
	this := PolicyrulenfsclientpatchRules{}
	return &this
}

// NewPolicyrulenfsclientpatchRulesWithDefaults instantiates a new PolicyrulenfsclientpatchRules object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyrulenfsclientpatchRulesWithDefaults() *PolicyrulenfsclientpatchRules {
	this := PolicyrulenfsclientpatchRules{}
	return &this
}

// GetAccess returns the Access field value if set, zero value otherwise.
func (o *PolicyrulenfsclientpatchRules) GetAccess() string {
	if o == nil || IsNil(o.Access) {
		var ret string
		return ret
	}
	return *o.Access
}

// GetAccessOk returns a tuple with the Access field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyrulenfsclientpatchRules) GetAccessOk() (*string, bool) {
	if o == nil || IsNil(o.Access) {
		return nil, false
	}
	return o.Access, true
}

// HasAccess returns a boolean if a field has been set.
func (o *PolicyrulenfsclientpatchRules) HasAccess() bool {
	if o != nil && !IsNil(o.Access) {
		return true
	}

	return false
}

// SetAccess gets a reference to the given string and assigns it to the Access field.
func (o *PolicyrulenfsclientpatchRules) SetAccess(v string) {
	o.Access = &v
}

// GetAnongid returns the Anongid field value if set, zero value otherwise.
func (o *PolicyrulenfsclientpatchRules) GetAnongid() string {
	if o == nil || IsNil(o.Anongid) {
		var ret string
		return ret
	}
	return *o.Anongid
}

// GetAnongidOk returns a tuple with the Anongid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyrulenfsclientpatchRules) GetAnongidOk() (*string, bool) {
	if o == nil || IsNil(o.Anongid) {
		return nil, false
	}
	return o.Anongid, true
}

// HasAnongid returns a boolean if a field has been set.
func (o *PolicyrulenfsclientpatchRules) HasAnongid() bool {
	if o != nil && !IsNil(o.Anongid) {
		return true
	}

	return false
}

// SetAnongid gets a reference to the given string and assigns it to the Anongid field.
func (o *PolicyrulenfsclientpatchRules) SetAnongid(v string) {
	o.Anongid = &v
}

// GetAnonuid returns the Anonuid field value if set, zero value otherwise.
func (o *PolicyrulenfsclientpatchRules) GetAnonuid() string {
	if o == nil || IsNil(o.Anonuid) {
		var ret string
		return ret
	}
	return *o.Anonuid
}

// GetAnonuidOk returns a tuple with the Anonuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyrulenfsclientpatchRules) GetAnonuidOk() (*string, bool) {
	if o == nil || IsNil(o.Anonuid) {
		return nil, false
	}
	return o.Anonuid, true
}

// HasAnonuid returns a boolean if a field has been set.
func (o *PolicyrulenfsclientpatchRules) HasAnonuid() bool {
	if o != nil && !IsNil(o.Anonuid) {
		return true
	}

	return false
}

// SetAnonuid gets a reference to the given string and assigns it to the Anonuid field.
func (o *PolicyrulenfsclientpatchRules) SetAnonuid(v string) {
	o.Anonuid = &v
}

// GetClient returns the Client field value if set, zero value otherwise.
func (o *PolicyrulenfsclientpatchRules) GetClient() string {
	if o == nil || IsNil(o.Client) {
		var ret string
		return ret
	}
	return *o.Client
}

// GetClientOk returns a tuple with the Client field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyrulenfsclientpatchRules) GetClientOk() (*string, bool) {
	if o == nil || IsNil(o.Client) {
		return nil, false
	}
	return o.Client, true
}

// HasClient returns a boolean if a field has been set.
func (o *PolicyrulenfsclientpatchRules) HasClient() bool {
	if o != nil && !IsNil(o.Client) {
		return true
	}

	return false
}

// SetClient gets a reference to the given string and assigns it to the Client field.
func (o *PolicyrulenfsclientpatchRules) SetClient(v string) {
	o.Client = &v
}

// GetNfsVersion returns the NfsVersion field value if set, zero value otherwise.
func (o *PolicyrulenfsclientpatchRules) GetNfsVersion() []string {
	if o == nil || IsNil(o.NfsVersion) {
		var ret []string
		return ret
	}
	return o.NfsVersion
}

// GetNfsVersionOk returns a tuple with the NfsVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyrulenfsclientpatchRules) GetNfsVersionOk() ([]string, bool) {
	if o == nil || IsNil(o.NfsVersion) {
		return nil, false
	}
	return o.NfsVersion, true
}

// HasNfsVersion returns a boolean if a field has been set.
func (o *PolicyrulenfsclientpatchRules) HasNfsVersion() bool {
	if o != nil && !IsNil(o.NfsVersion) {
		return true
	}

	return false
}

// SetNfsVersion gets a reference to the given []string and assigns it to the NfsVersion field.
func (o *PolicyrulenfsclientpatchRules) SetNfsVersion(v []string) {
	o.NfsVersion = v
}

// GetPermission returns the Permission field value if set, zero value otherwise.
func (o *PolicyrulenfsclientpatchRules) GetPermission() string {
	if o == nil || IsNil(o.Permission) {
		var ret string
		return ret
	}
	return *o.Permission
}

// GetPermissionOk returns a tuple with the Permission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyrulenfsclientpatchRules) GetPermissionOk() (*string, bool) {
	if o == nil || IsNil(o.Permission) {
		return nil, false
	}
	return o.Permission, true
}

// HasPermission returns a boolean if a field has been set.
func (o *PolicyrulenfsclientpatchRules) HasPermission() bool {
	if o != nil && !IsNil(o.Permission) {
		return true
	}

	return false
}

// SetPermission gets a reference to the given string and assigns it to the Permission field.
func (o *PolicyrulenfsclientpatchRules) SetPermission(v string) {
	o.Permission = &v
}

// GetSecurity returns the Security field value if set, zero value otherwise.
func (o *PolicyrulenfsclientpatchRules) GetSecurity() []string {
	if o == nil || IsNil(o.Security) {
		var ret []string
		return ret
	}
	return o.Security
}

// GetSecurityOk returns a tuple with the Security field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyrulenfsclientpatchRules) GetSecurityOk() ([]string, bool) {
	if o == nil || IsNil(o.Security) {
		return nil, false
	}
	return o.Security, true
}

// HasSecurity returns a boolean if a field has been set.
func (o *PolicyrulenfsclientpatchRules) HasSecurity() bool {
	if o != nil && !IsNil(o.Security) {
		return true
	}

	return false
}

// SetSecurity gets a reference to the given []string and assigns it to the Security field.
func (o *PolicyrulenfsclientpatchRules) SetSecurity(v []string) {
	o.Security = v
}

func (o PolicyrulenfsclientpatchRules) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyrulenfsclientpatchRules) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Access) {
		toSerialize["access"] = o.Access
	}
	if !IsNil(o.Anongid) {
		toSerialize["anongid"] = o.Anongid
	}
	if !IsNil(o.Anonuid) {
		toSerialize["anonuid"] = o.Anonuid
	}
	if !IsNil(o.Client) {
		toSerialize["client"] = o.Client
	}
	if !IsNil(o.NfsVersion) {
		toSerialize["nfs_version"] = o.NfsVersion
	}
	if !IsNil(o.Permission) {
		toSerialize["permission"] = o.Permission
	}
	if !IsNil(o.Security) {
		toSerialize["security"] = o.Security
	}
	return toSerialize, nil
}

type NullablePolicyrulenfsclientpatchRules struct {
	value *PolicyrulenfsclientpatchRules
	isSet bool
}

func (v NullablePolicyrulenfsclientpatchRules) Get() *PolicyrulenfsclientpatchRules {
	return v.value
}

func (v *NullablePolicyrulenfsclientpatchRules) Set(val *PolicyrulenfsclientpatchRules) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyrulenfsclientpatchRules) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyrulenfsclientpatchRules) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyrulenfsclientpatchRules(val *PolicyrulenfsclientpatchRules) *NullablePolicyrulenfsclientpatchRules {
	return &NullablePolicyrulenfsclientpatchRules{value: val, isSet: true}
}

func (v NullablePolicyrulenfsclientpatchRules) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyrulenfsclientpatchRules) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
