/*
FlashBlade REST API

OpenAPI specification for FlashBlade REST API, developed by Pure Storage, Inc. (https://www.purestorage.com/).

API version: 2.25
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PresetWorkloadConstraintsResourceReferenceAllowedValues type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PresetWorkloadConstraintsResourceReferenceAllowedValues{}

// PresetWorkloadConstraintsResourceReferenceAllowedValues struct for PresetWorkloadConstraintsResourceReferenceAllowedValues
type PresetWorkloadConstraintsResourceReferenceAllowedValues struct {
	// The type of resource the parameter references. Valid values include `servers`, `storage-classes`, and `remote-arrays`.
	ResourceType string `json:"resource_type"`
}

type _PresetWorkloadConstraintsResourceReferenceAllowedValues PresetWorkloadConstraintsResourceReferenceAllowedValues

// NewPresetWorkloadConstraintsResourceReferenceAllowedValues instantiates a new PresetWorkloadConstraintsResourceReferenceAllowedValues object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPresetWorkloadConstraintsResourceReferenceAllowedValues(resourceType string) *PresetWorkloadConstraintsResourceReferenceAllowedValues {
	this := PresetWorkloadConstraintsResourceReferenceAllowedValues{}
	this.ResourceType = resourceType
	return &this
}

// NewPresetWorkloadConstraintsResourceReferenceAllowedValuesWithDefaults instantiates a new PresetWorkloadConstraintsResourceReferenceAllowedValues object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPresetWorkloadConstraintsResourceReferenceAllowedValuesWithDefaults() *PresetWorkloadConstraintsResourceReferenceAllowedValues {
	this := PresetWorkloadConstraintsResourceReferenceAllowedValues{}
	return &this
}

// GetResourceType returns the ResourceType field value
func (o *PresetWorkloadConstraintsResourceReferenceAllowedValues) GetResourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value
// and a boolean to check if the value has been set.
func (o *PresetWorkloadConstraintsResourceReferenceAllowedValues) GetResourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceType, true
}

// SetResourceType sets field value
func (o *PresetWorkloadConstraintsResourceReferenceAllowedValues) SetResourceType(v string) {
	o.ResourceType = v
}

func (o PresetWorkloadConstraintsResourceReferenceAllowedValues) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PresetWorkloadConstraintsResourceReferenceAllowedValues) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resource_type"] = o.ResourceType
	return toSerialize, nil
}

func (o *PresetWorkloadConstraintsResourceReferenceAllowedValues) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resource_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPresetWorkloadConstraintsResourceReferenceAllowedValues := _PresetWorkloadConstraintsResourceReferenceAllowedValues{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPresetWorkloadConstraintsResourceReferenceAllowedValues)

	if err != nil {
		return err
	}

	*o = PresetWorkloadConstraintsResourceReferenceAllowedValues(varPresetWorkloadConstraintsResourceReferenceAllowedValues)

	return err
}

type NullablePresetWorkloadConstraintsResourceReferenceAllowedValues struct {
	value *PresetWorkloadConstraintsResourceReferenceAllowedValues
	isSet bool
}

func (v NullablePresetWorkloadConstraintsResourceReferenceAllowedValues) Get() *PresetWorkloadConstraintsResourceReferenceAllowedValues {
	return v.value
}

func (v *NullablePresetWorkloadConstraintsResourceReferenceAllowedValues) Set(val *PresetWorkloadConstraintsResourceReferenceAllowedValues) {
	v.value = val
	v.isSet = true
}

func (v NullablePresetWorkloadConstraintsResourceReferenceAllowedValues) IsSet() bool {
	return v.isSet
}

func (v *NullablePresetWorkloadConstraintsResourceReferenceAllowedValues) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePresetWorkloadConstraintsResourceReferenceAllowedValues(val *PresetWorkloadConstraintsResourceReferenceAllowedValues) *NullablePresetWorkloadConstraintsResourceReferenceAllowedValues {
	return &NullablePresetWorkloadConstraintsResourceReferenceAllowedValues{value: val, isSet: true}
}

func (v NullablePresetWorkloadConstraintsResourceReferenceAllowedValues) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePresetWorkloadConstraintsResourceReferenceAllowedValues) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
