/*
FlashBlade REST API

A lightweight client for FlashBlade REST API 2.13, developed by Pure Storage, Inc. (http://www.purestorage.com/).

API version: 2.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the CrossOriginResourceSharingPolicyRuleBulkManage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CrossOriginResourceSharingPolicyRuleBulkManage{}

// CrossOriginResourceSharingPolicyRuleBulkManage struct for CrossOriginResourceSharingPolicyRuleBulkManage
type CrossOriginResourceSharingPolicyRuleBulkManage struct {
	// A list of headers that are permitted to be included in cross-origin requests to access a bucket. The only currently supported allowed header is `*`.
	AllowedHeaders []string `json:"allowed_headers,omitempty"`
	// A list of HTTP methods that are permitted for cross-origin requests to access a bucket. The only currently supported combination of allowed methods is all methods `[\"GET\", \"PUT\", \"HEAD\", \"POST\", \"DELETE\"]`.
	AllowedMethods []string `json:"allowed_methods,omitempty"`
	// A list of origins (domains) that are permitted to make cross-origin requests to access a bucket. The only currently supported allowed origin is `*`.
	AllowedOrigins []string `json:"allowed_origins,omitempty"`
	// Name of the object (e.g., a file system or snapshot).
	Name *string `json:"name,omitempty"`
}

// NewCrossOriginResourceSharingPolicyRuleBulkManage instantiates a new CrossOriginResourceSharingPolicyRuleBulkManage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCrossOriginResourceSharingPolicyRuleBulkManage() *CrossOriginResourceSharingPolicyRuleBulkManage {
	this := CrossOriginResourceSharingPolicyRuleBulkManage{}
	return &this
}

// NewCrossOriginResourceSharingPolicyRuleBulkManageWithDefaults instantiates a new CrossOriginResourceSharingPolicyRuleBulkManage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCrossOriginResourceSharingPolicyRuleBulkManageWithDefaults() *CrossOriginResourceSharingPolicyRuleBulkManage {
	this := CrossOriginResourceSharingPolicyRuleBulkManage{}
	return &this
}

// GetAllowedHeaders returns the AllowedHeaders field value if set, zero value otherwise.
func (o *CrossOriginResourceSharingPolicyRuleBulkManage) GetAllowedHeaders() []string {
	if o == nil || IsNil(o.AllowedHeaders) {
		var ret []string
		return ret
	}
	return o.AllowedHeaders
}

// GetAllowedHeadersOk returns a tuple with the AllowedHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrossOriginResourceSharingPolicyRuleBulkManage) GetAllowedHeadersOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedHeaders) {
		return nil, false
	}
	return o.AllowedHeaders, true
}

// HasAllowedHeaders returns a boolean if a field has been set.
func (o *CrossOriginResourceSharingPolicyRuleBulkManage) HasAllowedHeaders() bool {
	if o != nil && !IsNil(o.AllowedHeaders) {
		return true
	}

	return false
}

// SetAllowedHeaders gets a reference to the given []string and assigns it to the AllowedHeaders field.
func (o *CrossOriginResourceSharingPolicyRuleBulkManage) SetAllowedHeaders(v []string) {
	o.AllowedHeaders = v
}

// GetAllowedMethods returns the AllowedMethods field value if set, zero value otherwise.
func (o *CrossOriginResourceSharingPolicyRuleBulkManage) GetAllowedMethods() []string {
	if o == nil || IsNil(o.AllowedMethods) {
		var ret []string
		return ret
	}
	return o.AllowedMethods
}

// GetAllowedMethodsOk returns a tuple with the AllowedMethods field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrossOriginResourceSharingPolicyRuleBulkManage) GetAllowedMethodsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedMethods) {
		return nil, false
	}
	return o.AllowedMethods, true
}

// HasAllowedMethods returns a boolean if a field has been set.
func (o *CrossOriginResourceSharingPolicyRuleBulkManage) HasAllowedMethods() bool {
	if o != nil && !IsNil(o.AllowedMethods) {
		return true
	}

	return false
}

// SetAllowedMethods gets a reference to the given []string and assigns it to the AllowedMethods field.
func (o *CrossOriginResourceSharingPolicyRuleBulkManage) SetAllowedMethods(v []string) {
	o.AllowedMethods = v
}

// GetAllowedOrigins returns the AllowedOrigins field value if set, zero value otherwise.
func (o *CrossOriginResourceSharingPolicyRuleBulkManage) GetAllowedOrigins() []string {
	if o == nil || IsNil(o.AllowedOrigins) {
		var ret []string
		return ret
	}
	return o.AllowedOrigins
}

// GetAllowedOriginsOk returns a tuple with the AllowedOrigins field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrossOriginResourceSharingPolicyRuleBulkManage) GetAllowedOriginsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedOrigins) {
		return nil, false
	}
	return o.AllowedOrigins, true
}

// HasAllowedOrigins returns a boolean if a field has been set.
func (o *CrossOriginResourceSharingPolicyRuleBulkManage) HasAllowedOrigins() bool {
	if o != nil && !IsNil(o.AllowedOrigins) {
		return true
	}

	return false
}

// SetAllowedOrigins gets a reference to the given []string and assigns it to the AllowedOrigins field.
func (o *CrossOriginResourceSharingPolicyRuleBulkManage) SetAllowedOrigins(v []string) {
	o.AllowedOrigins = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CrossOriginResourceSharingPolicyRuleBulkManage) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CrossOriginResourceSharingPolicyRuleBulkManage) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CrossOriginResourceSharingPolicyRuleBulkManage) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CrossOriginResourceSharingPolicyRuleBulkManage) SetName(v string) {
	o.Name = &v
}

func (o CrossOriginResourceSharingPolicyRuleBulkManage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CrossOriginResourceSharingPolicyRuleBulkManage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AllowedHeaders) {
		toSerialize["allowed_headers"] = o.AllowedHeaders
	}
	if !IsNil(o.AllowedMethods) {
		toSerialize["allowed_methods"] = o.AllowedMethods
	}
	if !IsNil(o.AllowedOrigins) {
		toSerialize["allowed_origins"] = o.AllowedOrigins
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableCrossOriginResourceSharingPolicyRuleBulkManage struct {
	value *CrossOriginResourceSharingPolicyRuleBulkManage
	isSet bool
}

func (v NullableCrossOriginResourceSharingPolicyRuleBulkManage) Get() *CrossOriginResourceSharingPolicyRuleBulkManage {
	return v.value
}

func (v *NullableCrossOriginResourceSharingPolicyRuleBulkManage) Set(val *CrossOriginResourceSharingPolicyRuleBulkManage) {
	v.value = val
	v.isSet = true
}

func (v NullableCrossOriginResourceSharingPolicyRuleBulkManage) IsSet() bool {
	return v.isSet
}

func (v *NullableCrossOriginResourceSharingPolicyRuleBulkManage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCrossOriginResourceSharingPolicyRuleBulkManage(val *CrossOriginResourceSharingPolicyRuleBulkManage) *NullableCrossOriginResourceSharingPolicyRuleBulkManage {
	return &NullableCrossOriginResourceSharingPolicyRuleBulkManage{value: val, isSet: true}
}

func (v NullableCrossOriginResourceSharingPolicyRuleBulkManage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCrossOriginResourceSharingPolicyRuleBulkManage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
