/*
FlashArray REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.24
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the NetworkInterfacePortDetailsStaticTxBiasThresholds type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkInterfacePortDetailsStaticTxBiasThresholds{}

// NetworkInterfacePortDetailsStaticTxBiasThresholds The alarm low, warn low, warn high, alarm high thresholds for Tx bias current in mA.
type NetworkInterfacePortDetailsStaticTxBiasThresholds struct {
	// The alarm high threshold for Tx bias current in mA.
	AlarmHigh *float64 `json:"alarm_high,omitempty"`
	// The alarm low threshold for Tx bias current in mA.
	AlarmLow *float64 `json:"alarm_low,omitempty"`
	// The warn high threshold for Tx bias current in mA.
	WarnHigh *float64 `json:"warn_high,omitempty"`
	// The warn low threshold for Tx bias current in mA.
	WarnLow *float64 `json:"warn_low,omitempty"`
}

// NewNetworkInterfacePortDetailsStaticTxBiasThresholds instantiates a new NetworkInterfacePortDetailsStaticTxBiasThresholds object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkInterfacePortDetailsStaticTxBiasThresholds() *NetworkInterfacePortDetailsStaticTxBiasThresholds {
	this := NetworkInterfacePortDetailsStaticTxBiasThresholds{}
	return &this
}

// NewNetworkInterfacePortDetailsStaticTxBiasThresholdsWithDefaults instantiates a new NetworkInterfacePortDetailsStaticTxBiasThresholds object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkInterfacePortDetailsStaticTxBiasThresholdsWithDefaults() *NetworkInterfacePortDetailsStaticTxBiasThresholds {
	this := NetworkInterfacePortDetailsStaticTxBiasThresholds{}
	return &this
}

// GetAlarmHigh returns the AlarmHigh field value if set, zero value otherwise.
func (o *NetworkInterfacePortDetailsStaticTxBiasThresholds) GetAlarmHigh() float64 {
	if o == nil || IsNil(o.AlarmHigh) {
		var ret float64
		return ret
	}
	return *o.AlarmHigh
}

// GetAlarmHighOk returns a tuple with the AlarmHigh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkInterfacePortDetailsStaticTxBiasThresholds) GetAlarmHighOk() (*float64, bool) {
	if o == nil || IsNil(o.AlarmHigh) {
		return nil, false
	}
	return o.AlarmHigh, true
}

// HasAlarmHigh returns a boolean if a field has been set.
func (o *NetworkInterfacePortDetailsStaticTxBiasThresholds) HasAlarmHigh() bool {
	if o != nil && !IsNil(o.AlarmHigh) {
		return true
	}

	return false
}

// SetAlarmHigh gets a reference to the given float64 and assigns it to the AlarmHigh field.
func (o *NetworkInterfacePortDetailsStaticTxBiasThresholds) SetAlarmHigh(v float64) {
	o.AlarmHigh = &v
}

// GetAlarmLow returns the AlarmLow field value if set, zero value otherwise.
func (o *NetworkInterfacePortDetailsStaticTxBiasThresholds) GetAlarmLow() float64 {
	if o == nil || IsNil(o.AlarmLow) {
		var ret float64
		return ret
	}
	return *o.AlarmLow
}

// GetAlarmLowOk returns a tuple with the AlarmLow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkInterfacePortDetailsStaticTxBiasThresholds) GetAlarmLowOk() (*float64, bool) {
	if o == nil || IsNil(o.AlarmLow) {
		return nil, false
	}
	return o.AlarmLow, true
}

// HasAlarmLow returns a boolean if a field has been set.
func (o *NetworkInterfacePortDetailsStaticTxBiasThresholds) HasAlarmLow() bool {
	if o != nil && !IsNil(o.AlarmLow) {
		return true
	}

	return false
}

// SetAlarmLow gets a reference to the given float64 and assigns it to the AlarmLow field.
func (o *NetworkInterfacePortDetailsStaticTxBiasThresholds) SetAlarmLow(v float64) {
	o.AlarmLow = &v
}

// GetWarnHigh returns the WarnHigh field value if set, zero value otherwise.
func (o *NetworkInterfacePortDetailsStaticTxBiasThresholds) GetWarnHigh() float64 {
	if o == nil || IsNil(o.WarnHigh) {
		var ret float64
		return ret
	}
	return *o.WarnHigh
}

// GetWarnHighOk returns a tuple with the WarnHigh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkInterfacePortDetailsStaticTxBiasThresholds) GetWarnHighOk() (*float64, bool) {
	if o == nil || IsNil(o.WarnHigh) {
		return nil, false
	}
	return o.WarnHigh, true
}

// HasWarnHigh returns a boolean if a field has been set.
func (o *NetworkInterfacePortDetailsStaticTxBiasThresholds) HasWarnHigh() bool {
	if o != nil && !IsNil(o.WarnHigh) {
		return true
	}

	return false
}

// SetWarnHigh gets a reference to the given float64 and assigns it to the WarnHigh field.
func (o *NetworkInterfacePortDetailsStaticTxBiasThresholds) SetWarnHigh(v float64) {
	o.WarnHigh = &v
}

// GetWarnLow returns the WarnLow field value if set, zero value otherwise.
func (o *NetworkInterfacePortDetailsStaticTxBiasThresholds) GetWarnLow() float64 {
	if o == nil || IsNil(o.WarnLow) {
		var ret float64
		return ret
	}
	return *o.WarnLow
}

// GetWarnLowOk returns a tuple with the WarnLow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkInterfacePortDetailsStaticTxBiasThresholds) GetWarnLowOk() (*float64, bool) {
	if o == nil || IsNil(o.WarnLow) {
		return nil, false
	}
	return o.WarnLow, true
}

// HasWarnLow returns a boolean if a field has been set.
func (o *NetworkInterfacePortDetailsStaticTxBiasThresholds) HasWarnLow() bool {
	if o != nil && !IsNil(o.WarnLow) {
		return true
	}

	return false
}

// SetWarnLow gets a reference to the given float64 and assigns it to the WarnLow field.
func (o *NetworkInterfacePortDetailsStaticTxBiasThresholds) SetWarnLow(v float64) {
	o.WarnLow = &v
}

func (o NetworkInterfacePortDetailsStaticTxBiasThresholds) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkInterfacePortDetailsStaticTxBiasThresholds) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AlarmHigh) {
		toSerialize["alarm_high"] = o.AlarmHigh
	}
	if !IsNil(o.AlarmLow) {
		toSerialize["alarm_low"] = o.AlarmLow
	}
	if !IsNil(o.WarnHigh) {
		toSerialize["warn_high"] = o.WarnHigh
	}
	if !IsNil(o.WarnLow) {
		toSerialize["warn_low"] = o.WarnLow
	}
	return toSerialize, nil
}

type NullableNetworkInterfacePortDetailsStaticTxBiasThresholds struct {
	value *NetworkInterfacePortDetailsStaticTxBiasThresholds
	isSet bool
}

func (v NullableNetworkInterfacePortDetailsStaticTxBiasThresholds) Get() *NetworkInterfacePortDetailsStaticTxBiasThresholds {
	return v.value
}

func (v *NullableNetworkInterfacePortDetailsStaticTxBiasThresholds) Set(val *NetworkInterfacePortDetailsStaticTxBiasThresholds) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkInterfacePortDetailsStaticTxBiasThresholds) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkInterfacePortDetailsStaticTxBiasThresholds) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkInterfacePortDetailsStaticTxBiasThresholds(val *NetworkInterfacePortDetailsStaticTxBiasThresholds) *NullableNetworkInterfacePortDetailsStaticTxBiasThresholds {
	return &NullableNetworkInterfacePortDetailsStaticTxBiasThresholds{value: val, isSet: true}
}

func (v NullableNetworkInterfacePortDetailsStaticTxBiasThresholds) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkInterfacePortDetailsStaticTxBiasThresholds) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
