/*
FlashArray REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.58
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)

// AntivirusAPIService AntivirusAPI service
type AntivirusAPIService service

type APIAntivirusTargetsGetRequest struct {
	ctx               context.Context
	APIService        *AntivirusAPIService
	authorization     *string
	xRequestID        *string
	allowErrors       *bool
	contextNames      *[]string
	continuationToken *string
	filter            *string
	ids               *[]string
	limit             *int32
	names             *[]string
	offset            *int32
	sort              *[]string
	totalItemCount    *bool
}

// Access token (in JWT format) required to use any API endpoint (except &#x60;/oauth2&#x60;, &#x60;/login&#x60;, and &#x60;/logout&#x60;)
func (r APIAntivirusTargetsGetRequest) Authorization(authorization string) APIAntivirusTargetsGetRequest {
	r.authorization = &authorization
	return r
}

// Supplied by client during request or generated by server.
func (r APIAntivirusTargetsGetRequest) XRequestID(xRequestID string) APIAntivirusTargetsGetRequest {
	r.xRequestID = &xRequestID
	return r
}

// If set to &#x60;true&#x60;, the API will allow the operation to continue even if there are errors. Any errors will be returned in the &#x60;errors&#x60; field of the response. If set to &#x60;false&#x60;, the operation will fail if there are any errors.
func (r APIAntivirusTargetsGetRequest) AllowErrors(allowErrors bool) APIAntivirusTargetsGetRequest {
	r.allowErrors = &allowErrors
	return r
}

// Performs the operation on the unique contexts specified.  If specified, each context name must be the name of an array in the same fleet or the name of the fleet itself.  If not specified, the context will default to the array that received this request.  Other parameters provided with the request, such as names of volumes or snapshots, are resolved relative to the provided &#x60;context&#x60;.  Enter multiple names in comma-separated format. For example, &#x60;name01,name02&#x60;.
func (r APIAntivirusTargetsGetRequest) ContextNames(contextNames []string) APIAntivirusTargetsGetRequest {
	r.contextNames = &contextNames
	return r
}

// A token used to retrieve the next page of data with some consistency guaranteed. The token is a Base64 encoded value. Set &#x60;continuation_token&#x60; to the system-generated token taken from the &#x60;x-next-token&#x60; header field of the response. A query has reached its last page when the response does not include a token. Pagination requires the &#x60;limit&#x60; and &#x60;continuation_token&#x60; query parameters.
func (r APIAntivirusTargetsGetRequest) ContinuationToken(continuationToken string) APIAntivirusTargetsGetRequest {
	r.continuationToken = &continuationToken
	return r
}

// Narrows down the results to only the response objects that satisfy the filter criteria.
func (r APIAntivirusTargetsGetRequest) Filter(filter string) APIAntivirusTargetsGetRequest {
	r.filter = &filter
	return r
}

// A comma-separated list of unique resource IDs. At least one resource must match  each specified ID, otherwise an error is returned. This parameter is required   if ids or names is not provided, but it cannot be used together with name or names.
func (r APIAntivirusTargetsGetRequest) Ids(ids []string) APIAntivirusTargetsGetRequest {
	r.ids = &ids
	return r
}

// Limits the size of the response to the specified number of objects on each page. To return the total number of resources, set &#x60;limit&#x3D;0&#x60;. The total number of resources is returned as a &#x60;total_item_count&#x60; value. If the page size requested is larger than the system maximum limit, the server returns the maximum limit, disregarding the requested page size.
func (r APIAntivirusTargetsGetRequest) Limit(limit int32) APIAntivirusTargetsGetRequest {
	r.limit = &limit
	return r
}

// Performs the operation on the unique names specified. Enter multiple names in comma-separated format. For example, &#x60;name01,name02&#x60;.  If there is not at least one resource that matches each of the elements of &#x60;names&#x60;, then an error is returned, except when creating new resources.
func (r APIAntivirusTargetsGetRequest) Names(names []string) APIAntivirusTargetsGetRequest {
	r.names = &names
	return r
}

// The starting position based on the results of the query in relation to the full set of response objects returned.
func (r APIAntivirusTargetsGetRequest) Offset(offset int32) APIAntivirusTargetsGetRequest {
	r.offset = &offset
	return r
}

// Sorts the response objects by the specified fields. Sorting can be applied to any field name  in the response, in ascending order by default, or in descending order by prefixing the  field name with a minus sign (-). Multiple fields can be specified as a comma-separated  list (e.g., sort volumes by size descending, then by name ascending). If sort is provided,  the response will not include a continuation_token.
func (r APIAntivirusTargetsGetRequest) Sort(sort []string) APIAntivirusTargetsGetRequest {
	r.sort = &sort
	return r
}

// If set to &#x60;true&#x60;, the &#x60;total_item_count&#x60; matching the specified query parameters is calculated and returned in the response. If set to &#x60;false&#x60;, the &#x60;total_item_count&#x60; is &#x60;null&#x60; in the response. This may speed up queries where the &#x60;total_item_count&#x60; is large. If not specified, defaults to &#x60;false&#x60;.
func (r APIAntivirusTargetsGetRequest) TotalItemCount(totalItemCount bool) APIAntivirusTargetsGetRequest {
	r.totalItemCount = &totalItemCount
	return r
}

func (r APIAntivirusTargetsGetRequest) Execute() (*AntivirusTargetGetResponse, *http.Response, error) {
	return r.APIService.AntivirusTargetsGetExecute(r)
}

/*
AntivirusTargetsGet List antivirus targets

Displays a list of antivirus targets (pools) of all types.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return APIAntivirusTargetsGetRequest
*/
func (a *AntivirusAPIService) AntivirusTargetsGet(ctx context.Context) APIAntivirusTargetsGetRequest {
	return APIAntivirusTargetsGetRequest{
		APIService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return AntivirusTargetGetResponse
func (a *AntivirusAPIService) AntivirusTargetsGetExecute(r APIAntivirusTargetsGetRequest) (*AntivirusTargetGetResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *AntivirusTargetGetResponse
	)

	endpoint := "AntivirusAPIService.AntivirusTargetsGet"
	localVarHeaderParams := make(map[string]string)

	localBasePath := a.client.cfg.ArrayURL

	nonAuthEndpoints := map[string]bool{
		"AuthorizationAPIService.Oauth210TokenPost": true,
		"AuthorizationAPIService.LoginPost":         true,
	}
	var authenticator Authenticator
	if !nonAuthEndpoints[endpoint] {
		authenticator = a.client.cfg.Authenticator
	} else {
		authenticator = nil
	}

	if authenticator != nil {
		if err := authenticator.SetAuthHeader(r.ctx, *a.client.AuthorizationAPI, localVarHeaderParams); err != nil {
			return localVarReturnValue, nil, err
		}
	}

	localVarPath := localBasePath + "/api/2.58/antivirus/targets"

	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.allowErrors != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "allow_errors", r.allowErrors, "")
	}
	if r.contextNames != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "context_names", r.contextNames, "csv")
	}
	if r.continuationToken != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "continuation_token", r.continuationToken, "")
	}
	if r.filter != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "filter", r.filter, "")
	}
	if r.ids != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "ids", r.ids, "csv")
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "")
	}
	if r.names != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "names", r.names, "csv")
	}
	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "")
	}
	if r.sort != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sort", r.sort, "csv")
	}
	if r.totalItemCount != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "total_item_count", r.totalItemCount, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, http.CanonicalHeaderKey("Authorization"), r.authorization, "")
	}
	if r.xRequestID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, http.CanonicalHeaderKey("X-Request-ID"), r.xRequestID, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	ignoredEndpoints := map[string]bool{
		"AuthorizationAPIService.LogoutPost": true,
	}

	authStatusCodes := map[int]bool{
		401: true,
	}

	if authStatusCodes[localVarHTTPResponse.StatusCode] && !ignoredEndpoints[endpoint] && authenticator != nil {
		// Drain and close the first response body so its connection can be
		// reused; keep a buffered copy readable in case the retry fails and
		// this response is returned to the caller.
		firstRespBody, _ := io.ReadAll(localVarHTTPResponse.Body)
		localVarHTTPResponse.Body.Close()
		localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(firstRespBody))
		// retry with token refresh
		err = authenticator.RefreshAccessToken(r.ctx, *a.client.AuthorizationAPI)
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		// Update auth header
		if err := authenticator.SetAuthHeader(r.ctx, *a.client.AuthorizationAPI, localVarHeaderParams); err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		req, err = a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		localVarHTTPResponse, err = a.client.callAPI(req)
		if err != nil || localVarHTTPResponse == nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &ErrorResponse{
			StatusCode: localVarHTTPResponse.StatusCode,
			Headers:    localVarHTTPResponse.Header,
		}
		err = a.client.decode(&newErr, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, &GenericOpenAPIError{
				body:  localVarBody,
				error: localVarHTTPResponse.Status,
			}
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type APIAntivirusTargetsIcapDeleteRequest struct {
	ctx            context.Context
	APIService     *AntivirusAPIService
	authorization  *string
	xRequestID     *string
	contextNames   *[]string
	deleteScanners *bool
	ids            *[]string
	names          *[]string
}

// Access token (in JWT format) required to use any API endpoint (except &#x60;/oauth2&#x60;, &#x60;/login&#x60;, and &#x60;/logout&#x60;)
func (r APIAntivirusTargetsIcapDeleteRequest) Authorization(authorization string) APIAntivirusTargetsIcapDeleteRequest {
	r.authorization = &authorization
	return r
}

// Supplied by client during request or generated by server.
func (r APIAntivirusTargetsIcapDeleteRequest) XRequestID(xRequestID string) APIAntivirusTargetsIcapDeleteRequest {
	r.xRequestID = &xRequestID
	return r
}

// Performs the operation on the context specified.  If specified, the context names must be an array of size 1, and the single element must be the name of an array in the same fleet or the name of the fleet itself. If not specified, the context will default to the array that received this request.  Other parameters provided with the request, such as names of volumes or snapshots, are resolved relative to the provided &#x60;context&#x60;.
func (r APIAntivirusTargetsIcapDeleteRequest) ContextNames(contextNames []string) APIAntivirusTargetsIcapDeleteRequest {
	r.contextNames = &contextNames
	return r
}

// If set to &#x60;true&#x60;, this parameter deletes all scanners associated with the antivirus ICAP target along with the target itself.
func (r APIAntivirusTargetsIcapDeleteRequest) DeleteScanners(deleteScanners bool) APIAntivirusTargetsIcapDeleteRequest {
	r.deleteScanners = &deleteScanners
	return r
}

// A comma-separated list of unique resource IDs. At least one resource must match  each specified ID, otherwise an error is returned. This parameter is required   if ids or names is not provided, but it cannot be used together with name or names.
func (r APIAntivirusTargetsIcapDeleteRequest) Ids(ids []string) APIAntivirusTargetsIcapDeleteRequest {
	r.ids = &ids
	return r
}

// Performs the operation on the unique names specified. Enter multiple names in comma-separated format. For example, &#x60;name01,name02&#x60;.  If there is not at least one resource that matches each of the elements of &#x60;names&#x60;, then an error is returned, except when creating new resources.
func (r APIAntivirusTargetsIcapDeleteRequest) Names(names []string) APIAntivirusTargetsIcapDeleteRequest {
	r.names = &names
	return r
}

func (r APIAntivirusTargetsIcapDeleteRequest) Execute() (*http.Response, error) {
	return r.APIService.AntivirusTargetsIcapDeleteExecute(r)
}

/*
AntivirusTargetsIcapDelete Delete antivirus ICAP targets

Deletes one or more antivirus ICAP targets. The `names` parameter
is required. A target cannot be deleted if it has scanners attached.
To also delete all associated scanners, set `delete_scanners` to
`true`.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return APIAntivirusTargetsIcapDeleteRequest
*/
func (a *AntivirusAPIService) AntivirusTargetsIcapDelete(ctx context.Context) APIAntivirusTargetsIcapDeleteRequest {
	return APIAntivirusTargetsIcapDeleteRequest{
		APIService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
func (a *AntivirusAPIService) AntivirusTargetsIcapDeleteExecute(r APIAntivirusTargetsIcapDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	endpoint := "AntivirusAPIService.AntivirusTargetsIcapDelete"
	localVarHeaderParams := make(map[string]string)

	localBasePath := a.client.cfg.ArrayURL

	nonAuthEndpoints := map[string]bool{
		"AuthorizationAPIService.Oauth210TokenPost": true,
		"AuthorizationAPIService.LoginPost":         true,
	}
	var authenticator Authenticator
	if !nonAuthEndpoints[endpoint] {
		authenticator = a.client.cfg.Authenticator
	} else {
		authenticator = nil
	}

	if authenticator != nil {
		if err := authenticator.SetAuthHeader(r.ctx, *a.client.AuthorizationAPI, localVarHeaderParams); err != nil {
			return nil, err
		}
	}

	localVarPath := localBasePath + "/api/2.58/antivirus/targets/icap"

	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.contextNames != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "context_names", r.contextNames, "csv")
	}
	if r.deleteScanners != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "delete_scanners", r.deleteScanners, "")
	}
	if r.ids != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "ids", r.ids, "csv")
	}
	if r.names != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "names", r.names, "csv")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, http.CanonicalHeaderKey("Authorization"), r.authorization, "")
	}
	if r.xRequestID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, http.CanonicalHeaderKey("X-Request-ID"), r.xRequestID, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	ignoredEndpoints := map[string]bool{
		"AuthorizationAPIService.LogoutPost": true,
	}

	authStatusCodes := map[int]bool{
		401: true,
	}

	if authStatusCodes[localVarHTTPResponse.StatusCode] && !ignoredEndpoints[endpoint] && authenticator != nil {
		// Drain and close the first response body so its connection can be
		// reused; keep a buffered copy readable in case the retry fails and
		// this response is returned to the caller.
		firstRespBody, _ := io.ReadAll(localVarHTTPResponse.Body)
		localVarHTTPResponse.Body.Close()
		localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(firstRespBody))
		// retry with token refresh
		err = authenticator.RefreshAccessToken(r.ctx, *a.client.AuthorizationAPI)
		if err != nil {
			return localVarHTTPResponse, err
		}
		// Update auth header
		if err := authenticator.SetAuthHeader(r.ctx, *a.client.AuthorizationAPI, localVarHeaderParams); err != nil {
			return localVarHTTPResponse, err
		}
		req, err = a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
		if err != nil {
			return localVarHTTPResponse, err
		}
		localVarHTTPResponse, err = a.client.callAPI(req)
		if err != nil || localVarHTTPResponse == nil {
			return localVarHTTPResponse, err
		}
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &ErrorResponse{
			StatusCode: localVarHTTPResponse.StatusCode,
			Headers:    localVarHTTPResponse.Header,
		}
		err = a.client.decode(&newErr, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
		if err != nil {
			return localVarHTTPResponse, &GenericOpenAPIError{
				body:  localVarBody,
				error: localVarHTTPResponse.Status,
			}
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type APIAntivirusTargetsIcapGetRequest struct {
	ctx               context.Context
	APIService        *AntivirusAPIService
	authorization     *string
	xRequestID        *string
	allowErrors       *bool
	contextNames      *[]string
	continuationToken *string
	filter            *string
	ids               *[]string
	limit             *int32
	names             *[]string
	offset            *int32
	sort              *[]string
	totalItemCount    *bool
}

// Access token (in JWT format) required to use any API endpoint (except &#x60;/oauth2&#x60;, &#x60;/login&#x60;, and &#x60;/logout&#x60;)
func (r APIAntivirusTargetsIcapGetRequest) Authorization(authorization string) APIAntivirusTargetsIcapGetRequest {
	r.authorization = &authorization
	return r
}

// Supplied by client during request or generated by server.
func (r APIAntivirusTargetsIcapGetRequest) XRequestID(xRequestID string) APIAntivirusTargetsIcapGetRequest {
	r.xRequestID = &xRequestID
	return r
}

// If set to &#x60;true&#x60;, the API will allow the operation to continue even if there are errors. Any errors will be returned in the &#x60;errors&#x60; field of the response. If set to &#x60;false&#x60;, the operation will fail if there are any errors.
func (r APIAntivirusTargetsIcapGetRequest) AllowErrors(allowErrors bool) APIAntivirusTargetsIcapGetRequest {
	r.allowErrors = &allowErrors
	return r
}

// Performs the operation on the unique contexts specified.  If specified, each context name must be the name of an array in the same fleet or the name of the fleet itself.  If not specified, the context will default to the array that received this request.  Other parameters provided with the request, such as names of volumes or snapshots, are resolved relative to the provided &#x60;context&#x60;.  Enter multiple names in comma-separated format. For example, &#x60;name01,name02&#x60;.
func (r APIAntivirusTargetsIcapGetRequest) ContextNames(contextNames []string) APIAntivirusTargetsIcapGetRequest {
	r.contextNames = &contextNames
	return r
}

// A token used to retrieve the next page of data with some consistency guaranteed. The token is a Base64 encoded value. Set &#x60;continuation_token&#x60; to the system-generated token taken from the &#x60;x-next-token&#x60; header field of the response. A query has reached its last page when the response does not include a token. Pagination requires the &#x60;limit&#x60; and &#x60;continuation_token&#x60; query parameters.
func (r APIAntivirusTargetsIcapGetRequest) ContinuationToken(continuationToken string) APIAntivirusTargetsIcapGetRequest {
	r.continuationToken = &continuationToken
	return r
}

// Narrows down the results to only the response objects that satisfy the filter criteria.
func (r APIAntivirusTargetsIcapGetRequest) Filter(filter string) APIAntivirusTargetsIcapGetRequest {
	r.filter = &filter
	return r
}

// A comma-separated list of unique resource IDs. At least one resource must match  each specified ID, otherwise an error is returned. This parameter is required   if ids or names is not provided, but it cannot be used together with name or names.
func (r APIAntivirusTargetsIcapGetRequest) Ids(ids []string) APIAntivirusTargetsIcapGetRequest {
	r.ids = &ids
	return r
}

// Limits the size of the response to the specified number of objects on each page. To return the total number of resources, set &#x60;limit&#x3D;0&#x60;. The total number of resources is returned as a &#x60;total_item_count&#x60; value. If the page size requested is larger than the system maximum limit, the server returns the maximum limit, disregarding the requested page size.
func (r APIAntivirusTargetsIcapGetRequest) Limit(limit int32) APIAntivirusTargetsIcapGetRequest {
	r.limit = &limit
	return r
}

// Performs the operation on the unique names specified. Enter multiple names in comma-separated format. For example, &#x60;name01,name02&#x60;.  If there is not at least one resource that matches each of the elements of &#x60;names&#x60;, then an error is returned, except when creating new resources.
func (r APIAntivirusTargetsIcapGetRequest) Names(names []string) APIAntivirusTargetsIcapGetRequest {
	r.names = &names
	return r
}

// The starting position based on the results of the query in relation to the full set of response objects returned.
func (r APIAntivirusTargetsIcapGetRequest) Offset(offset int32) APIAntivirusTargetsIcapGetRequest {
	r.offset = &offset
	return r
}

// Sorts the response objects by the specified fields. Sorting can be applied to any field name  in the response, in ascending order by default, or in descending order by prefixing the  field name with a minus sign (-). Multiple fields can be specified as a comma-separated  list (e.g., sort volumes by size descending, then by name ascending). If sort is provided,  the response will not include a continuation_token.
func (r APIAntivirusTargetsIcapGetRequest) Sort(sort []string) APIAntivirusTargetsIcapGetRequest {
	r.sort = &sort
	return r
}

// If set to &#x60;true&#x60;, the &#x60;total_item_count&#x60; matching the specified query parameters is calculated and returned in the response. If set to &#x60;false&#x60;, the &#x60;total_item_count&#x60; is &#x60;null&#x60; in the response. This may speed up queries where the &#x60;total_item_count&#x60; is large. If not specified, defaults to &#x60;false&#x60;.
func (r APIAntivirusTargetsIcapGetRequest) TotalItemCount(totalItemCount bool) APIAntivirusTargetsIcapGetRequest {
	r.totalItemCount = &totalItemCount
	return r
}

func (r APIAntivirusTargetsIcapGetRequest) Execute() (*AntivirusIcapTargetGetResponse, *http.Response, error) {
	return r.APIService.AntivirusTargetsIcapGetExecute(r)
}

/*
AntivirusTargetsIcapGet List antivirus ICAP targets

Displays a list of antivirus ICAP targets.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return APIAntivirusTargetsIcapGetRequest
*/
func (a *AntivirusAPIService) AntivirusTargetsIcapGet(ctx context.Context) APIAntivirusTargetsIcapGetRequest {
	return APIAntivirusTargetsIcapGetRequest{
		APIService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return AntivirusIcapTargetGetResponse
func (a *AntivirusAPIService) AntivirusTargetsIcapGetExecute(r APIAntivirusTargetsIcapGetRequest) (*AntivirusIcapTargetGetResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *AntivirusIcapTargetGetResponse
	)

	endpoint := "AntivirusAPIService.AntivirusTargetsIcapGet"
	localVarHeaderParams := make(map[string]string)

	localBasePath := a.client.cfg.ArrayURL

	nonAuthEndpoints := map[string]bool{
		"AuthorizationAPIService.Oauth210TokenPost": true,
		"AuthorizationAPIService.LoginPost":         true,
	}
	var authenticator Authenticator
	if !nonAuthEndpoints[endpoint] {
		authenticator = a.client.cfg.Authenticator
	} else {
		authenticator = nil
	}

	if authenticator != nil {
		if err := authenticator.SetAuthHeader(r.ctx, *a.client.AuthorizationAPI, localVarHeaderParams); err != nil {
			return localVarReturnValue, nil, err
		}
	}

	localVarPath := localBasePath + "/api/2.58/antivirus/targets/icap"

	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.allowErrors != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "allow_errors", r.allowErrors, "")
	}
	if r.contextNames != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "context_names", r.contextNames, "csv")
	}
	if r.continuationToken != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "continuation_token", r.continuationToken, "")
	}
	if r.filter != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "filter", r.filter, "")
	}
	if r.ids != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "ids", r.ids, "csv")
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "")
	}
	if r.names != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "names", r.names, "csv")
	}
	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "")
	}
	if r.sort != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sort", r.sort, "csv")
	}
	if r.totalItemCount != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "total_item_count", r.totalItemCount, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, http.CanonicalHeaderKey("Authorization"), r.authorization, "")
	}
	if r.xRequestID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, http.CanonicalHeaderKey("X-Request-ID"), r.xRequestID, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	ignoredEndpoints := map[string]bool{
		"AuthorizationAPIService.LogoutPost": true,
	}

	authStatusCodes := map[int]bool{
		401: true,
	}

	if authStatusCodes[localVarHTTPResponse.StatusCode] && !ignoredEndpoints[endpoint] && authenticator != nil {
		// Drain and close the first response body so its connection can be
		// reused; keep a buffered copy readable in case the retry fails and
		// this response is returned to the caller.
		firstRespBody, _ := io.ReadAll(localVarHTTPResponse.Body)
		localVarHTTPResponse.Body.Close()
		localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(firstRespBody))
		// retry with token refresh
		err = authenticator.RefreshAccessToken(r.ctx, *a.client.AuthorizationAPI)
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		// Update auth header
		if err := authenticator.SetAuthHeader(r.ctx, *a.client.AuthorizationAPI, localVarHeaderParams); err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		req, err = a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		localVarHTTPResponse, err = a.client.callAPI(req)
		if err != nil || localVarHTTPResponse == nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &ErrorResponse{
			StatusCode: localVarHTTPResponse.StatusCode,
			Headers:    localVarHTTPResponse.Header,
		}
		err = a.client.decode(&newErr, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, &GenericOpenAPIError{
				body:  localVarBody,
				error: localVarHTTPResponse.Status,
			}
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type APIAntivirusTargetsIcapPatchRequest struct {
	ctx           context.Context
	APIService    *AntivirusAPIService
	target        *AntivirusTargetPatch
	authorization *string
	xRequestID    *string
	contextNames  *[]string
	ids           *[]string
	names         *[]string
}

func (r APIAntivirusTargetsIcapPatchRequest) Target(target AntivirusTargetPatch) APIAntivirusTargetsIcapPatchRequest {
	r.target = &target
	return r
}

// Access token (in JWT format) required to use any API endpoint (except &#x60;/oauth2&#x60;, &#x60;/login&#x60;, and &#x60;/logout&#x60;)
func (r APIAntivirusTargetsIcapPatchRequest) Authorization(authorization string) APIAntivirusTargetsIcapPatchRequest {
	r.authorization = &authorization
	return r
}

// Supplied by client during request or generated by server.
func (r APIAntivirusTargetsIcapPatchRequest) XRequestID(xRequestID string) APIAntivirusTargetsIcapPatchRequest {
	r.xRequestID = &xRequestID
	return r
}

// Performs the operation on the context specified.  If specified, the context names must be an array of size 1, and the single element must be the name of an array in the same fleet or the name of the fleet itself. If not specified, the context will default to the array that received this request.  Other parameters provided with the request, such as names of volumes or snapshots, are resolved relative to the provided &#x60;context&#x60;.
func (r APIAntivirusTargetsIcapPatchRequest) ContextNames(contextNames []string) APIAntivirusTargetsIcapPatchRequest {
	r.contextNames = &contextNames
	return r
}

// A comma-separated list of unique resource IDs. At least one resource must match  each specified ID, otherwise an error is returned. This parameter is required   if ids or names is not provided, but it cannot be used together with name or names.
func (r APIAntivirusTargetsIcapPatchRequest) Ids(ids []string) APIAntivirusTargetsIcapPatchRequest {
	r.ids = &ids
	return r
}

// Performs the operation on the unique names specified. Enter multiple names in comma-separated format. For example, &#x60;name01,name02&#x60;.  If there is not at least one resource that matches each of the elements of &#x60;names&#x60;, then an error is returned, except when creating new resources.
func (r APIAntivirusTargetsIcapPatchRequest) Names(names []string) APIAntivirusTargetsIcapPatchRequest {
	r.names = &names
	return r
}

func (r APIAntivirusTargetsIcapPatchRequest) Execute() (*AntivirusIcapTargetResponse, *http.Response, error) {
	return r.APIService.AntivirusTargetsIcapPatchExecute(r)
}

/*
AntivirusTargetsIcapPatch Modify antivirus ICAP targets

Modifies one or more antivirus ICAP targets. The `names` parameter
is required. To rename a target, set the `name` parameter to the
new name.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return APIAntivirusTargetsIcapPatchRequest
*/
func (a *AntivirusAPIService) AntivirusTargetsIcapPatch(ctx context.Context) APIAntivirusTargetsIcapPatchRequest {
	return APIAntivirusTargetsIcapPatchRequest{
		APIService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return AntivirusIcapTargetResponse
func (a *AntivirusAPIService) AntivirusTargetsIcapPatchExecute(r APIAntivirusTargetsIcapPatchRequest) (*AntivirusIcapTargetResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPatch
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *AntivirusIcapTargetResponse
	)

	endpoint := "AntivirusAPIService.AntivirusTargetsIcapPatch"
	localVarHeaderParams := make(map[string]string)

	localBasePath := a.client.cfg.ArrayURL

	nonAuthEndpoints := map[string]bool{
		"AuthorizationAPIService.Oauth210TokenPost": true,
		"AuthorizationAPIService.LoginPost":         true,
	}
	var authenticator Authenticator
	if !nonAuthEndpoints[endpoint] {
		authenticator = a.client.cfg.Authenticator
	} else {
		authenticator = nil
	}

	if authenticator != nil {
		if err := authenticator.SetAuthHeader(r.ctx, *a.client.AuthorizationAPI, localVarHeaderParams); err != nil {
			return localVarReturnValue, nil, err
		}
	}

	localVarPath := localBasePath + "/api/2.58/antivirus/targets/icap"

	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.target == nil {
		return localVarReturnValue, nil, reportError("target is required and must be specified")
	}

	if r.contextNames != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "context_names", r.contextNames, "csv")
	}
	if r.ids != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "ids", r.ids, "csv")
	}
	if r.names != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "names", r.names, "csv")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, http.CanonicalHeaderKey("Authorization"), r.authorization, "")
	}
	if r.xRequestID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, http.CanonicalHeaderKey("X-Request-ID"), r.xRequestID, "")
	}
	// body params
	localVarPostBody = r.target
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	ignoredEndpoints := map[string]bool{
		"AuthorizationAPIService.LogoutPost": true,
	}

	authStatusCodes := map[int]bool{
		401: true,
	}

	if authStatusCodes[localVarHTTPResponse.StatusCode] && !ignoredEndpoints[endpoint] && authenticator != nil {
		// Drain and close the first response body so its connection can be
		// reused; keep a buffered copy readable in case the retry fails and
		// this response is returned to the caller.
		firstRespBody, _ := io.ReadAll(localVarHTTPResponse.Body)
		localVarHTTPResponse.Body.Close()
		localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(firstRespBody))
		// retry with token refresh
		err = authenticator.RefreshAccessToken(r.ctx, *a.client.AuthorizationAPI)
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		// Update auth header
		if err := authenticator.SetAuthHeader(r.ctx, *a.client.AuthorizationAPI, localVarHeaderParams); err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		req, err = a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		localVarHTTPResponse, err = a.client.callAPI(req)
		if err != nil || localVarHTTPResponse == nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &ErrorResponse{
			StatusCode: localVarHTTPResponse.StatusCode,
			Headers:    localVarHTTPResponse.Header,
		}
		err = a.client.decode(&newErr, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, &GenericOpenAPIError{
				body:  localVarBody,
				error: localVarHTTPResponse.Status,
			}
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type APIAntivirusTargetsIcapPostRequest struct {
	ctx           context.Context
	APIService    *AntivirusAPIService
	target        *AntivirusTargetPost
	authorization *string
	xRequestID    *string
	contextNames  *[]string
	names         *[]string
}

func (r APIAntivirusTargetsIcapPostRequest) Target(target AntivirusTargetPost) APIAntivirusTargetsIcapPostRequest {
	r.target = &target
	return r
}

// Access token (in JWT format) required to use any API endpoint (except &#x60;/oauth2&#x60;, &#x60;/login&#x60;, and &#x60;/logout&#x60;)
func (r APIAntivirusTargetsIcapPostRequest) Authorization(authorization string) APIAntivirusTargetsIcapPostRequest {
	r.authorization = &authorization
	return r
}

// Supplied by client during request or generated by server.
func (r APIAntivirusTargetsIcapPostRequest) XRequestID(xRequestID string) APIAntivirusTargetsIcapPostRequest {
	r.xRequestID = &xRequestID
	return r
}

// Performs the operation on the context specified.  If specified, the context names must be an array of size 1, and the single element must be the name of an array in the same fleet or the name of the fleet itself. If not specified, the context will default to the array that received this request.  Other parameters provided with the request, such as names of volumes or snapshots, are resolved relative to the provided &#x60;context&#x60;.
func (r APIAntivirusTargetsIcapPostRequest) ContextNames(contextNames []string) APIAntivirusTargetsIcapPostRequest {
	r.contextNames = &contextNames
	return r
}

// Performs the operation on the unique names specified. Enter multiple names in comma-separated format. For example, &#x60;name01,name02&#x60;.  If there is not at least one resource that matches each of the elements of &#x60;names&#x60;, then an error is returned, except when creating new resources.
func (r APIAntivirusTargetsIcapPostRequest) Names(names []string) APIAntivirusTargetsIcapPostRequest {
	r.names = &names
	return r
}

func (r APIAntivirusTargetsIcapPostRequest) Execute() (*AntivirusIcapTargetResponse, *http.Response, error) {
	return r.APIService.AntivirusTargetsIcapPostExecute(r)
}

/*
AntivirusTargetsIcapPost Create antivirus ICAP targets

Creates one or more antivirus ICAP targets.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return APIAntivirusTargetsIcapPostRequest
*/
func (a *AntivirusAPIService) AntivirusTargetsIcapPost(ctx context.Context) APIAntivirusTargetsIcapPostRequest {
	return APIAntivirusTargetsIcapPostRequest{
		APIService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return AntivirusIcapTargetResponse
func (a *AntivirusAPIService) AntivirusTargetsIcapPostExecute(r APIAntivirusTargetsIcapPostRequest) (*AntivirusIcapTargetResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *AntivirusIcapTargetResponse
	)

	endpoint := "AntivirusAPIService.AntivirusTargetsIcapPost"
	localVarHeaderParams := make(map[string]string)

	localBasePath := a.client.cfg.ArrayURL

	nonAuthEndpoints := map[string]bool{
		"AuthorizationAPIService.Oauth210TokenPost": true,
		"AuthorizationAPIService.LoginPost":         true,
	}
	var authenticator Authenticator
	if !nonAuthEndpoints[endpoint] {
		authenticator = a.client.cfg.Authenticator
	} else {
		authenticator = nil
	}

	if authenticator != nil {
		if err := authenticator.SetAuthHeader(r.ctx, *a.client.AuthorizationAPI, localVarHeaderParams); err != nil {
			return localVarReturnValue, nil, err
		}
	}

	localVarPath := localBasePath + "/api/2.58/antivirus/targets/icap"

	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.target == nil {
		return localVarReturnValue, nil, reportError("target is required and must be specified")
	}

	if r.contextNames != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "context_names", r.contextNames, "csv")
	}
	if r.names != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "names", r.names, "csv")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, http.CanonicalHeaderKey("Authorization"), r.authorization, "")
	}
	if r.xRequestID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, http.CanonicalHeaderKey("X-Request-ID"), r.xRequestID, "")
	}
	// body params
	localVarPostBody = r.target
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	ignoredEndpoints := map[string]bool{
		"AuthorizationAPIService.LogoutPost": true,
	}

	authStatusCodes := map[int]bool{
		401: true,
	}

	if authStatusCodes[localVarHTTPResponse.StatusCode] && !ignoredEndpoints[endpoint] && authenticator != nil {
		// Drain and close the first response body so its connection can be
		// reused; keep a buffered copy readable in case the retry fails and
		// this response is returned to the caller.
		firstRespBody, _ := io.ReadAll(localVarHTTPResponse.Body)
		localVarHTTPResponse.Body.Close()
		localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(firstRespBody))
		// retry with token refresh
		err = authenticator.RefreshAccessToken(r.ctx, *a.client.AuthorizationAPI)
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		// Update auth header
		if err := authenticator.SetAuthHeader(r.ctx, *a.client.AuthorizationAPI, localVarHeaderParams); err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		req, err = a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		localVarHTTPResponse, err = a.client.callAPI(req)
		if err != nil || localVarHTTPResponse == nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &ErrorResponse{
			StatusCode: localVarHTTPResponse.StatusCode,
			Headers:    localVarHTTPResponse.Header,
		}
		err = a.client.decode(&newErr, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, &GenericOpenAPIError{
				body:  localVarBody,
				error: localVarHTTPResponse.Status,
			}
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type APIAntivirusTargetsIcapScannersDeleteRequest struct {
	ctx                  context.Context
	APIService           *AntivirusAPIService
	authorization        *string
	xRequestID           *string
	allowNoActiveScanner *bool
	contextNames         *[]string
	ids                  *[]string
	names                *[]string
}

// Access token (in JWT format) required to use any API endpoint (except &#x60;/oauth2&#x60;, &#x60;/login&#x60;, and &#x60;/logout&#x60;)
func (r APIAntivirusTargetsIcapScannersDeleteRequest) Authorization(authorization string) APIAntivirusTargetsIcapScannersDeleteRequest {
	r.authorization = &authorization
	return r
}

// Supplied by client during request or generated by server.
func (r APIAntivirusTargetsIcapScannersDeleteRequest) XRequestID(xRequestID string) APIAntivirusTargetsIcapScannersDeleteRequest {
	r.xRequestID = &xRequestID
	return r
}

// Set to &#x60;true&#x60; to allow the operation to proceed even if it leaves the target with no active (enabled) scanners. Defaults to &#x60;false&#x60;.
func (r APIAntivirusTargetsIcapScannersDeleteRequest) AllowNoActiveScanner(allowNoActiveScanner bool) APIAntivirusTargetsIcapScannersDeleteRequest {
	r.allowNoActiveScanner = &allowNoActiveScanner
	return r
}

// Performs the operation on the context specified.  If specified, the context names must be an array of size 1, and the single element must be the name of an array in the same fleet or the name of the fleet itself. If not specified, the context will default to the array that received this request.  Other parameters provided with the request, such as names of volumes or snapshots, are resolved relative to the provided &#x60;context&#x60;.
func (r APIAntivirusTargetsIcapScannersDeleteRequest) ContextNames(contextNames []string) APIAntivirusTargetsIcapScannersDeleteRequest {
	r.contextNames = &contextNames
	return r
}

// A comma-separated list of unique resource IDs. At least one resource must match  each specified ID, otherwise an error is returned. This parameter is required   if ids or names is not provided, but it cannot be used together with name or names.
func (r APIAntivirusTargetsIcapScannersDeleteRequest) Ids(ids []string) APIAntivirusTargetsIcapScannersDeleteRequest {
	r.ids = &ids
	return r
}

// Performs the operation on the unique names specified. Enter multiple names in comma-separated format. For example, &#x60;name01,name02&#x60;.  If there is not at least one resource that matches each of the elements of &#x60;names&#x60;, then an error is returned, except when creating new resources.
func (r APIAntivirusTargetsIcapScannersDeleteRequest) Names(names []string) APIAntivirusTargetsIcapScannersDeleteRequest {
	r.names = &names
	return r
}

func (r APIAntivirusTargetsIcapScannersDeleteRequest) Execute() (*http.Response, error) {
	return r.APIService.AntivirusTargetsIcapScannersDeleteExecute(r)
}

/*
AntivirusTargetsIcapScannersDelete Delete antivirus ICAP scanners

Deletes one or more antivirus ICAP scanners. The `names` parameter
is required. Removing the last active scanner from a target may
cause an outage because unscanned files cannot be read. To override
this protection, set `allow_no_active_scanner=true`.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return APIAntivirusTargetsIcapScannersDeleteRequest
*/
func (a *AntivirusAPIService) AntivirusTargetsIcapScannersDelete(ctx context.Context) APIAntivirusTargetsIcapScannersDeleteRequest {
	return APIAntivirusTargetsIcapScannersDeleteRequest{
		APIService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
func (a *AntivirusAPIService) AntivirusTargetsIcapScannersDeleteExecute(r APIAntivirusTargetsIcapScannersDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	endpoint := "AntivirusAPIService.AntivirusTargetsIcapScannersDelete"
	localVarHeaderParams := make(map[string]string)

	localBasePath := a.client.cfg.ArrayURL

	nonAuthEndpoints := map[string]bool{
		"AuthorizationAPIService.Oauth210TokenPost": true,
		"AuthorizationAPIService.LoginPost":         true,
	}
	var authenticator Authenticator
	if !nonAuthEndpoints[endpoint] {
		authenticator = a.client.cfg.Authenticator
	} else {
		authenticator = nil
	}

	if authenticator != nil {
		if err := authenticator.SetAuthHeader(r.ctx, *a.client.AuthorizationAPI, localVarHeaderParams); err != nil {
			return nil, err
		}
	}

	localVarPath := localBasePath + "/api/2.58/antivirus/targets/icap/scanners"

	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.allowNoActiveScanner != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "allow_no_active_scanner", r.allowNoActiveScanner, "")
	}
	if r.contextNames != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "context_names", r.contextNames, "csv")
	}
	if r.ids != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "ids", r.ids, "csv")
	}
	if r.names != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "names", r.names, "csv")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, http.CanonicalHeaderKey("Authorization"), r.authorization, "")
	}
	if r.xRequestID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, http.CanonicalHeaderKey("X-Request-ID"), r.xRequestID, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	ignoredEndpoints := map[string]bool{
		"AuthorizationAPIService.LogoutPost": true,
	}

	authStatusCodes := map[int]bool{
		401: true,
	}

	if authStatusCodes[localVarHTTPResponse.StatusCode] && !ignoredEndpoints[endpoint] && authenticator != nil {
		// Drain and close the first response body so its connection can be
		// reused; keep a buffered copy readable in case the retry fails and
		// this response is returned to the caller.
		firstRespBody, _ := io.ReadAll(localVarHTTPResponse.Body)
		localVarHTTPResponse.Body.Close()
		localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(firstRespBody))
		// retry with token refresh
		err = authenticator.RefreshAccessToken(r.ctx, *a.client.AuthorizationAPI)
		if err != nil {
			return localVarHTTPResponse, err
		}
		// Update auth header
		if err := authenticator.SetAuthHeader(r.ctx, *a.client.AuthorizationAPI, localVarHeaderParams); err != nil {
			return localVarHTTPResponse, err
		}
		req, err = a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
		if err != nil {
			return localVarHTTPResponse, err
		}
		localVarHTTPResponse, err = a.client.callAPI(req)
		if err != nil || localVarHTTPResponse == nil {
			return localVarHTTPResponse, err
		}
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &ErrorResponse{
			StatusCode: localVarHTTPResponse.StatusCode,
			Headers:    localVarHTTPResponse.Header,
		}
		err = a.client.decode(&newErr, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
		if err != nil {
			return localVarHTTPResponse, &GenericOpenAPIError{
				body:  localVarBody,
				error: localVarHTTPResponse.Status,
			}
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type APIAntivirusTargetsIcapScannersGetRequest struct {
	ctx               context.Context
	APIService        *AntivirusAPIService
	authorization     *string
	xRequestID        *string
	allowErrors       *bool
	contextNames      *[]string
	continuationToken *string
	filter            *string
	ids               *[]string
	limit             *int32
	names             *[]string
	offset            *int32
	sort              *[]string
	totalItemCount    *bool
}

// Access token (in JWT format) required to use any API endpoint (except &#x60;/oauth2&#x60;, &#x60;/login&#x60;, and &#x60;/logout&#x60;)
func (r APIAntivirusTargetsIcapScannersGetRequest) Authorization(authorization string) APIAntivirusTargetsIcapScannersGetRequest {
	r.authorization = &authorization
	return r
}

// Supplied by client during request or generated by server.
func (r APIAntivirusTargetsIcapScannersGetRequest) XRequestID(xRequestID string) APIAntivirusTargetsIcapScannersGetRequest {
	r.xRequestID = &xRequestID
	return r
}

// If set to &#x60;true&#x60;, the API will allow the operation to continue even if there are errors. Any errors will be returned in the &#x60;errors&#x60; field of the response. If set to &#x60;false&#x60;, the operation will fail if there are any errors.
func (r APIAntivirusTargetsIcapScannersGetRequest) AllowErrors(allowErrors bool) APIAntivirusTargetsIcapScannersGetRequest {
	r.allowErrors = &allowErrors
	return r
}

// Performs the operation on the unique contexts specified.  If specified, each context name must be the name of an array in the same fleet or the name of the fleet itself.  If not specified, the context will default to the array that received this request.  Other parameters provided with the request, such as names of volumes or snapshots, are resolved relative to the provided &#x60;context&#x60;.  Enter multiple names in comma-separated format. For example, &#x60;name01,name02&#x60;.
func (r APIAntivirusTargetsIcapScannersGetRequest) ContextNames(contextNames []string) APIAntivirusTargetsIcapScannersGetRequest {
	r.contextNames = &contextNames
	return r
}

// A token used to retrieve the next page of data with some consistency guaranteed. The token is a Base64 encoded value. Set &#x60;continuation_token&#x60; to the system-generated token taken from the &#x60;x-next-token&#x60; header field of the response. A query has reached its last page when the response does not include a token. Pagination requires the &#x60;limit&#x60; and &#x60;continuation_token&#x60; query parameters.
func (r APIAntivirusTargetsIcapScannersGetRequest) ContinuationToken(continuationToken string) APIAntivirusTargetsIcapScannersGetRequest {
	r.continuationToken = &continuationToken
	return r
}

// Narrows down the results to only the response objects that satisfy the filter criteria.
func (r APIAntivirusTargetsIcapScannersGetRequest) Filter(filter string) APIAntivirusTargetsIcapScannersGetRequest {
	r.filter = &filter
	return r
}

// A comma-separated list of unique resource IDs. At least one resource must match  each specified ID, otherwise an error is returned. This parameter is required   if ids or names is not provided, but it cannot be used together with name or names.
func (r APIAntivirusTargetsIcapScannersGetRequest) Ids(ids []string) APIAntivirusTargetsIcapScannersGetRequest {
	r.ids = &ids
	return r
}

// Limits the size of the response to the specified number of objects on each page. To return the total number of resources, set &#x60;limit&#x3D;0&#x60;. The total number of resources is returned as a &#x60;total_item_count&#x60; value. If the page size requested is larger than the system maximum limit, the server returns the maximum limit, disregarding the requested page size.
func (r APIAntivirusTargetsIcapScannersGetRequest) Limit(limit int32) APIAntivirusTargetsIcapScannersGetRequest {
	r.limit = &limit
	return r
}

// Performs the operation on the unique names specified. Enter multiple names in comma-separated format. For example, &#x60;name01,name02&#x60;.  If there is not at least one resource that matches each of the elements of &#x60;names&#x60;, then an error is returned, except when creating new resources.
func (r APIAntivirusTargetsIcapScannersGetRequest) Names(names []string) APIAntivirusTargetsIcapScannersGetRequest {
	r.names = &names
	return r
}

// The starting position based on the results of the query in relation to the full set of response objects returned.
func (r APIAntivirusTargetsIcapScannersGetRequest) Offset(offset int32) APIAntivirusTargetsIcapScannersGetRequest {
	r.offset = &offset
	return r
}

// Sorts the response objects by the specified fields. Sorting can be applied to any field name  in the response, in ascending order by default, or in descending order by prefixing the  field name with a minus sign (-). Multiple fields can be specified as a comma-separated  list (e.g., sort volumes by size descending, then by name ascending). If sort is provided,  the response will not include a continuation_token.
func (r APIAntivirusTargetsIcapScannersGetRequest) Sort(sort []string) APIAntivirusTargetsIcapScannersGetRequest {
	r.sort = &sort
	return r
}

// If set to &#x60;true&#x60;, the &#x60;total_item_count&#x60; matching the specified query parameters is calculated and returned in the response. If set to &#x60;false&#x60;, the &#x60;total_item_count&#x60; is &#x60;null&#x60; in the response. This may speed up queries where the &#x60;total_item_count&#x60; is large. If not specified, defaults to &#x60;false&#x60;.
func (r APIAntivirusTargetsIcapScannersGetRequest) TotalItemCount(totalItemCount bool) APIAntivirusTargetsIcapScannersGetRequest {
	r.totalItemCount = &totalItemCount
	return r
}

func (r APIAntivirusTargetsIcapScannersGetRequest) Execute() (*AntivirusIcapScannerGetResponse, *http.Response, error) {
	return r.APIService.AntivirusTargetsIcapScannersGetExecute(r)
}

/*
AntivirusTargetsIcapScannersGet List antivirus ICAP scanners

Displays a list of antivirus ICAP scanners.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return APIAntivirusTargetsIcapScannersGetRequest
*/
func (a *AntivirusAPIService) AntivirusTargetsIcapScannersGet(ctx context.Context) APIAntivirusTargetsIcapScannersGetRequest {
	return APIAntivirusTargetsIcapScannersGetRequest{
		APIService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return AntivirusIcapScannerGetResponse
func (a *AntivirusAPIService) AntivirusTargetsIcapScannersGetExecute(r APIAntivirusTargetsIcapScannersGetRequest) (*AntivirusIcapScannerGetResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *AntivirusIcapScannerGetResponse
	)

	endpoint := "AntivirusAPIService.AntivirusTargetsIcapScannersGet"
	localVarHeaderParams := make(map[string]string)

	localBasePath := a.client.cfg.ArrayURL

	nonAuthEndpoints := map[string]bool{
		"AuthorizationAPIService.Oauth210TokenPost": true,
		"AuthorizationAPIService.LoginPost":         true,
	}
	var authenticator Authenticator
	if !nonAuthEndpoints[endpoint] {
		authenticator = a.client.cfg.Authenticator
	} else {
		authenticator = nil
	}

	if authenticator != nil {
		if err := authenticator.SetAuthHeader(r.ctx, *a.client.AuthorizationAPI, localVarHeaderParams); err != nil {
			return localVarReturnValue, nil, err
		}
	}

	localVarPath := localBasePath + "/api/2.58/antivirus/targets/icap/scanners"

	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.allowErrors != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "allow_errors", r.allowErrors, "")
	}
	if r.contextNames != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "context_names", r.contextNames, "csv")
	}
	if r.continuationToken != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "continuation_token", r.continuationToken, "")
	}
	if r.filter != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "filter", r.filter, "")
	}
	if r.ids != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "ids", r.ids, "csv")
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "")
	}
	if r.names != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "names", r.names, "csv")
	}
	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "")
	}
	if r.sort != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "sort", r.sort, "csv")
	}
	if r.totalItemCount != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "total_item_count", r.totalItemCount, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, http.CanonicalHeaderKey("Authorization"), r.authorization, "")
	}
	if r.xRequestID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, http.CanonicalHeaderKey("X-Request-ID"), r.xRequestID, "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	ignoredEndpoints := map[string]bool{
		"AuthorizationAPIService.LogoutPost": true,
	}

	authStatusCodes := map[int]bool{
		401: true,
	}

	if authStatusCodes[localVarHTTPResponse.StatusCode] && !ignoredEndpoints[endpoint] && authenticator != nil {
		// Drain and close the first response body so its connection can be
		// reused; keep a buffered copy readable in case the retry fails and
		// this response is returned to the caller.
		firstRespBody, _ := io.ReadAll(localVarHTTPResponse.Body)
		localVarHTTPResponse.Body.Close()
		localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(firstRespBody))
		// retry with token refresh
		err = authenticator.RefreshAccessToken(r.ctx, *a.client.AuthorizationAPI)
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		// Update auth header
		if err := authenticator.SetAuthHeader(r.ctx, *a.client.AuthorizationAPI, localVarHeaderParams); err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		req, err = a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		localVarHTTPResponse, err = a.client.callAPI(req)
		if err != nil || localVarHTTPResponse == nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &ErrorResponse{
			StatusCode: localVarHTTPResponse.StatusCode,
			Headers:    localVarHTTPResponse.Header,
		}
		err = a.client.decode(&newErr, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, &GenericOpenAPIError{
				body:  localVarBody,
				error: localVarHTTPResponse.Status,
			}
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type APIAntivirusTargetsIcapScannersPatchRequest struct {
	ctx                  context.Context
	APIService           *AntivirusAPIService
	scanner              *AntivirusIcapScannerPatch
	authorization        *string
	xRequestID           *string
	allowNoActiveScanner *bool
	contextNames         *[]string
	ids                  *[]string
	names                *[]string
}

func (r APIAntivirusTargetsIcapScannersPatchRequest) Scanner(scanner AntivirusIcapScannerPatch) APIAntivirusTargetsIcapScannersPatchRequest {
	r.scanner = &scanner
	return r
}

// Access token (in JWT format) required to use any API endpoint (except &#x60;/oauth2&#x60;, &#x60;/login&#x60;, and &#x60;/logout&#x60;)
func (r APIAntivirusTargetsIcapScannersPatchRequest) Authorization(authorization string) APIAntivirusTargetsIcapScannersPatchRequest {
	r.authorization = &authorization
	return r
}

// Supplied by client during request or generated by server.
func (r APIAntivirusTargetsIcapScannersPatchRequest) XRequestID(xRequestID string) APIAntivirusTargetsIcapScannersPatchRequest {
	r.xRequestID = &xRequestID
	return r
}

// Set to &#x60;true&#x60; to allow the operation to proceed even if it leaves the target with no active (enabled) scanners. Defaults to &#x60;false&#x60;.
func (r APIAntivirusTargetsIcapScannersPatchRequest) AllowNoActiveScanner(allowNoActiveScanner bool) APIAntivirusTargetsIcapScannersPatchRequest {
	r.allowNoActiveScanner = &allowNoActiveScanner
	return r
}

// Performs the operation on the context specified.  If specified, the context names must be an array of size 1, and the single element must be the name of an array in the same fleet or the name of the fleet itself. If not specified, the context will default to the array that received this request.  Other parameters provided with the request, such as names of volumes or snapshots, are resolved relative to the provided &#x60;context&#x60;.
func (r APIAntivirusTargetsIcapScannersPatchRequest) ContextNames(contextNames []string) APIAntivirusTargetsIcapScannersPatchRequest {
	r.contextNames = &contextNames
	return r
}

// A comma-separated list of unique resource IDs. At least one resource must match  each specified ID, otherwise an error is returned. This parameter is required   if ids or names is not provided, but it cannot be used together with name or names.
func (r APIAntivirusTargetsIcapScannersPatchRequest) Ids(ids []string) APIAntivirusTargetsIcapScannersPatchRequest {
	r.ids = &ids
	return r
}

// Performs the operation on the unique names specified. Enter multiple names in comma-separated format. For example, &#x60;name01,name02&#x60;.  If there is not at least one resource that matches each of the elements of &#x60;names&#x60;, then an error is returned, except when creating new resources.
func (r APIAntivirusTargetsIcapScannersPatchRequest) Names(names []string) APIAntivirusTargetsIcapScannersPatchRequest {
	r.names = &names
	return r
}

func (r APIAntivirusTargetsIcapScannersPatchRequest) Execute() (*AntivirusIcapScannerResponse, *http.Response, error) {
	return r.APIService.AntivirusTargetsIcapScannersPatchExecute(r)
}

/*
AntivirusTargetsIcapScannersPatch Modify antivirus ICAP scanners

Modifies one or more antivirus ICAP scanners. The `names` parameter
is required. Disabling the last active scanner in a target may
cause an outage because unscanned files cannot be read. To override
this protection, set `allow_no_active_scanner=true`.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return APIAntivirusTargetsIcapScannersPatchRequest
*/
func (a *AntivirusAPIService) AntivirusTargetsIcapScannersPatch(ctx context.Context) APIAntivirusTargetsIcapScannersPatchRequest {
	return APIAntivirusTargetsIcapScannersPatchRequest{
		APIService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return AntivirusIcapScannerResponse
func (a *AntivirusAPIService) AntivirusTargetsIcapScannersPatchExecute(r APIAntivirusTargetsIcapScannersPatchRequest) (*AntivirusIcapScannerResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPatch
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *AntivirusIcapScannerResponse
	)

	endpoint := "AntivirusAPIService.AntivirusTargetsIcapScannersPatch"
	localVarHeaderParams := make(map[string]string)

	localBasePath := a.client.cfg.ArrayURL

	nonAuthEndpoints := map[string]bool{
		"AuthorizationAPIService.Oauth210TokenPost": true,
		"AuthorizationAPIService.LoginPost":         true,
	}
	var authenticator Authenticator
	if !nonAuthEndpoints[endpoint] {
		authenticator = a.client.cfg.Authenticator
	} else {
		authenticator = nil
	}

	if authenticator != nil {
		if err := authenticator.SetAuthHeader(r.ctx, *a.client.AuthorizationAPI, localVarHeaderParams); err != nil {
			return localVarReturnValue, nil, err
		}
	}

	localVarPath := localBasePath + "/api/2.58/antivirus/targets/icap/scanners"

	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.scanner == nil {
		return localVarReturnValue, nil, reportError("scanner is required and must be specified")
	}

	if r.allowNoActiveScanner != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "allow_no_active_scanner", r.allowNoActiveScanner, "")
	}
	if r.contextNames != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "context_names", r.contextNames, "csv")
	}
	if r.ids != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "ids", r.ids, "csv")
	}
	if r.names != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "names", r.names, "csv")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, http.CanonicalHeaderKey("Authorization"), r.authorization, "")
	}
	if r.xRequestID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, http.CanonicalHeaderKey("X-Request-ID"), r.xRequestID, "")
	}
	// body params
	localVarPostBody = r.scanner
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	ignoredEndpoints := map[string]bool{
		"AuthorizationAPIService.LogoutPost": true,
	}

	authStatusCodes := map[int]bool{
		401: true,
	}

	if authStatusCodes[localVarHTTPResponse.StatusCode] && !ignoredEndpoints[endpoint] && authenticator != nil {
		// Drain and close the first response body so its connection can be
		// reused; keep a buffered copy readable in case the retry fails and
		// this response is returned to the caller.
		firstRespBody, _ := io.ReadAll(localVarHTTPResponse.Body)
		localVarHTTPResponse.Body.Close()
		localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(firstRespBody))
		// retry with token refresh
		err = authenticator.RefreshAccessToken(r.ctx, *a.client.AuthorizationAPI)
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		// Update auth header
		if err := authenticator.SetAuthHeader(r.ctx, *a.client.AuthorizationAPI, localVarHeaderParams); err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		req, err = a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		localVarHTTPResponse, err = a.client.callAPI(req)
		if err != nil || localVarHTTPResponse == nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &ErrorResponse{
			StatusCode: localVarHTTPResponse.StatusCode,
			Headers:    localVarHTTPResponse.Header,
		}
		err = a.client.decode(&newErr, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, &GenericOpenAPIError{
				body:  localVarBody,
				error: localVarHTTPResponse.Status,
			}
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type APIAntivirusTargetsIcapScannersPostRequest struct {
	ctx           context.Context
	APIService    *AntivirusAPIService
	scanner       *AntivirusIcapScannerPost
	authorization *string
	xRequestID    *string
	contextNames  *[]string
	targetIds     *[]string
	targetNames   *[]string
}

func (r APIAntivirusTargetsIcapScannersPostRequest) Scanner(scanner AntivirusIcapScannerPost) APIAntivirusTargetsIcapScannersPostRequest {
	r.scanner = &scanner
	return r
}

// Access token (in JWT format) required to use any API endpoint (except &#x60;/oauth2&#x60;, &#x60;/login&#x60;, and &#x60;/logout&#x60;)
func (r APIAntivirusTargetsIcapScannersPostRequest) Authorization(authorization string) APIAntivirusTargetsIcapScannersPostRequest {
	r.authorization = &authorization
	return r
}

// Supplied by client during request or generated by server.
func (r APIAntivirusTargetsIcapScannersPostRequest) XRequestID(xRequestID string) APIAntivirusTargetsIcapScannersPostRequest {
	r.xRequestID = &xRequestID
	return r
}

// Performs the operation on the context specified.  If specified, the context names must be an array of size 1, and the single element must be the name of an array in the same fleet or the name of the fleet itself. If not specified, the context will default to the array that received this request.  Other parameters provided with the request, such as names of volumes or snapshots, are resolved relative to the provided &#x60;context&#x60;.
func (r APIAntivirusTargetsIcapScannersPostRequest) ContextNames(contextNames []string) APIAntivirusTargetsIcapScannersPostRequest {
	r.contextNames = &contextNames
	return r
}

// Performs the operation on the specified unique target IDs. Enter multiple target IDs in comma-separated format. Either the &#x60;target_ids&#x60; or &#x60;target_names&#x60; parameter is required, but they cannot be used together.
func (r APIAntivirusTargetsIcapScannersPostRequest) TargetIds(targetIds []string) APIAntivirusTargetsIcapScannersPostRequest {
	r.targetIds = &targetIds
	return r
}

// Performs the operation on the specified target names. Enter multiple target names in comma-separated format, for example, &#x60;name01,name02&#x60;.
func (r APIAntivirusTargetsIcapScannersPostRequest) TargetNames(targetNames []string) APIAntivirusTargetsIcapScannersPostRequest {
	r.targetNames = &targetNames
	return r
}

func (r APIAntivirusTargetsIcapScannersPostRequest) Execute() (*AntivirusIcapScannerResponse, *http.Response, error) {
	return r.APIService.AntivirusTargetsIcapScannersPostExecute(r)
}

/*
AntivirusTargetsIcapScannersPost Create antivirus ICAP scanners

Creates one or more antivirus ICAP scanners within a target. Either
the `target_ids` or `target_names` parameter is required to specify
the parent target, but they cannot be used together. Scanner names
are system-generated.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return APIAntivirusTargetsIcapScannersPostRequest
*/
func (a *AntivirusAPIService) AntivirusTargetsIcapScannersPost(ctx context.Context) APIAntivirusTargetsIcapScannersPostRequest {
	return APIAntivirusTargetsIcapScannersPostRequest{
		APIService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return AntivirusIcapScannerResponse
func (a *AntivirusAPIService) AntivirusTargetsIcapScannersPostExecute(r APIAntivirusTargetsIcapScannersPostRequest) (*AntivirusIcapScannerResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *AntivirusIcapScannerResponse
	)

	endpoint := "AntivirusAPIService.AntivirusTargetsIcapScannersPost"
	localVarHeaderParams := make(map[string]string)

	localBasePath := a.client.cfg.ArrayURL

	nonAuthEndpoints := map[string]bool{
		"AuthorizationAPIService.Oauth210TokenPost": true,
		"AuthorizationAPIService.LoginPost":         true,
	}
	var authenticator Authenticator
	if !nonAuthEndpoints[endpoint] {
		authenticator = a.client.cfg.Authenticator
	} else {
		authenticator = nil
	}

	if authenticator != nil {
		if err := authenticator.SetAuthHeader(r.ctx, *a.client.AuthorizationAPI, localVarHeaderParams); err != nil {
			return localVarReturnValue, nil, err
		}
	}

	localVarPath := localBasePath + "/api/2.58/antivirus/targets/icap/scanners"

	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.scanner == nil {
		return localVarReturnValue, nil, reportError("scanner is required and must be specified")
	}

	if r.contextNames != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "context_names", r.contextNames, "csv")
	}
	if r.targetIds != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "target_ids", r.targetIds, "csv")
	}
	if r.targetNames != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "target_names", r.targetNames, "csv")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, http.CanonicalHeaderKey("Authorization"), r.authorization, "")
	}
	if r.xRequestID != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, http.CanonicalHeaderKey("X-Request-ID"), r.xRequestID, "")
	}
	// body params
	localVarPostBody = r.scanner
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	ignoredEndpoints := map[string]bool{
		"AuthorizationAPIService.LogoutPost": true,
	}

	authStatusCodes := map[int]bool{
		401: true,
	}

	if authStatusCodes[localVarHTTPResponse.StatusCode] && !ignoredEndpoints[endpoint] && authenticator != nil {
		// Drain and close the first response body so its connection can be
		// reused; keep a buffered copy readable in case the retry fails and
		// this response is returned to the caller.
		firstRespBody, _ := io.ReadAll(localVarHTTPResponse.Body)
		localVarHTTPResponse.Body.Close()
		localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(firstRespBody))
		// retry with token refresh
		err = authenticator.RefreshAccessToken(r.ctx, *a.client.AuthorizationAPI)
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		// Update auth header
		if err := authenticator.SetAuthHeader(r.ctx, *a.client.AuthorizationAPI, localVarHeaderParams); err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		req, err = a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
		localVarHTTPResponse, err = a.client.callAPI(req)
		if err != nil || localVarHTTPResponse == nil {
			return localVarReturnValue, localVarHTTPResponse, err
		}
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &ErrorResponse{
			StatusCode: localVarHTTPResponse.StatusCode,
			Headers:    localVarHTTPResponse.Header,
		}
		err = a.client.decode(&newErr, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
		if err != nil {
			return localVarReturnValue, localVarHTTPResponse, &GenericOpenAPIError{
				body:  localVarBody,
				error: localVarHTTPResponse.Status,
			}
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
