/*
FlashArray REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.54
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the CloudConfigPatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudConfigPatch{}

// CloudConfigPatch struct for CloudConfigPatch
type CloudConfigPatch struct {
	// The requested configuration of the automatic capacity upgrade.
	AutomaticCapacityUpgrade *CloudConfigAutomaticCapacityUpgradePatch `json:"automatic_capacity_upgrade,omitempty"`
	// The requested model configuration of the CBS array.
	Model *CloudConfigModelPatch `json:"model,omitempty"`
}

// NewCloudConfigPatch instantiates a new CloudConfigPatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudConfigPatch() *CloudConfigPatch {
	this := CloudConfigPatch{}
	return &this
}

// NewCloudConfigPatchWithDefaults instantiates a new CloudConfigPatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudConfigPatchWithDefaults() *CloudConfigPatch {
	this := CloudConfigPatch{}
	return &this
}

// GetAutomaticCapacityUpgrade returns the AutomaticCapacityUpgrade field value if set, zero value otherwise.
func (o *CloudConfigPatch) GetAutomaticCapacityUpgrade() CloudConfigAutomaticCapacityUpgradePatch {
	if o == nil || IsNil(o.AutomaticCapacityUpgrade) {
		var ret CloudConfigAutomaticCapacityUpgradePatch
		return ret
	}
	return *o.AutomaticCapacityUpgrade
}

// GetAutomaticCapacityUpgradeOk returns a tuple with the AutomaticCapacityUpgrade field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudConfigPatch) GetAutomaticCapacityUpgradeOk() (*CloudConfigAutomaticCapacityUpgradePatch, bool) {
	if o == nil || IsNil(o.AutomaticCapacityUpgrade) {
		return nil, false
	}
	return o.AutomaticCapacityUpgrade, true
}

// HasAutomaticCapacityUpgrade returns a boolean if a field has been set.
func (o *CloudConfigPatch) HasAutomaticCapacityUpgrade() bool {
	if o != nil && !IsNil(o.AutomaticCapacityUpgrade) {
		return true
	}

	return false
}

// SetAutomaticCapacityUpgrade gets a reference to the given CloudConfigAutomaticCapacityUpgradePatch and assigns it to the AutomaticCapacityUpgrade field.
func (o *CloudConfigPatch) SetAutomaticCapacityUpgrade(v CloudConfigAutomaticCapacityUpgradePatch) {
	o.AutomaticCapacityUpgrade = &v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *CloudConfigPatch) GetModel() CloudConfigModelPatch {
	if o == nil || IsNil(o.Model) {
		var ret CloudConfigModelPatch
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CloudConfigPatch) GetModelOk() (*CloudConfigModelPatch, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *CloudConfigPatch) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given CloudConfigModelPatch and assigns it to the Model field.
func (o *CloudConfigPatch) SetModel(v CloudConfigModelPatch) {
	o.Model = &v
}

func (o CloudConfigPatch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CloudConfigPatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AutomaticCapacityUpgrade) {
		toSerialize["automatic_capacity_upgrade"] = o.AutomaticCapacityUpgrade
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	return toSerialize, nil
}

type NullableCloudConfigPatch struct {
	value *CloudConfigPatch
	isSet bool
}

func (v NullableCloudConfigPatch) Get() *CloudConfigPatch {
	return v.value
}

func (v *NullableCloudConfigPatch) Set(val *CloudConfigPatch) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudConfigPatch) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudConfigPatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudConfigPatch(val *CloudConfigPatch) *NullableCloudConfigPatch {
	return &NullableCloudConfigPatch{value: val, isSet: true}
}

func (v NullableCloudConfigPatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudConfigPatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
