/*
FlashArray REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.58
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the AntivirusIcapScannerBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AntivirusIcapScannerBase{}

// AntivirusIcapScannerBase struct for AntivirusIcapScannerBase
type AntivirusIcapScannerBase struct {
	// The CA certificate used to verify the ICAP scanner's identity when TLS is enabled. If set for the `icap://` protocol, it uses the RFC-defined ICAP Upgrade method. Required for the `icaps://` protocol.
	CaCertificate *ReferenceWithFixedType `json:"ca_certificate,omitempty"`
	// If set to `true`, the ICAP scanner is enabled. If set to `false`, the scanner is disabled.
	Enabled *bool `json:"enabled,omitempty"`
	// The maximum number of parallel connections that the array establishes towards the ICAP scanner. Defaults to `1` if not specified.
	MaxConnections *int32 `json:"max_connections,omitempty"`
	// The source network interface used by the array to connect to this ICAP scanner. The list must contain exactly one item.
	Sources []ReferenceNoIdWithType `json:"sources,omitempty"`
	// The URI of the ICAP scanner, in the format `icap[s]://<hostname>[:<port>][/<service>]`. If the port is not specified, it defaults to `1344` for `icap://` and `11344` for `icaps://`. If specified without a protocol, `icap://` is assumed.
	Uri *string `json:"uri,omitempty"`
}

// NewAntivirusIcapScannerBase instantiates a new AntivirusIcapScannerBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAntivirusIcapScannerBase() *AntivirusIcapScannerBase {
	this := AntivirusIcapScannerBase{}
	var maxConnections int32 = 1
	this.MaxConnections = &maxConnections
	return &this
}

// NewAntivirusIcapScannerBaseWithDefaults instantiates a new AntivirusIcapScannerBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAntivirusIcapScannerBaseWithDefaults() *AntivirusIcapScannerBase {
	this := AntivirusIcapScannerBase{}
	var maxConnections int32 = 1
	this.MaxConnections = &maxConnections
	return &this
}

// GetCaCertificate returns the CaCertificate field value if set, zero value otherwise.
func (o *AntivirusIcapScannerBase) GetCaCertificate() ReferenceWithFixedType {
	if o == nil || IsNil(o.CaCertificate) {
		var ret ReferenceWithFixedType
		return ret
	}
	return *o.CaCertificate
}

// GetCaCertificateOk returns a tuple with the CaCertificate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AntivirusIcapScannerBase) GetCaCertificateOk() (*ReferenceWithFixedType, bool) {
	if o == nil || IsNil(o.CaCertificate) {
		return nil, false
	}
	return o.CaCertificate, true
}

// HasCaCertificate returns a boolean if a field has been set.
func (o *AntivirusIcapScannerBase) HasCaCertificate() bool {
	if o != nil && !IsNil(o.CaCertificate) {
		return true
	}

	return false
}

// SetCaCertificate gets a reference to the given ReferenceWithFixedType and assigns it to the CaCertificate field.
func (o *AntivirusIcapScannerBase) SetCaCertificate(v ReferenceWithFixedType) {
	o.CaCertificate = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *AntivirusIcapScannerBase) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AntivirusIcapScannerBase) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *AntivirusIcapScannerBase) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *AntivirusIcapScannerBase) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetMaxConnections returns the MaxConnections field value if set, zero value otherwise.
func (o *AntivirusIcapScannerBase) GetMaxConnections() int32 {
	if o == nil || IsNil(o.MaxConnections) {
		var ret int32
		return ret
	}
	return *o.MaxConnections
}

// GetMaxConnectionsOk returns a tuple with the MaxConnections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AntivirusIcapScannerBase) GetMaxConnectionsOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxConnections) {
		return nil, false
	}
	return o.MaxConnections, true
}

// HasMaxConnections returns a boolean if a field has been set.
func (o *AntivirusIcapScannerBase) HasMaxConnections() bool {
	if o != nil && !IsNil(o.MaxConnections) {
		return true
	}

	return false
}

// SetMaxConnections gets a reference to the given int32 and assigns it to the MaxConnections field.
func (o *AntivirusIcapScannerBase) SetMaxConnections(v int32) {
	o.MaxConnections = &v
}

// GetSources returns the Sources field value if set, zero value otherwise.
func (o *AntivirusIcapScannerBase) GetSources() []ReferenceNoIdWithType {
	if o == nil || IsNil(o.Sources) {
		var ret []ReferenceNoIdWithType
		return ret
	}
	return o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AntivirusIcapScannerBase) GetSourcesOk() ([]ReferenceNoIdWithType, bool) {
	if o == nil || IsNil(o.Sources) {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *AntivirusIcapScannerBase) HasSources() bool {
	if o != nil && !IsNil(o.Sources) {
		return true
	}

	return false
}

// SetSources gets a reference to the given []ReferenceNoIdWithType and assigns it to the Sources field.
func (o *AntivirusIcapScannerBase) SetSources(v []ReferenceNoIdWithType) {
	o.Sources = v
}

// GetUri returns the Uri field value if set, zero value otherwise.
func (o *AntivirusIcapScannerBase) GetUri() string {
	if o == nil || IsNil(o.Uri) {
		var ret string
		return ret
	}
	return *o.Uri
}

// GetUriOk returns a tuple with the Uri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AntivirusIcapScannerBase) GetUriOk() (*string, bool) {
	if o == nil || IsNil(o.Uri) {
		return nil, false
	}
	return o.Uri, true
}

// HasUri returns a boolean if a field has been set.
func (o *AntivirusIcapScannerBase) HasUri() bool {
	if o != nil && !IsNil(o.Uri) {
		return true
	}

	return false
}

// SetUri gets a reference to the given string and assigns it to the Uri field.
func (o *AntivirusIcapScannerBase) SetUri(v string) {
	o.Uri = &v
}

func (o AntivirusIcapScannerBase) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AntivirusIcapScannerBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CaCertificate) {
		toSerialize["ca_certificate"] = o.CaCertificate
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.MaxConnections) {
		toSerialize["max_connections"] = o.MaxConnections
	}
	if !IsNil(o.Sources) {
		toSerialize["sources"] = o.Sources
	}
	if !IsNil(o.Uri) {
		toSerialize["uri"] = o.Uri
	}
	return toSerialize, nil
}

type NullableAntivirusIcapScannerBase struct {
	value *AntivirusIcapScannerBase
	isSet bool
}

func (v NullableAntivirusIcapScannerBase) Get() *AntivirusIcapScannerBase {
	return v.value
}

func (v *NullableAntivirusIcapScannerBase) Set(val *AntivirusIcapScannerBase) {
	v.value = val
	v.isSet = true
}

func (v NullableAntivirusIcapScannerBase) IsSet() bool {
	return v.isSet
}

func (v *NullableAntivirusIcapScannerBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAntivirusIcapScannerBase(val *AntivirusIcapScannerBase) *NullableAntivirusIcapScannerBase {
	return &NullableAntivirusIcapScannerBase{value: val, isSet: true}
}

func (v NullableAntivirusIcapScannerBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAntivirusIcapScannerBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
