/*
FlashArray REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.54
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the KmipResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KmipResponse{}

// KmipResponse struct for KmipResponse
type KmipResponse struct {
	Items []Kmip `json:"items,omitempty"`
}

// NewKmipResponse instantiates a new KmipResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKmipResponse() *KmipResponse {
	this := KmipResponse{}
	return &this
}

// NewKmipResponseWithDefaults instantiates a new KmipResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKmipResponseWithDefaults() *KmipResponse {
	this := KmipResponse{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *KmipResponse) GetItems() []Kmip {
	if o == nil || IsNil(o.Items) {
		var ret []Kmip
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KmipResponse) GetItemsOk() ([]Kmip, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *KmipResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Kmip and assigns it to the Items field.
func (o *KmipResponse) SetItems(v []Kmip) {
	o.Items = v
}

func (o KmipResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KmipResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableKmipResponse struct {
	value *KmipResponse
	isSet bool
}

func (v NullableKmipResponse) Get() *KmipResponse {
	return v.value
}

func (v *NullableKmipResponse) Set(val *KmipResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableKmipResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableKmipResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKmipResponse(val *KmipResponse) *NullableKmipResponse {
	return &NullableKmipResponse{value: val, isSet: true}
}

func (v NullableKmipResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKmipResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
