/*
FlashArray REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.58
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the PolicyRuleAntivirus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyRuleAntivirus{}

// PolicyRuleAntivirus struct for PolicyRuleAntivirus
type PolicyRuleAntivirus struct {
	// The context in which the operation was performed.  Valid values include a reference to any array which is a member of the same fleet or to the fleet itself.  Other parameters provided with the request, such as names of volumes or snapshots, are resolved relative to the provided `context`.
	Context *FixedReferenceWithType `json:"context,omitempty"`
	// Returns a value of `true` if the pod containing the antivirus policy rule has been destroyed and is pending eradication. The `time_remaining` value displays the amount of time left until the destroyed policy is permanently eradicated. Once the `time_remaining` period has elapsed, the antivirus policy rule is permanently eradicated and can no longer be recovered.
	Destroyed *bool `json:"destroyed,omitempty"`
	// Specifies whether the rule is an `include` or `exclude` rule. Valid values are `include` and `exclude`. An `include` rule means that files matching the pattern are scanned. An `exclude` rule means that files matching the pattern are skipped from scanning.
	Effect *string `json:"effect,omitempty"`
	// Specifies whether the rule is enabled. If not specified, it defaults to `true`.
	Enabled *bool `json:"enabled,omitempty"`
	// Specifies the time interval, in milliseconds, following the last scan after which a rescan will be automatically initiated. If not specified or equal to `0`, a forced rescan will not be initiated. Valid values are `0`, `86400000`, and any multiple of `86400000` between `86400000` and `14515200000` (up to 24 weeks). This is only applicable to `include` rules.
	ForceRescanAfter *int64 `json:"force_rescan_after,omitempty"`
	// Specifies the maximum size, in bytes, of files that are scanned by the antivirus. Valid values are between `1048576` and `2147483648` (1 MB to 2 GB). If not specified, it defaults to `209715200` (200 MB). This is only applicable to `include` rules.
	MaxSize *int64 `json:"max_size,omitempty"`
	// The name of this rule. The name is automatically generated by the system.
	Name *string `json:"name,omitempty"`
	// Specifies the action to take when an infected file is found. Valid values are `restrict` and `quarantine`. The `restrict` action means that the infected file remains at its location but cannot be opened, read, copied, or moved. The `quarantine` action means that an infected file is moved to a quarantine folder. This is only applicable to `include` rules.
	OnInfectedAction *string `json:"on_infected_action,omitempty"`
	// Specifies the action to take when the antivirus scan of a file fails. Valid values are `deny` and `allow`. If set to `deny`, access to the file is denied when scanning fails. If set to `allow`, the file is accessible even if scanning fails. If not specified, it defaults to `deny`. This is only applicable to `include` rules.
	OnScanFailure *string `json:"on_scan_failure,omitempty"`
	// Specifies the path prefix for files that the rule applies to. The path prefix is relative to the managed directory that the policy is attached to. It must start with `/` and end with `/_**_/`. No wildcards are allowed in the middle of the path. If not specified, it defaults to `/_**_/`, which matches all paths under the attachment point.
	PathPrefix *string `json:"path_prefix,omitempty"`
	// A list of matching patterns. The interpretation depends on the `rule_class`. For the `extension` class, each item must be `*` (match all), an empty string (match files without an extension), or start with `.` (for example, `.exe` or `.tar.*`). For the `filename` class, each item is a filename wildcard (for example, `tmp*.exe` or `*.doc*`). If `*` is present, it must be the only item. If not specified, it defaults to `[\"*\"]`.
	Patterns []string `json:"patterns,omitempty"`
	// The policy to which this rule belongs.
	Policy *FixedReferenceWithType `json:"policy,omitempty"`
	// Specifies the class of the rule, which determines how the `patterns` are interpreted. Valid values are `extension` and `filename`. The `extension` class matches file extensions. The `filename` class matches full filenames using wildcards. If not specified, it defaults to `extension`.
	RuleClass *string `json:"rule_class,omitempty"`
	// The amount of time left, in milliseconds, until the destroyed antivirus policy rule is permanently eradicated.
	TimeRemaining *int64 `json:"time_remaining,omitempty"`
}

// NewPolicyRuleAntivirus instantiates a new PolicyRuleAntivirus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyRuleAntivirus() *PolicyRuleAntivirus {
	this := PolicyRuleAntivirus{}
	return &this
}

// NewPolicyRuleAntivirusWithDefaults instantiates a new PolicyRuleAntivirus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyRuleAntivirusWithDefaults() *PolicyRuleAntivirus {
	this := PolicyRuleAntivirus{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *PolicyRuleAntivirus) GetContext() FixedReferenceWithType {
	if o == nil || IsNil(o.Context) {
		var ret FixedReferenceWithType
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyRuleAntivirus) GetContextOk() (*FixedReferenceWithType, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *PolicyRuleAntivirus) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given FixedReferenceWithType and assigns it to the Context field.
func (o *PolicyRuleAntivirus) SetContext(v FixedReferenceWithType) {
	o.Context = &v
}

// GetDestroyed returns the Destroyed field value if set, zero value otherwise.
func (o *PolicyRuleAntivirus) GetDestroyed() bool {
	if o == nil || IsNil(o.Destroyed) {
		var ret bool
		return ret
	}
	return *o.Destroyed
}

// GetDestroyedOk returns a tuple with the Destroyed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyRuleAntivirus) GetDestroyedOk() (*bool, bool) {
	if o == nil || IsNil(o.Destroyed) {
		return nil, false
	}
	return o.Destroyed, true
}

// HasDestroyed returns a boolean if a field has been set.
func (o *PolicyRuleAntivirus) HasDestroyed() bool {
	if o != nil && !IsNil(o.Destroyed) {
		return true
	}

	return false
}

// SetDestroyed gets a reference to the given bool and assigns it to the Destroyed field.
func (o *PolicyRuleAntivirus) SetDestroyed(v bool) {
	o.Destroyed = &v
}

// GetEffect returns the Effect field value if set, zero value otherwise.
func (o *PolicyRuleAntivirus) GetEffect() string {
	if o == nil || IsNil(o.Effect) {
		var ret string
		return ret
	}
	return *o.Effect
}

// GetEffectOk returns a tuple with the Effect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyRuleAntivirus) GetEffectOk() (*string, bool) {
	if o == nil || IsNil(o.Effect) {
		return nil, false
	}
	return o.Effect, true
}

// HasEffect returns a boolean if a field has been set.
func (o *PolicyRuleAntivirus) HasEffect() bool {
	if o != nil && !IsNil(o.Effect) {
		return true
	}

	return false
}

// SetEffect gets a reference to the given string and assigns it to the Effect field.
func (o *PolicyRuleAntivirus) SetEffect(v string) {
	o.Effect = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *PolicyRuleAntivirus) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyRuleAntivirus) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *PolicyRuleAntivirus) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *PolicyRuleAntivirus) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetForceRescanAfter returns the ForceRescanAfter field value if set, zero value otherwise.
func (o *PolicyRuleAntivirus) GetForceRescanAfter() int64 {
	if o == nil || IsNil(o.ForceRescanAfter) {
		var ret int64
		return ret
	}
	return *o.ForceRescanAfter
}

// GetForceRescanAfterOk returns a tuple with the ForceRescanAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyRuleAntivirus) GetForceRescanAfterOk() (*int64, bool) {
	if o == nil || IsNil(o.ForceRescanAfter) {
		return nil, false
	}
	return o.ForceRescanAfter, true
}

// HasForceRescanAfter returns a boolean if a field has been set.
func (o *PolicyRuleAntivirus) HasForceRescanAfter() bool {
	if o != nil && !IsNil(o.ForceRescanAfter) {
		return true
	}

	return false
}

// SetForceRescanAfter gets a reference to the given int64 and assigns it to the ForceRescanAfter field.
func (o *PolicyRuleAntivirus) SetForceRescanAfter(v int64) {
	o.ForceRescanAfter = &v
}

// GetMaxSize returns the MaxSize field value if set, zero value otherwise.
func (o *PolicyRuleAntivirus) GetMaxSize() int64 {
	if o == nil || IsNil(o.MaxSize) {
		var ret int64
		return ret
	}
	return *o.MaxSize
}

// GetMaxSizeOk returns a tuple with the MaxSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyRuleAntivirus) GetMaxSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.MaxSize) {
		return nil, false
	}
	return o.MaxSize, true
}

// HasMaxSize returns a boolean if a field has been set.
func (o *PolicyRuleAntivirus) HasMaxSize() bool {
	if o != nil && !IsNil(o.MaxSize) {
		return true
	}

	return false
}

// SetMaxSize gets a reference to the given int64 and assigns it to the MaxSize field.
func (o *PolicyRuleAntivirus) SetMaxSize(v int64) {
	o.MaxSize = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PolicyRuleAntivirus) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyRuleAntivirus) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PolicyRuleAntivirus) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PolicyRuleAntivirus) SetName(v string) {
	o.Name = &v
}

// GetOnInfectedAction returns the OnInfectedAction field value if set, zero value otherwise.
func (o *PolicyRuleAntivirus) GetOnInfectedAction() string {
	if o == nil || IsNil(o.OnInfectedAction) {
		var ret string
		return ret
	}
	return *o.OnInfectedAction
}

// GetOnInfectedActionOk returns a tuple with the OnInfectedAction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyRuleAntivirus) GetOnInfectedActionOk() (*string, bool) {
	if o == nil || IsNil(o.OnInfectedAction) {
		return nil, false
	}
	return o.OnInfectedAction, true
}

// HasOnInfectedAction returns a boolean if a field has been set.
func (o *PolicyRuleAntivirus) HasOnInfectedAction() bool {
	if o != nil && !IsNil(o.OnInfectedAction) {
		return true
	}

	return false
}

// SetOnInfectedAction gets a reference to the given string and assigns it to the OnInfectedAction field.
func (o *PolicyRuleAntivirus) SetOnInfectedAction(v string) {
	o.OnInfectedAction = &v
}

// GetOnScanFailure returns the OnScanFailure field value if set, zero value otherwise.
func (o *PolicyRuleAntivirus) GetOnScanFailure() string {
	if o == nil || IsNil(o.OnScanFailure) {
		var ret string
		return ret
	}
	return *o.OnScanFailure
}

// GetOnScanFailureOk returns a tuple with the OnScanFailure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyRuleAntivirus) GetOnScanFailureOk() (*string, bool) {
	if o == nil || IsNil(o.OnScanFailure) {
		return nil, false
	}
	return o.OnScanFailure, true
}

// HasOnScanFailure returns a boolean if a field has been set.
func (o *PolicyRuleAntivirus) HasOnScanFailure() bool {
	if o != nil && !IsNil(o.OnScanFailure) {
		return true
	}

	return false
}

// SetOnScanFailure gets a reference to the given string and assigns it to the OnScanFailure field.
func (o *PolicyRuleAntivirus) SetOnScanFailure(v string) {
	o.OnScanFailure = &v
}

// GetPathPrefix returns the PathPrefix field value if set, zero value otherwise.
func (o *PolicyRuleAntivirus) GetPathPrefix() string {
	if o == nil || IsNil(o.PathPrefix) {
		var ret string
		return ret
	}
	return *o.PathPrefix
}

// GetPathPrefixOk returns a tuple with the PathPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyRuleAntivirus) GetPathPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.PathPrefix) {
		return nil, false
	}
	return o.PathPrefix, true
}

// HasPathPrefix returns a boolean if a field has been set.
func (o *PolicyRuleAntivirus) HasPathPrefix() bool {
	if o != nil && !IsNil(o.PathPrefix) {
		return true
	}

	return false
}

// SetPathPrefix gets a reference to the given string and assigns it to the PathPrefix field.
func (o *PolicyRuleAntivirus) SetPathPrefix(v string) {
	o.PathPrefix = &v
}

// GetPatterns returns the Patterns field value if set, zero value otherwise.
func (o *PolicyRuleAntivirus) GetPatterns() []string {
	if o == nil || IsNil(o.Patterns) {
		var ret []string
		return ret
	}
	return o.Patterns
}

// GetPatternsOk returns a tuple with the Patterns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyRuleAntivirus) GetPatternsOk() ([]string, bool) {
	if o == nil || IsNil(o.Patterns) {
		return nil, false
	}
	return o.Patterns, true
}

// HasPatterns returns a boolean if a field has been set.
func (o *PolicyRuleAntivirus) HasPatterns() bool {
	if o != nil && !IsNil(o.Patterns) {
		return true
	}

	return false
}

// SetPatterns gets a reference to the given []string and assigns it to the Patterns field.
func (o *PolicyRuleAntivirus) SetPatterns(v []string) {
	o.Patterns = v
}

// GetPolicy returns the Policy field value if set, zero value otherwise.
func (o *PolicyRuleAntivirus) GetPolicy() FixedReferenceWithType {
	if o == nil || IsNil(o.Policy) {
		var ret FixedReferenceWithType
		return ret
	}
	return *o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyRuleAntivirus) GetPolicyOk() (*FixedReferenceWithType, bool) {
	if o == nil || IsNil(o.Policy) {
		return nil, false
	}
	return o.Policy, true
}

// HasPolicy returns a boolean if a field has been set.
func (o *PolicyRuleAntivirus) HasPolicy() bool {
	if o != nil && !IsNil(o.Policy) {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given FixedReferenceWithType and assigns it to the Policy field.
func (o *PolicyRuleAntivirus) SetPolicy(v FixedReferenceWithType) {
	o.Policy = &v
}

// GetRuleClass returns the RuleClass field value if set, zero value otherwise.
func (o *PolicyRuleAntivirus) GetRuleClass() string {
	if o == nil || IsNil(o.RuleClass) {
		var ret string
		return ret
	}
	return *o.RuleClass
}

// GetRuleClassOk returns a tuple with the RuleClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyRuleAntivirus) GetRuleClassOk() (*string, bool) {
	if o == nil || IsNil(o.RuleClass) {
		return nil, false
	}
	return o.RuleClass, true
}

// HasRuleClass returns a boolean if a field has been set.
func (o *PolicyRuleAntivirus) HasRuleClass() bool {
	if o != nil && !IsNil(o.RuleClass) {
		return true
	}

	return false
}

// SetRuleClass gets a reference to the given string and assigns it to the RuleClass field.
func (o *PolicyRuleAntivirus) SetRuleClass(v string) {
	o.RuleClass = &v
}

// GetTimeRemaining returns the TimeRemaining field value if set, zero value otherwise.
func (o *PolicyRuleAntivirus) GetTimeRemaining() int64 {
	if o == nil || IsNil(o.TimeRemaining) {
		var ret int64
		return ret
	}
	return *o.TimeRemaining
}

// GetTimeRemainingOk returns a tuple with the TimeRemaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicyRuleAntivirus) GetTimeRemainingOk() (*int64, bool) {
	if o == nil || IsNil(o.TimeRemaining) {
		return nil, false
	}
	return o.TimeRemaining, true
}

// HasTimeRemaining returns a boolean if a field has been set.
func (o *PolicyRuleAntivirus) HasTimeRemaining() bool {
	if o != nil && !IsNil(o.TimeRemaining) {
		return true
	}

	return false
}

// SetTimeRemaining gets a reference to the given int64 and assigns it to the TimeRemaining field.
func (o *PolicyRuleAntivirus) SetTimeRemaining(v int64) {
	o.TimeRemaining = &v
}

func (o PolicyRuleAntivirus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyRuleAntivirus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.Destroyed) {
		toSerialize["destroyed"] = o.Destroyed
	}
	if !IsNil(o.Effect) {
		toSerialize["effect"] = o.Effect
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.ForceRescanAfter) {
		toSerialize["force_rescan_after"] = o.ForceRescanAfter
	}
	if !IsNil(o.MaxSize) {
		toSerialize["max_size"] = o.MaxSize
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.OnInfectedAction) {
		toSerialize["on_infected_action"] = o.OnInfectedAction
	}
	if !IsNil(o.OnScanFailure) {
		toSerialize["on_scan_failure"] = o.OnScanFailure
	}
	if !IsNil(o.PathPrefix) {
		toSerialize["path_prefix"] = o.PathPrefix
	}
	if !IsNil(o.Patterns) {
		toSerialize["patterns"] = o.Patterns
	}
	if !IsNil(o.Policy) {
		toSerialize["policy"] = o.Policy
	}
	if !IsNil(o.RuleClass) {
		toSerialize["rule_class"] = o.RuleClass
	}
	if !IsNil(o.TimeRemaining) {
		toSerialize["time_remaining"] = o.TimeRemaining
	}
	return toSerialize, nil
}

type NullablePolicyRuleAntivirus struct {
	value *PolicyRuleAntivirus
	isSet bool
}

func (v NullablePolicyRuleAntivirus) Get() *PolicyRuleAntivirus {
	return v.value
}

func (v *NullablePolicyRuleAntivirus) Set(val *PolicyRuleAntivirus) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyRuleAntivirus) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyRuleAntivirus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyRuleAntivirus(val *PolicyRuleAntivirus) *NullablePolicyRuleAntivirus {
	return &NullablePolicyRuleAntivirus{value: val, isSet: true}
}

func (v NullablePolicyRuleAntivirus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyRuleAntivirus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
