/*
FlashArray REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.51
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the SupportRemoteAssistSessionsPatch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SupportRemoteAssistSessionsPatch{}

// SupportRemoteAssistSessionsPatch struct for SupportRemoteAssistSessionsPatch
type SupportRemoteAssistSessionsPatch struct {
	// Overrides the default access level for the remote assist session only. Values include `restricted` and `elevated`. If not provided, the remote assist session will use the default_access_level setting.
	AccessLevelOverride *string `json:"access_level_override,omitempty"`
	// The status of a remote assist session. If set to `true`, enables the remote assist session. If set to `false`, disables the remote assist session.
	Active *bool `json:"active,omitempty"`
	// Specifies the duration of the remote assist session in milliseconds. This parameter should only be provided when establishing a new session. This parameter determines the length of time the session will remain active after initiation. Defaults to 86400000 (24h) with a min of 14400000 (4h) and a max of 172800000 (48h).
	Duration *int64 `json:"duration,omitempty"`
}

// NewSupportRemoteAssistSessionsPatch instantiates a new SupportRemoteAssistSessionsPatch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupportRemoteAssistSessionsPatch() *SupportRemoteAssistSessionsPatch {
	this := SupportRemoteAssistSessionsPatch{}
	return &this
}

// NewSupportRemoteAssistSessionsPatchWithDefaults instantiates a new SupportRemoteAssistSessionsPatch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupportRemoteAssistSessionsPatchWithDefaults() *SupportRemoteAssistSessionsPatch {
	this := SupportRemoteAssistSessionsPatch{}
	return &this
}

// GetAccessLevelOverride returns the AccessLevelOverride field value if set, zero value otherwise.
func (o *SupportRemoteAssistSessionsPatch) GetAccessLevelOverride() string {
	if o == nil || IsNil(o.AccessLevelOverride) {
		var ret string
		return ret
	}
	return *o.AccessLevelOverride
}

// GetAccessLevelOverrideOk returns a tuple with the AccessLevelOverride field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SupportRemoteAssistSessionsPatch) GetAccessLevelOverrideOk() (*string, bool) {
	if o == nil || IsNil(o.AccessLevelOverride) {
		return nil, false
	}
	return o.AccessLevelOverride, true
}

// HasAccessLevelOverride returns a boolean if a field has been set.
func (o *SupportRemoteAssistSessionsPatch) HasAccessLevelOverride() bool {
	if o != nil && !IsNil(o.AccessLevelOverride) {
		return true
	}

	return false
}

// SetAccessLevelOverride gets a reference to the given string and assigns it to the AccessLevelOverride field.
func (o *SupportRemoteAssistSessionsPatch) SetAccessLevelOverride(v string) {
	o.AccessLevelOverride = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *SupportRemoteAssistSessionsPatch) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SupportRemoteAssistSessionsPatch) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *SupportRemoteAssistSessionsPatch) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *SupportRemoteAssistSessionsPatch) SetActive(v bool) {
	o.Active = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *SupportRemoteAssistSessionsPatch) GetDuration() int64 {
	if o == nil || IsNil(o.Duration) {
		var ret int64
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SupportRemoteAssistSessionsPatch) GetDurationOk() (*int64, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *SupportRemoteAssistSessionsPatch) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int64 and assigns it to the Duration field.
func (o *SupportRemoteAssistSessionsPatch) SetDuration(v int64) {
	o.Duration = &v
}

func (o SupportRemoteAssistSessionsPatch) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SupportRemoteAssistSessionsPatch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccessLevelOverride) {
		toSerialize["access_level_override"] = o.AccessLevelOverride
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	return toSerialize, nil
}

type NullableSupportRemoteAssistSessionsPatch struct {
	value *SupportRemoteAssistSessionsPatch
	isSet bool
}

func (v NullableSupportRemoteAssistSessionsPatch) Get() *SupportRemoteAssistSessionsPatch {
	return v.value
}

func (v *NullableSupportRemoteAssistSessionsPatch) Set(val *SupportRemoteAssistSessionsPatch) {
	v.value = val
	v.isSet = true
}

func (v NullableSupportRemoteAssistSessionsPatch) IsSet() bool {
	return v.isSet
}

func (v *NullableSupportRemoteAssistSessionsPatch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupportRemoteAssistSessionsPatch(val *SupportRemoteAssistSessionsPatch) *NullableSupportRemoteAssistSessionsPatch {
	return &NullableSupportRemoteAssistSessionsPatch{value: val, isSet: true}
}

func (v NullableSupportRemoteAssistSessionsPatch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupportRemoteAssistSessionsPatch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
