/*
FlashBlade REST API

OpenAPI specification for FlashBlade REST API, developed by Everpure, Inc. (https://www.everpuredata.com/).

API version: 2.26
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the UserGroupQuotaPolicyRuleBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserGroupQuotaPolicyRuleBase{}

// UserGroupQuotaPolicyRuleBase struct for UserGroupQuotaPolicyRuleBase
type UserGroupQuotaPolicyRuleBase struct {
	// A non-modifiable, globally unique ID chosen by the system.
	Id *string `json:"id,omitempty"`
	// Name of the object (e.g., a file system or snapshot).
	Name *string `json:"name,omitempty"`
	// If set to `true`, this rule describes an enforced quota. A quota error is issued if the logical space usage of the subject exceeds the limit value described in this rule.
	Enforced *bool `json:"enforced,omitempty"`
	// Specifies whether to send notifications to the affected quota subject or not. Valid values are `None` and `Account`. Defaults to `Account`.
	Notifications *string `json:"notifications,omitempty"`
	// The policy to which this rule belongs.
	Policy *FixedReference `json:"policy,omitempty"`
	// The policy's version. This can be used when updating the resource to ensure there aren't any updates to the policy since the resource was read.
	PolicyVersion *string `json:"policy_version,omitempty"`
	// The limit of the quota (in bytes) for the specified user, cannot be `0`. If specified, this value will override the default quota for that particular subject type.
	QuotaLimit *int64 `json:"quota_limit,omitempty"`
	// Specifies quota type for the quota policy. Valid values are `user`, `group`, `user-default`and `group-default`. `user-default` and `group-default` cannot be specified with a subject.
	QuotaType *string `json:"quota_type,omitempty"`
	// The user or group subject on which this rule is applied
	Subject *UserGroupQuotaSubject `json:"subject,omitempty"`
}

// NewUserGroupQuotaPolicyRuleBase instantiates a new UserGroupQuotaPolicyRuleBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserGroupQuotaPolicyRuleBase() *UserGroupQuotaPolicyRuleBase {
	this := UserGroupQuotaPolicyRuleBase{}
	return &this
}

// NewUserGroupQuotaPolicyRuleBaseWithDefaults instantiates a new UserGroupQuotaPolicyRuleBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserGroupQuotaPolicyRuleBaseWithDefaults() *UserGroupQuotaPolicyRuleBase {
	this := UserGroupQuotaPolicyRuleBase{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UserGroupQuotaPolicyRuleBase) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserGroupQuotaPolicyRuleBase) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UserGroupQuotaPolicyRuleBase) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UserGroupQuotaPolicyRuleBase) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UserGroupQuotaPolicyRuleBase) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserGroupQuotaPolicyRuleBase) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UserGroupQuotaPolicyRuleBase) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UserGroupQuotaPolicyRuleBase) SetName(v string) {
	o.Name = &v
}

// GetEnforced returns the Enforced field value if set, zero value otherwise.
func (o *UserGroupQuotaPolicyRuleBase) GetEnforced() bool {
	if o == nil || IsNil(o.Enforced) {
		var ret bool
		return ret
	}
	return *o.Enforced
}

// GetEnforcedOk returns a tuple with the Enforced field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserGroupQuotaPolicyRuleBase) GetEnforcedOk() (*bool, bool) {
	if o == nil || IsNil(o.Enforced) {
		return nil, false
	}
	return o.Enforced, true
}

// HasEnforced returns a boolean if a field has been set.
func (o *UserGroupQuotaPolicyRuleBase) HasEnforced() bool {
	if o != nil && !IsNil(o.Enforced) {
		return true
	}

	return false
}

// SetEnforced gets a reference to the given bool and assigns it to the Enforced field.
func (o *UserGroupQuotaPolicyRuleBase) SetEnforced(v bool) {
	o.Enforced = &v
}

// GetNotifications returns the Notifications field value if set, zero value otherwise.
func (o *UserGroupQuotaPolicyRuleBase) GetNotifications() string {
	if o == nil || IsNil(o.Notifications) {
		var ret string
		return ret
	}
	return *o.Notifications
}

// GetNotificationsOk returns a tuple with the Notifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserGroupQuotaPolicyRuleBase) GetNotificationsOk() (*string, bool) {
	if o == nil || IsNil(o.Notifications) {
		return nil, false
	}
	return o.Notifications, true
}

// HasNotifications returns a boolean if a field has been set.
func (o *UserGroupQuotaPolicyRuleBase) HasNotifications() bool {
	if o != nil && !IsNil(o.Notifications) {
		return true
	}

	return false
}

// SetNotifications gets a reference to the given string and assigns it to the Notifications field.
func (o *UserGroupQuotaPolicyRuleBase) SetNotifications(v string) {
	o.Notifications = &v
}

// GetPolicy returns the Policy field value if set, zero value otherwise.
func (o *UserGroupQuotaPolicyRuleBase) GetPolicy() FixedReference {
	if o == nil || IsNil(o.Policy) {
		var ret FixedReference
		return ret
	}
	return *o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserGroupQuotaPolicyRuleBase) GetPolicyOk() (*FixedReference, bool) {
	if o == nil || IsNil(o.Policy) {
		return nil, false
	}
	return o.Policy, true
}

// HasPolicy returns a boolean if a field has been set.
func (o *UserGroupQuotaPolicyRuleBase) HasPolicy() bool {
	if o != nil && !IsNil(o.Policy) {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given FixedReference and assigns it to the Policy field.
func (o *UserGroupQuotaPolicyRuleBase) SetPolicy(v FixedReference) {
	o.Policy = &v
}

// GetPolicyVersion returns the PolicyVersion field value if set, zero value otherwise.
func (o *UserGroupQuotaPolicyRuleBase) GetPolicyVersion() string {
	if o == nil || IsNil(o.PolicyVersion) {
		var ret string
		return ret
	}
	return *o.PolicyVersion
}

// GetPolicyVersionOk returns a tuple with the PolicyVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserGroupQuotaPolicyRuleBase) GetPolicyVersionOk() (*string, bool) {
	if o == nil || IsNil(o.PolicyVersion) {
		return nil, false
	}
	return o.PolicyVersion, true
}

// HasPolicyVersion returns a boolean if a field has been set.
func (o *UserGroupQuotaPolicyRuleBase) HasPolicyVersion() bool {
	if o != nil && !IsNil(o.PolicyVersion) {
		return true
	}

	return false
}

// SetPolicyVersion gets a reference to the given string and assigns it to the PolicyVersion field.
func (o *UserGroupQuotaPolicyRuleBase) SetPolicyVersion(v string) {
	o.PolicyVersion = &v
}

// GetQuotaLimit returns the QuotaLimit field value if set, zero value otherwise.
func (o *UserGroupQuotaPolicyRuleBase) GetQuotaLimit() int64 {
	if o == nil || IsNil(o.QuotaLimit) {
		var ret int64
		return ret
	}
	return *o.QuotaLimit
}

// GetQuotaLimitOk returns a tuple with the QuotaLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserGroupQuotaPolicyRuleBase) GetQuotaLimitOk() (*int64, bool) {
	if o == nil || IsNil(o.QuotaLimit) {
		return nil, false
	}
	return o.QuotaLimit, true
}

// HasQuotaLimit returns a boolean if a field has been set.
func (o *UserGroupQuotaPolicyRuleBase) HasQuotaLimit() bool {
	if o != nil && !IsNil(o.QuotaLimit) {
		return true
	}

	return false
}

// SetQuotaLimit gets a reference to the given int64 and assigns it to the QuotaLimit field.
func (o *UserGroupQuotaPolicyRuleBase) SetQuotaLimit(v int64) {
	o.QuotaLimit = &v
}

// GetQuotaType returns the QuotaType field value if set, zero value otherwise.
func (o *UserGroupQuotaPolicyRuleBase) GetQuotaType() string {
	if o == nil || IsNil(o.QuotaType) {
		var ret string
		return ret
	}
	return *o.QuotaType
}

// GetQuotaTypeOk returns a tuple with the QuotaType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserGroupQuotaPolicyRuleBase) GetQuotaTypeOk() (*string, bool) {
	if o == nil || IsNil(o.QuotaType) {
		return nil, false
	}
	return o.QuotaType, true
}

// HasQuotaType returns a boolean if a field has been set.
func (o *UserGroupQuotaPolicyRuleBase) HasQuotaType() bool {
	if o != nil && !IsNil(o.QuotaType) {
		return true
	}

	return false
}

// SetQuotaType gets a reference to the given string and assigns it to the QuotaType field.
func (o *UserGroupQuotaPolicyRuleBase) SetQuotaType(v string) {
	o.QuotaType = &v
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *UserGroupQuotaPolicyRuleBase) GetSubject() UserGroupQuotaSubject {
	if o == nil || IsNil(o.Subject) {
		var ret UserGroupQuotaSubject
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserGroupQuotaPolicyRuleBase) GetSubjectOk() (*UserGroupQuotaSubject, bool) {
	if o == nil || IsNil(o.Subject) {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *UserGroupQuotaPolicyRuleBase) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given UserGroupQuotaSubject and assigns it to the Subject field.
func (o *UserGroupQuotaPolicyRuleBase) SetSubject(v UserGroupQuotaSubject) {
	o.Subject = &v
}

func (o UserGroupQuotaPolicyRuleBase) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserGroupQuotaPolicyRuleBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Enforced) {
		toSerialize["enforced"] = o.Enforced
	}
	if !IsNil(o.Notifications) {
		toSerialize["notifications"] = o.Notifications
	}
	if !IsNil(o.Policy) {
		toSerialize["policy"] = o.Policy
	}
	if !IsNil(o.PolicyVersion) {
		toSerialize["policy_version"] = o.PolicyVersion
	}
	if !IsNil(o.QuotaLimit) {
		toSerialize["quota_limit"] = o.QuotaLimit
	}
	if !IsNil(o.QuotaType) {
		toSerialize["quota_type"] = o.QuotaType
	}
	if !IsNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	return toSerialize, nil
}

type NullableUserGroupQuotaPolicyRuleBase struct {
	value *UserGroupQuotaPolicyRuleBase
	isSet bool
}

func (v NullableUserGroupQuotaPolicyRuleBase) Get() *UserGroupQuotaPolicyRuleBase {
	return v.value
}

func (v *NullableUserGroupQuotaPolicyRuleBase) Set(val *UserGroupQuotaPolicyRuleBase) {
	v.value = val
	v.isSet = true
}

func (v NullableUserGroupQuotaPolicyRuleBase) IsSet() bool {
	return v.isSet
}

func (v *NullableUserGroupQuotaPolicyRuleBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserGroupQuotaPolicyRuleBase(val *UserGroupQuotaPolicyRuleBase) *NullableUserGroupQuotaPolicyRuleBase {
	return &NullableUserGroupQuotaPolicyRuleBase{value: val, isSet: true}
}

func (v NullableUserGroupQuotaPolicyRuleBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserGroupQuotaPolicyRuleBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
