/*
FlashBlade REST API

A lightweight client for FlashBlade REST API 2.9, developed by Pure Storage, Inc. (http://www.purestorage.com/).

API version: 2.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopureclient

import (
	"encoding/json"
)

// checks if the MultiProtocolPost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MultiProtocolPost{}

// MultiProtocolPost struct for MultiProtocolPost
type MultiProtocolPost struct {
	// The access control style that is utilized for client actions such as setting file and directory ACLs. Possible values include `nfs`, `smb`, `shared`, `independent`, and `mode-bits`. If `nfs` is specified, then SMB clients will be unable to set permissions on files and directories. If `smb` is specified, then NFS clients will be unable to set permissions on files and directories. If `shared` is specified, then NFS and SMB clients will both be able to set permissions on files and directories. Any client will be able to overwrite the permissions set by another client, regardless of protocol. If `independent` is specified, then NFS and SMB clients will both be able to set permissions on files and directories, and can access files and directories created over any protocol. Permissions set by SMB clients will not affect NFS clients and vice versa. NFS clients will be restricted to only using mode bits to set permissions. If `mode-bits` is specified, then NFS and SMB clients will both be able to set permissions on files and directories, but only mode bits may be used to set permissions for NFS clients. When SMB clients set an ACL, it will be converted to have the same permission granularity as NFS mode bits. Defaults to `shared`.
	AccessControlStyle *string `json:"access_control_style,omitempty"`
	// If set to `true`, prevents NFS clients from erasing a configured ACL when setting NFS mode bits. If this is `true`, then attempts to set mode bits on a file or directory will fail if they cannot be combined with the existing ACL set on a file or directory without erasing the ACL. Attempts to set mode bits that would not erase an existing ACL will still succeed and the mode bit changes will be merged with the existing ACL. This must be `false` when `access_control_style` is set to either `independent` or `mode-bits`. Defaults to `true`.
	SafeguardAcls *bool `json:"safeguard_acls,omitempty"`
}

// NewMultiProtocolPost instantiates a new MultiProtocolPost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMultiProtocolPost() *MultiProtocolPost {
	this := MultiProtocolPost{}
	return &this
}

// NewMultiProtocolPostWithDefaults instantiates a new MultiProtocolPost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMultiProtocolPostWithDefaults() *MultiProtocolPost {
	this := MultiProtocolPost{}
	return &this
}

// GetAccessControlStyle returns the AccessControlStyle field value if set, zero value otherwise.
func (o *MultiProtocolPost) GetAccessControlStyle() string {
	if o == nil || IsNil(o.AccessControlStyle) {
		var ret string
		return ret
	}
	return *o.AccessControlStyle
}

// GetAccessControlStyleOk returns a tuple with the AccessControlStyle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiProtocolPost) GetAccessControlStyleOk() (*string, bool) {
	if o == nil || IsNil(o.AccessControlStyle) {
		return nil, false
	}
	return o.AccessControlStyle, true
}

// HasAccessControlStyle returns a boolean if a field has been set.
func (o *MultiProtocolPost) HasAccessControlStyle() bool {
	if o != nil && !IsNil(o.AccessControlStyle) {
		return true
	}

	return false
}

// SetAccessControlStyle gets a reference to the given string and assigns it to the AccessControlStyle field.
func (o *MultiProtocolPost) SetAccessControlStyle(v string) {
	o.AccessControlStyle = &v
}

// GetSafeguardAcls returns the SafeguardAcls field value if set, zero value otherwise.
func (o *MultiProtocolPost) GetSafeguardAcls() bool {
	if o == nil || IsNil(o.SafeguardAcls) {
		var ret bool
		return ret
	}
	return *o.SafeguardAcls
}

// GetSafeguardAclsOk returns a tuple with the SafeguardAcls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MultiProtocolPost) GetSafeguardAclsOk() (*bool, bool) {
	if o == nil || IsNil(o.SafeguardAcls) {
		return nil, false
	}
	return o.SafeguardAcls, true
}

// HasSafeguardAcls returns a boolean if a field has been set.
func (o *MultiProtocolPost) HasSafeguardAcls() bool {
	if o != nil && !IsNil(o.SafeguardAcls) {
		return true
	}

	return false
}

// SetSafeguardAcls gets a reference to the given bool and assigns it to the SafeguardAcls field.
func (o *MultiProtocolPost) SetSafeguardAcls(v bool) {
	o.SafeguardAcls = &v
}

func (o MultiProtocolPost) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MultiProtocolPost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccessControlStyle) {
		toSerialize["access_control_style"] = o.AccessControlStyle
	}
	if !IsNil(o.SafeguardAcls) {
		toSerialize["safeguard_acls"] = o.SafeguardAcls
	}
	return toSerialize, nil
}

type NullableMultiProtocolPost struct {
	value *MultiProtocolPost
	isSet bool
}

func (v NullableMultiProtocolPost) Get() *MultiProtocolPost {
	return v.value
}

func (v *NullableMultiProtocolPost) Set(val *MultiProtocolPost) {
	v.value = val
	v.isSet = true
}

func (v NullableMultiProtocolPost) IsSet() bool {
	return v.isSet
}

func (v *NullableMultiProtocolPost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMultiProtocolPost(val *MultiProtocolPost) *NullableMultiProtocolPost {
	return &NullableMultiProtocolPost{value: val, isSet: true}
}

func (v NullableMultiProtocolPost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMultiProtocolPost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
